### ISSUE TITLE
[Exception][PhpStorm 2022.1.4] com.intellij.diagnostic.PluginException: Cannot create class ai.codium.analytic.Codium...

### ISSUE THREAD

**Issue by KoskeyHoward** [Codium-ai/codiumai-jetbrains-release#101]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
com.intellij.diagnostic.PluginException: Cannot create class ai.codium.analytic.CodiumAnalyticService (classloader=PluginClassLoader(plugin=PluginDescriptor(name=CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4, id=codiumai.codiumai, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/PhpStorm2022.1/plugins/codium-ai-plugin-0.6.02.jar, version=0.6.02, package=null, isBundled=false), packagePrefix=null, instanceId=129, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:884)
	at com.intellij.serviceContainer.ComponentManagerImpl.createLightService(ComponentManagerImpl.kt:824)
	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:670)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:622)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:584)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at ai.codium.UtilsKt.getCodiumAnalyticService(Utils.kt:262)
	at ai.codium.ui.CodiumLoginPanel.<init>(CodiumLoginPanel.kt:49)
	at ai.codium.ui.CodiumToolWindowFactory$createToolWindowContent$3.newLoginRequired$lambda$1(CodiumToolWindowFactory.kt:127)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.NoClassDefFoundError: com/mixpanel/mixpanelapi/MixpanelAPI
	at ai.codium.analytic.CodiumAnalyticService.<init>(CodiumAnalyticService.kt:26)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:845)
	... 40 more

```

# Other Information
```
=== About ===
Build version: PhpStorm 2022.1.4 Build: #PS-221.6008.16 July 20, 2022
Theme: Darcula
JRE: 11.0.15+10-b2043.56, JetBrains s.r.o.
JVM: 11.0.15+10-b2043.56, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.2 (x86_64, emulated)

=== Plugins ===
Custom plugins: [PHP Annotations (8.3.0), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.6.02), .env files support (2022.1)]
Disabled plugins:[]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/8wnREeS8) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Seems like plugin dependencies are missing. 🤔
Did you install plugin from marketplace or manually? If latter then did you you use original zip file or unzip it and use jar?

**Comment by ArtsiomCh** [comment]
Please re-install plugin from marketplace, or install it manually from **zip** not from unzipped jar
