### ISSUE TITLE
[Exception][IDEA 2023.2.1] com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl.sou...

### ISSUE THREAD

**Issue by Portur** [Codium-ai/codiumai-jetbrains-release#105]
# User Description
I was renaming/restructuring TypeScript types

# Stack Trace
```
com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl.source.tree.CompositeElement of type JS:TYPESCRIPT_CLASS (class com.intellij.lang.javascript.types.TypeScriptClassElementType)
	at com.intellij.psi.PsiInvalidElementAccessException.createByNode(PsiInvalidElementAccessException.java:80)
	at com.intellij.psi.impl.source.SubstrateRef$2.getContainingFile(SubstrateRef.java:74)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:235)
	at com.intellij.codeInsight.intention.preview.IntentionPreviewUtils.isPreviewElement(IntentionPreviewUtils.java:64)
	at com.intellij.lang.javascript.psi.resolve.AccessibilityProcessingHandler.getRealElement(AccessibilityProcessingHandler.java:253)
	at com.intellij.lang.javascript.psi.resolve.AccessibilityProcessingHandler.startingParent(AccessibilityProcessingHandler.java:265)
	at com.intellij.lang.javascript.psi.resolve.ResolveProcessor.startingParent(ResolveProcessor.java:154)
	at com.intellij.lang.javascript.psi.resolve.ResolveProcessor.handleEvent(ResolveProcessor.java:142)
	at com.intellij.lang.javascript.psi.ecma6.impl.TypeScriptClassBase.processDeclarations(TypeScriptClassBase.java:99)
	at com.intellij.lang.javascript.psi.ecmal4.impl.JSClassBase.gatherDeclarations(JSClassBase.java:172)
	at com.intellij.lang.javascript.psi.ecmal4.impl.JSClassBase.getFunctions(JSClassBase.java:129)
	at ai.codium.language.JsTsLanguageService.doGetSupportedElementsForClass$codium_ai_plugin(JsTsLanguageService.kt:55)
	at ai.codium.language.LanguageService.getSupportedElementsForClass(LanguageService.kt:39)
	at ai.codium.ui.structureview.CodiumStructureViewChildElement.getChildren(CodiumStructureViewChildElement.kt:44)
	at ai.codium.ui.structureview.CodiumStructureViewChildElement.getChildren(CodiumStructureViewChildElement.kt:26)
	at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.initChildren(TreeElementWrapper.java:35)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.rebuildSubtree(CachingChildrenTreeNode.java:207)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.ensureChildrenAreInitialized(CachingChildrenTreeNode.java:41)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.getChildren(CachingChildrenTreeNode.java:33)
	at com.intellij.ide.structureView.newStructureView.StructureViewComponent$MyNodeWrapper.getChildren(StructureViewComponent.java:841)
	at com.intellij.ide.util.treeView.smartTree.SmartTreeStructure.getChildElements(SmartTreeStructure.java:62)
	at com.intellij.ui.tre

<TRIMMED STACKTRACE>

ogress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:111)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:76)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:188)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:165)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:433)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2023.2.1 Build: #IU-232.9559.62 August 23, 2023
Theme: Darcula
JRE: 17.0.8+7-b1000.8, JetBrains s.r.o.
JVM: 17.0.8+7-b1000.8, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.5.1 (aarch64)

=== Plugins ===
Custom plugins: [Python (232.9559.62), DarkTheme (1.0.4), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.6.03), Darcula Darker Theme (1.2.0), .env files support (2023.2), Interesting Theme (1.3), EJS (232.8660.142), GraphQL (4.0.2), One Dark theme (5.8.0), Prisma ORM (232.9559.10), Base16 Tomorrow Dark Theme (1.0.4), .ignore (4.5.1), String Manipulation (9.11.3), Package Search (232.9559.10), CSV Editor (3.2.1-232), Live Edit (232.8660.142), Database Navigator (3.3.9995.0), EnvFile (3.4.1)]
Disabled plugins:[Prisma (1.2.5), Go (232.9559.65), Android Design Tools (232.9559.62), Yet another emoji support (1.0.7), Lotus Theme (1.10), New Relic CodeStream (14.28.0+511), Ktor (232.9559.62), Kotlin (232-1.9.0-IJ9559.62), Terraform and HCL (232.8660.88), WakaTime (14.2.1), Android (2022.3.1 Final.232.9559.62), Dev Containers (232.9559.62), Spacegray Theme (1.5.1), Tabnine: AI Code Completion & Chat in Java JS/TS Python & More (1.0.51), Nord (0.13.0)]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/bk2uh4EO) by [Unito](https://www.unito.io)

**Comment by aldanchenko** [comment]
Hi @Portur 

Thanks for reporting!

Best regards,
Alex

**Comment by ArtsiomCh** [comment]
Sorry for late response 😔
Do you still experience such issues? 
Seems like we fixed them in latest versions, but want to clarify that with use

**Comment by Portur** [comment]
I have not :)
