### ISSUE TITLE
[Exception][Rider 2023.1 EAP 9] java.lang.RuntimeException: Cannot invoke (class=, method=newLoginRequired, topic=Cod...

### ISSUE THREAD

**Issue by jeansw** [Codium-ai/codiumai-jetbrains-release#11]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.RuntimeException: Cannot invoke (class=, method=newLoginRequired, topic=Codium login events)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:657)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:415)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:394)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:454)
	at jdk.proxy7/jdk.proxy7.$Proxy191.newLoginRequired(Unknown Source)
	at ai.codium.UtilsKt.isUserLogged(Utils.kt:55)
	at ai.codium.ui.CodiumToolWindowFactory.createToolWindowContent$showDefaultContentByLoggedStatus$lambda$1(CodiumToolWindowFactory.kt:40)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:570)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: com.intellij.diagnostic.PluginException: Cannot create class ai.codium.analytic.CodiumAnalyticService (classloader=PluginClassLoader(plugin=PluginDescriptor(name=CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4, id=codiumai.codiumai, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/Rider2023.1/plugins/codium-ai-plugin-0.4.7.jar, version=0.4.7, package=null, isBundled=false), packagePrefix=null, instanceId=102, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1034)
	at com.intellij.serviceContainer.ComponentManagerImpl.createLightService(ComponentManagerImpl.kt:970)
	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:774)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:726)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:670)
	at ai.codium.UtilsKt.getCodiumAnalyticService(Utils.kt:128)
	at ai.codium.ui.CodiumLoginPanel.<init>(CodiumLoginPanel.kt:43)
	at ai.codium.ui.CodiumToolWindowFactory$createToolWindowContent$2.newLoginRequired(CodiumToolWindowFactory.kt:68)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:677)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:640)
	... 44 more
Caused by: java.lang.NoClassDefFoundError: com/mixpanel/mixpanelapi/MixpanelAPI
	at ai.codium.analytic.CodiumAnalyticService.<init>(CodiumAnalyticService.kt:27)
	at com.intellij.service

<TRIMMED STACKTRACE>
```

# Other Information
```
=== About ===
Build version: JetBrains Rider 2023.1 EAP 9 Build: #RD-231.8109.136 March 22, 2023
Theme: Rider Night
JRE: 17.0.6+10-b829.5, JetBrains s.r.o.
JVM: 17.0.6+10-b829.5, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.1 (aarch64)

=== Plugins ===
Custom plugins: [Prettier (231.8109.147), GitHub Copilot (1.2.4.2459), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.4.7), .env files support (2023.1)]
Disabled plugins:[F# Support (2023.1.71), Mercurial (231.8109.136), Unity Support (2023.1.0.71), .ignore (4.5.0), Perforce Helix Core (231.8109.136), Subversion (231.8109.136), Database Tools and SQL (231.8109.136)]
```

**Comment by ArtsiomCh** [comment]
Please update to the 0.4.8 and let us know please if that exception happened again.

**Comment by jeansw** [comment]
Looks good now!
