### ISSUE TITLE
[Exception][PyCharm 2023.2.1] java.util.ConcurrentModificationException: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by Krytos** [Codium-ai/codiumai-jetbrains-release#111]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.util.ConcurrentModificationException: java.util.ConcurrentModificationException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562)
	at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981)
	at com.intellij.util.ConcurrencyUtil.manifestExceptionsIn(ConcurrencyUtil.java:277)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$queuePassesCreation$21(DaemonCodeAnalyzerImpl.java:1084)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)


<TRIMMED STACKTRACE>

itorBackgroundHighlighter.lambda$getPasses$0(TextEditorBackgroundHighlighter.java:85)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.computeWithSpanIgnoreThrows(trace.kt:73)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.computeWithSpanThrows(TraceUtil.java:18)
	at com.intellij.codeInsight.daemon.impl.TextEditorBackgroundHighlighter.getPasses(TextEditorBackgroundHighlighter.java:80)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$submitInBackground$24(DaemonCodeAnalyzerImpl.java:1131)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:923)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:76)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$submitInBackground$25(DaemonCodeAnalyzerImpl.java:1120)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.submitInBackground(DaemonCodeAnalyzerImpl.java:1117)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$queuePassesCreation$20(DaemonCodeAnalyzerImpl.java:1082)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:190)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

# Other Information
```
=== About ===
Build version: PyCharm 2023.2.1 Build: #PY-232.9559.58 August 22, 2023
Theme: One Dark
JRE: 17.0.8+7-b1000.8, JetBrains s.r.o.
JVM: 17.0.8+7-b1000.8, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [CodeGlance Pro (1.7.5), One Dark theme (5.8.0), Mypy (0.16.0), GitHub Copilot (1.2.22.3129), Regexp Tester (2.2.0), .ignore (4.5.1), Requirements (2022.4.1), Indent Rainbow (2.2.0), EmmyLua (1.4.7-IDEA231), Kubernetes (232.9559.34), Rainbow Brackets Lite - Free and OpenSource (1.0.1), Atom One Theme (1.5.1), Google Cloud Code (23.9.1-api-version-222), CMD Support (1.0.5), EnvFile (3.4.1), Ideolog (222.1.0.0), Cyan Light Theme (1.3), Dracula Theme (1.15.1), CodeSnap (1.0.4), CSV Editor (3.2.1-232), CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.6.05)]
Disabled plugins:[ChatGPT - EasyCode (3.1.4-231.232), SSH Remote Run (232.9559.58), Subversion (232.9559.58), Vagrant (232.9559.58), Space (232.9559.58), Node.js Remote Interpreter (232.9559.58), FTP/SFTP/WebDAV Connectivity (232.9559.58), Shared Indexes for Python (232.9559.58), Rainbow Brackets (2023.3.4), Vite (232.9559.58), Sass (232.9559.58), TSLint (232.9559.58), Puppet (232.9559.58), OpenAPI Specifications (232.9559.58), Perforce Helix Core (232.9559.58), Karma (232.9559.58), ReStructuredText (232.9559.58), Gherkin (232.9559.58), JavaScript Intention Power Pack (232.9559.58), WSL Support Framework (232.9559.58), Mercurial (232.9559.58), IDE Features Trainer (232.9559.58), IntelliLang (232.9559.58), Polymer & Web Components (232.9559.58), Endpoints (232.9559.58), HTTP Client (232.9559.58), Styled Components & Styled JSX (232.9559.58), Angular and AngularJS (232.9559.58), Vue.js (232.9559.58), GNU GetText files support (*.po) (232.9559.58), File Watchers (232.9559.58), TextMate Bundles (232.9559.58), PyScript (232.9559.58), Copyright (232.9559.58), Shared Project Indexes (232.9559.58), Webpack (232.9559.58), Less (232.9559.58)]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/fOaRyeaR) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Fixed in 0.6.06
