### ISSUE TITLE
[Exception][WebStorm 2023.2.2] com.intellij.diagnostic.PluginException: ID 'Commit.Button' is already taken by action...

### ISSUE THREAD

**Issue by renews** [Codium-ai/codiumai-jetbrains-release#112]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
com.intellij.diagnostic.PluginException: ID 'Commit.Button' is already taken by action 'Create commit message (Create commit message)' (class com.intellij.openapi.actionSystem.impl.ChameleonAction)  (Plugin: Git Commit Template). Action 'Generate Commit Message (null)' (class com.intellij.openapi.actionSystem.ActionStub) cannot use the same ID codiumai.codiumai [Plugin: codiumai.codiumai]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionIdCollision(ActionManagerImpl.kt:979)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.kt:918)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerOrReplaceActionInner(ActionManagerImpl.kt:470)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processActionElement(ActionManagerImpl.kt:443)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerPluginActions(ActionManagerImpl.kt:272)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerActions$intellij_platform_ide_impl(ActionManagerImpl.kt:145)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init>(ActionManagerImpl.kt:118)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:63)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:1011)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:43)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:158)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:137)
	at

<TRIMMED STACKTRACE>

er.access$createInstance(BaseComponentAdapter.kt:21)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invokeSuspend(BaseComponentAdapter.kt:185)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceAsync(BaseComponentAdapter.kt:180)
	at com.intellij.serviceContainer.ComponentManagerImpl.getServiceAsyncIfDefined(ComponentManagerImpl.kt:646)
	at com.intellij.serviceContainer.ComponentManagerImpl.getServiceAsync(ComponentManagerImpl.kt:637)
	at com.intellij.ide.bootstrap.AppServicePreloadingKt$preloadCriticalServices$2$7.invokeSuspend(appServicePreloading.kt:179)
	at com.intellij.ide.bootstrap.AppServicePreloadingKt$preloadCriticalServices$2$7.invoke(appServicePreloading.kt)
	at com.intellij.ide.bootstrap.AppServicePreloadingKt$preloadCriticalServices$2$7.invoke(appServicePreloading.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.diagnostic.TracerKt.subtask(tracer.kt:45)
	at com.intellij.diagnostic.TracerKt.subtask$default(tracer.kt:34)
	at com.intellij.ide.bootstrap.AppServicePreloadingKt$preloadCriticalServices$2.invokeSuspend(appServicePreloading.kt:105)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```

# Other Information
```
=== About ===
Build version: WebStorm 2023.2.2 Build: #WS-232.9921.42 September 12, 2023
Theme: Gruvbox Dark Hard
JRE: 17.0.8+7-b1000.22, JetBrains s.r.o.
JVM: 17.0.8+7-b1000.22, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.5.2 (x86_64)

=== Plugins ===
Custom plugins: [AsciiDoc (0.38.20), [Deprecated] Rust (0.4.201.5424-232), .env files support (2023.2), Regex Rename Files (1.2.5), CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.6.06), Apache config (.htaccess) (232.9921.36), String Manipulation (9.11.3), Shifter (1.9.6), React Buddy (2023.3-232), FlutterJsonBeanFactory (2.4), Extra ToolWindow Colorful Icons (1.27.0), GitHub Copilot (1.2.22.3129), Makefile Language (232.8660.88), Atom Material Icons (93.1.0), Tailwind Formatter (2.0.8), Kubernetes (232.9921.28), Mermaid (0.0.14+IJ.232), GitHub Codespaces (0.5.0.1214), Dart (232.9559.10), Vue Component Creator (2.7.3), Gruvbox - Theme (0.6.1), Rainbow Brackets (2023.3.4), Ini (232.9921.36), Translation (3.5.4), JetBrains Academy (2023.8-2023.2-460), Toml (232.8660.88), Git Commit Template (1.2.0), Ideolog (222.1.0.0), Svelte (232.9921.36), Dash (3.3), JsonToDart (JSON To Dart) (2.16), .ignore (4.5.1), Better Highlights (2023.7.12), CSV Editor (3.2.1-232), AI Assistant (232.9826)]
Disabled plugins:[NetBeans Keymap (232.9921.42), Big Data Tools Core (232.9559.62), Eclipse Keymap (232.9921.42), Visual Studio Keymap (232.9921.42), Grazie Lite (232.9921.42), GraphQL (4.0.2), Vagrant (232.9921.42), Key Promoter X (2023.2.0), Kafka (232.9559.62), Grazie Pro (0.3.247), AWS Toolkit (1.78-232), Grep Console (12.21.0-IJ2021.1), SonarLint (9.0.0.75308), Fig (2.0.0), IntelliVue (1.1.41), Code With Me (232.9921.42), Remote File Systems (232.9559.62), Big Data File Viewer (232.8660.206)]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/odtgLqha) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Will be fixed in next release 0.6.07
