### ISSUE TITLE
[Exception][IDEA 2022.3.2] com.intellij.diagnostic.PluginException: Cannot create class ai.codium.analytic.CodiumAnal...

### ISSUE THREAD

**Issue by Edward9053** [Codium-ai/codiumai-jetbrains-release#114]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
com.intellij.diagnostic.PluginException: Cannot create class ai.codium.analytic.CodiumAnalyticService (classloader=PluginClassLoader(plugin=PluginDescriptor(name=CodiumAI - Integrity Agent powered by GPT-3.5&4, id=codiumai.codiumai, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2022.3/plugins/codium-ai-plugin-0.6.06.jar, version=0.6.06, package=null, isBundled=false), packagePrefix=null, instanceId=359, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:989)
	at com.intellij.serviceContainer.ComponentManagerImpl.createLightService(ComponentManagerImpl.kt:929)
	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:733)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:685)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:629)
	at ai.codium.UtilsKt.getCodiumAnalyticService(Utils.kt:258)
	at ai.codium.CodiumSettingsService.updatePrevVersionToCurrent(CodiumSettingsService.kt:46)
	at ai.codium.ui.CodiumStatusBarWidget.doInstallOrUpdateActions(CodiumStatusBarWidgetFactory.kt:78)
	at ai.codium.ui.CodiumStatusBarWidget.doInstallOrUpdateActions$default(CodiumStatusBarWidgetFactory.kt:51)
	at ai.codium.ui.CodiumStatusBarWidget._init_$lambda$4(CodiumStatusBarWidgetFactory.kt:82)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:241)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:377)
	at com.intellij.util.Alarm$Request.run(Alarm.java:366)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.NoClassDefFoundError: com/mixpanel/mixpanelapi/MixpanelAPI
	at ai.codium.analytic.CodiumAnalyticService.<init>(CodiumAnalyticService.kt:26)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:950)
	... 46 more
Caused by: java.lang.ClassNotFoundException: com.mixpanel.mixpanelapi.MixpanelAPI PluginClassLoader(plugin=PluginDescriptor(name=CodiumAI - Integrity Agent powered by GPT-3.5&4, id=codiumai.codiumai, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2022.3/plugins/codium-ai-plugin-0.6.06.jar, version=0.6.06, package=null, isBundled=false), packagePrefix=null, instanceId=359, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:217)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 48 more

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2022.3.2 Build: #IU-223.8617.56 January 26, 2023
Theme: Darcula
JRE: 17.0.5+1-b653.25, JetBrains s.r.o.
JVM: 17.0.5+1-b653.25, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.5.2 (aarch64)

=== Plugins ===
Custom plugins: [Chinese (Simplified) Language Pack / 中文语言包 (223.360), CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.6.06)]
Disabled plugins:[]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/Gkl8EsS4) by [Unito](https://www.unito.io)

**Comment by aldanchenko** [comment]
Hi @CB-FARAZ 

Thanks for reporting!
Please re-install the plugin from the marketplace, or install it manually from the zip not from an unzipped jar.

Best regards,
Alex

**Comment by Edward9053** [comment]
Thanks, Alex
