### ISSUE TITLE
[Exception][PhpStorm 2023.2.1] com.intellij.diagnostic.PluginException: Cannot create class ai.codium.analytic.Codium...

### ISSUE THREAD

**Issue by CB-FARAZ** [Codium-ai/codiumai-jetbrains-release#115]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
com.intellij.diagnostic.PluginException: Cannot create class ai.codium.analytic.CodiumAnalyticService (classloader=PluginClassLoader(plugin=PluginDescriptor(name=CodiumAI - Integrity Agent powered by GPT-3.5&4, id=codiumai.codiumai, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\PhpStorm2023.2\plugins\codium-ai-plugin-0.6.06.jar, version=0.6.06, package=null, isBundled=false), packagePrefix=null, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:1003)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:954)
	at com.intellij.serviceContainer.ComponentManagerImpl.createLightService(ComponentManagerImpl.kt:933)
	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:736)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:688)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:630)
	at ai.codium.UtilsKt.getCodiumAnalyticService(Utils.kt:258)
	at ai.codium.AnalysisManagerKt.runAnalysis(AnalysisManager.kt:44)
	at ai.codium.AnalysisManagerKt.runAnalysis$default(AnalysisManager.kt:33)
	at ai.codium.ui.actions.TestSelectedCodeContextMenuAction.actionPerformed(TestSelectedCodeContextMenuAction.kt:30)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:339)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:313)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:362)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:313)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$performAction$5(ActionMenuItem.java:300)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:226)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.java:293)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$0(ActionMenuItem.java:68)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$4(ActionMenuItem.java:115)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:115)

<TRIMMED STACKTRACE>

nDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:633)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:588)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.NoClassDefFoundError: com/mixpanel/mixpanelapi/MixpanelAPI
	at ai.codium.analytic.CodiumAnalyticService.<init>(CodiumAnalyticService.kt:26)
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:962)
	... 69 more
Caused by: java.lang.ClassNotFoundException: com.mixpanel.mixpanelapi.MixpanelAPI PluginClassLoader(plugin=PluginDescriptor(name=CodiumAI - Integrity Agent powered by GPT-3.5&4, id=codiumai.codiumai, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\PhpStorm2023.2\plugins\codium-ai-plugin-0.6.06.jar, version=0.6.06, package=null, isBundled=false), packagePrefix=null, state=active)
	... 71 more

```

# Other Information
```
=== About ===
Build version: PhpStorm 2023.2.1 Build: #PS-232.9559.64 August 25, 2023
Theme: Dark
JRE: 17.0.8+7-b1000.8, JetBrains s.r.o.
JVM: 17.0.8+7-b1000.8, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 10.0 (amd64)

=== Plugins ===
Custom plugins: [Laravel Query (4.0.2), Git Commit Message Helper (1.1.0), CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.6.06), Material Theme UI (8.11.0), GitHub Theme (1.2.0), PHP CS Fixer (1.0), Atom Material Icons (93.1.0), Carbon (3.0.0), GitHub Dark Theme (1.1.1), Atom One Theme (1.5.1), AI Assistant (232.9826), Rainbow Brackets (2023.3.4), Solarized Chandrian Themes (2.2.2), ANSI Highlighter Premium (23.2.0), .env files support (2023.2), Tabnine: AI Code Completion & Chat in Java JS/TS Python & More (1.5.0)]
Disabled plugins:[Laravel Idea (7.3.0.232), CodeGPT - ChatGPT For Laravel (1.05), Atom One Dark By Mayke (1.1.1), Doki Theme (88.5-1.11.0), Doki Theme Icons (88.5-1.0.13), Cody AI by Sourcegraph (3.0.9)]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/disT9g8E) by [Unito](https://www.unito.io)

**Comment by aldanchenko** [comment]
Hi @CB-FARAZ 

Thanks for reporting!
Please re-install the plugin from the marketplace, or install it manually from the zip not from an unzipped jar.

Best regards,
Alex
