### ISSUE TITLE
[Exception][PyCharm 2022.3.2] com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl....

### ISSUE THREAD

**Issue by oranshiner** [Codium-ai/codiumai-jetbrains-release#12]
# User Description
When I press generate test and delete the code under test I get this Exception

# Stack Trace
```
com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl.source.tree.CompositeElement of type Py:FUNCTION_DECLARATION (class com.jetbrains.python.psi.impl.stubs.PyFunctionElementType)
	at com.intellij.psi.PsiInvalidElementAccessException.createByNode(PsiInvalidElementAccessException.java:80)
	at com.intellij.psi.impl.source.SubstrateRef$2.getContainingFile(SubstrateRef.java:98)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:239)
	at ai.codium.python.CodiumPythonInlayProvider.getImportsContentFiles(CodiumPythonInlayProvider.kt:33)
	at ai.codium.CodiumInlayProviderBase.getImportsContent(CodiumInlayProviderBase.kt:103)
	at ai.codium.CodiumInlayProviderBase.addCodiumTestsGenerationInlay$lambda$0(CodiumInlayProviderBase.kt:87)
	at com.intellij.codeInsight.hints.presentation.PresentationFactory$referenceOnHover$hovered$1.invoke(PresentationFactory.kt:277)
	at com.intellij.codeInsight.hints.presentation.PresentationFactory$referenceOnHover$hovered$1.invoke(PresentationFactory.kt:273)
	at com.intellij.codeInsight.hints.presentation.PresentationFactory$onClick$2.invoke(PresentationFactory.kt:251)
	at com.intellij.codeInsight.hints.presentation.PresentationFactory$onClick$2.invoke(PresentationFactory.kt:249)
	at com.intellij.codeInsight.hints.presentation.OnClickPresentation._init_$lambda$0(OnClickPresentation.kt:17)
	at com.intellij.codeInsight.hints.presentation.OnClickPresentation.mouseClicked(OnClickPresentation.kt:21)
	at com.intellij.codeInsight.hints.presentation.StatefulPresentation.mouseClicked(StatefulPresentation.kt:96)
	at com.intellij.codeInsight.hints.presentation.StaticDelegatePresentation.mouseClicked(StaticDelegatePresentation.kt:51)
	at com.intellij.codeInsight.hints.presentation.RecursivelyUpdatingRootPresentation.mouseClicked(RecursivelyUpdatingRootPresentation.kt:69)
	at com.intellij.codeInsight.hints.LinearOrderInlayRenderer.mouseClicked(LinearOrderInlayRenderer.kt:113)
	at com.intellij.codeInsight.hints.presentation.listeners.InlayEditorMouseListener.mouseClicked$lambda$0(InlayEditorMouseListener.kt:26)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:167)
	at com.intellij.codeInsight.hints.presentation.listeners.InlayEditorMouseListener.mouseClicked(InlayEditorMouseListener.kt:25)
	at com.intellij.openapi.editor.impl.event.EditorEventMulticasterImpl$2.lambda$mouseClicked$1(EditorEventMulticasterImpl.java:73)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.java:35)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.java:46)
	at com.intellij.openapi.editor.impl.event.EditorEventMulticasterImpl$2.mouseClicked(EditorEventMulticasterImpl.java:73)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.runMouseClickedCommand(EditorImpl.java:3972)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mouseReleased(EditorImpl.java:3891)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:831)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThr

<TRIMMED STACKTRACE>
```

# Other Information
```
=== About ===
Build version: PyCharm 2022.3.2 Build: #PC-223.8617.48 January 24, 2023
Theme: Darcula
JRE: 17.0.5+1-b653.25, JetBrains s.r.o.
JVM: 17.0.5+1-b653.25, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.2.1 (aarch64)

=== Plugins ===
Custom plugins: [CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.4.7), GitHub Copilot (1.2.4.2459)]
Disabled plugins:[Requirements Pro (2022.4.1)]
```

**Comment by ArtsiomCh** [comment]
fixed in upcoming 0.4.10
