### ISSUE TITLE
[Exception][GoLand 2023.2.2] com.intellij.psi.stubs.UpToDateStubIndexMismatch: PSI and index do not match.Please rep...

### ISSUE THREAD

**Issue by beto-ouverney** [Codium-ai/codiumai-jetbrains-release#127]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
com.intellij.psi.stubs.UpToDateStubIndexMismatch: PSI and index do not match.
Please report the problem to JetBrains with the files attached
INDEXED VERSION IS THE CURRENT ONE file=GO_FILE, file.class=class com.goide.psi.GoFile, file.lang=Language: go, modStamp=2
 tree consistent
 stub debugInfo=created in getStubTree(), with AST = false; with backReference
 viewProvider=com.intellij.psi.SingleRootFileViewProvider{vFile=file:///Users/smartsaude/src/bitbucket.org/beneficiofacil/compra-automatica-worker/cmd/main.go, vFileId=37436, content=VirtualFileContent{size=1943}, eventSystemEnabled=true}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1696428301909; file length: 1943
 doc saved: true; doc stamp: 0; doc size: 1727; committed: true
indexing info: indexing timestamp = 1696428301909, binary = false, byte size = 1943, char size = 1727
ref: 50cf572587cf
latestIndexedStub=StubTree{myDebugInfo='created from index; with backReference', myRoot=GoFileStub}691997317
   same size=true
   debugInfo=created from index; with backReference
	at com.intellij.psi.stubs.StubTreeLoader.handleUpToDateMismatch(StubTreeLoader.java:210)
	at com.intellij.psi.stubs.StubTreeLoader.access$100(StubTreeLoader.java:28)
	at com.intellij.psi.stubs.StubTreeLoader$StubTreeAndIndexUnmatchCoarseException.doCreateCompleteException(StubTreeLoader.java:202)
	at com.intellij.psi.stubs.StubTreeLoader$StubTreeAndIndexUnmatchCoarseException.lambda$createCompleteException$0(StubTreeLoader.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:230)
	at com.intellij.psi.stubs.StubTreeLoader$StubTreeAndIndexUnmatchCoarseException.createCompleteException(StubTreeLoader.java:177)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:228)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:727)
	at com.intellij.psi.impl.source.PsiFileImpl.getNode(PsiFileImpl.java:926)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:737)
	at com.intellij.psi.SyntaxTraverser$PsiApi.first(SyntaxTraverser.java:296)
	at com.intellij.psi.SyntaxTraverser$PsiApi.first(SyntaxTraverser.java:264)
	at com.intellij.psi.SyntaxTraverser$ApiEx.children(SyntaxTraverser.java:241)
	at com.intellij.psi.SyntaxTraverser$Api.fun(SyntaxTra

<TRIMMED STACKTRACE>

	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:111)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:76)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:188)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:165)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:433)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:24)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.AssertionError: Stub count doesn't match stubbed node length
	at com.intellij.psi.impl.source.FileTrees.lambda$reconcilePsi$4(FileTrees.java:182)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:516)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:175)
	at com.intellij.psi.impl.source.FileTrees.withAst(FileTrees.java:141)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:214)
	... 66 more

```

# Other Information
```
=== About ===
Build version: GoLand 2023.2.2 Build: #GO-232.9921.53 September 14, 2023
Theme: Darcula
JRE: 17.0.8+7-b1000.22, JetBrains s.r.o.
JVM: 17.0.8+7-b1000.22, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 14.0 (aarch64)

=== Plugins ===
Custom plugins: [PostCSS (232.8660.149), Gradianto (5.4), Material Theme UI (8.12.2), Task Management (232.9559.28), Visual Studio Code Dark Plus Theme (2.8), Rainbow Brackets (2023.3.5), Gitmoji Plus: Commit Button (1.13.0), Gopher (2021.1), CSV Editor (3.2.1-232), Vue.js (232.9921.55), GitHub Copilot (1.3.0.3323), Conventional Commit (0.22.0), Nord (0.13.0), CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.6.09), AI Assistant (232.9826), One Dark theme (5.8.0), .env files support (2023.2), Prettier (232.9921.53)]
Disabled plugins:[Gerry Themes Pro (2023.1.70)]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/ArdLIIfL) by [Unito](https://www.unito.io)

**Comment by aldanchenko** [comment]
Hi @beto-ouverney 

Thanks for reporting. Could you help us to reproduce this issue? I'm not sure it's related to our plugin. Could you please clarify?

Thanks!
Alex

**Comment by ArtsiomCh** [comment]
Seems to be IDE internal issue with indexes:
> UpToDateStubIndexMismatch: PSI and index do not match. Please report the problem to JetBrains with the files attached

Please [report to JetBrains](https://youtrack.jetbrains.com/) if still experience it.
