### ISSUE TITLE
[Exception][IDEA 2023.2] *** exception class was changed or removed

### ISSUE THREAD

**Issue by NitishGameChanges** [Codium-ai/codiumai-jetbrains-release#137]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
   
Details: file:/private/var/folders/tw/6wc_b04d47xcxcxy6ktzd34r0000gn/T/AppTranslocation/8AFB3850-1290-4AF7-9C85-7347208C54F8/d/IntelliJ%20IDEA.app/Contents/plugins/sass/lib/sass.jar!/org/jetbrains/plugins/sass/stdlib/sass_functions.scss
   
   java.lang.Throwable: Cannot find sass stdlib file in 
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:406)
	at org.jetbrains.plugins.scss.index.SassScssIndexedRootProvider.initGlobalAndBuiltInModuleFiles(SassScssIndexedRootProvider.java:60)
	at org.jetbrains.plugins.scss.index.SassScssIndexedRootProvider.getAdditionalRootsToIndex(SassScssIndexedRootProvider.java:28)
	at com.intellij.util.indexing.IndexableSetContributor.getRootsToIndex(IndexableSetContributor.java:39)
	at com.intellij.util.indexing.AdditionalIndexableFileSet.collectFilesAndDirectories(AdditionalIndexableFileSet.java:45)
	at com.intellij.util.indexing.AdditionalIndexableFileSet.lambda$new$3(AdditionalIndexableFileSet.java:35)
	at com.intellij.util.CachedValueImpl.doCompute(CachedValueImpl.java:22)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:110)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:65)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.util.CachedValueImpl.getValue(CachedValueImpl.java:32)
	at com.intellij.util.indexing.AdditionalIndexableFileSet.isInSet(AdditionalIndexableFileSet.java:70)
	at com.intellij.util.indexing.roots.IndexableFilesIndexImpl.shouldBeIndexed(IndexableFilesIndexImpl.java:63)
	at com.intellij.util.indexing.FileBasedIndexImpl$5.isInSet(FileBasedIndexImpl.java:289)
	at com.intellij.util.indexing.FileBasedIndexImpl.getContainingProjects(FileBasedIndexImpl.java:1781)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$ensureFileBelongsToIndexableFilter$31(FileBasedIndexImpl.java:1924)
	at com.intellij.util.indexing.projectFilter.IncrementalProjectIndexableFilesFilterHolder$addFileId$matchedProjects$2.invoke(ProjectIndexableFilesFilterHolder.kt:80)
	at com.intellij.util.indexing.projectFilter.IncrementalProjectIndexableFilesFilterHolder$addFileId$matchedProjects$2.invoke(ProjectIndexableFilesFilterHolder.kt:80)
	at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
	at com.intellij.util.indexing.projectFilter.IncrementalProjectIndexableFilesFilterHolder.addFileId$lambda$1(ProjectIndexableFilesFilterHolder.kt:80)
	at com.intellij.util.indexing.projectFilter.IncrementalProjectIndexableFilesFilterHolder.access$addFileId$lambda$1(ProjectIndexableFilesFilterHolder.kt:45)
	at com.intellij.util.i

<TRIMMED STACKTRACE>

top/java.awt.Window.dispatchEventImpl(Window.java:2808)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:791)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:762)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:633)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:588)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2023.2 Build: #IU-232.8660.185 July 26, 2023
Theme: Dark
JRE: 17.0.7+7-b1000.6, JetBrains s.r.o.
JVM: 17.0.7+7-b1000.6, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.4 (aarch64)

=== Plugins ===
Custom plugins: [Kafka (232.8660.206), Big Data Tools Core (232.8660.206), CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.6.07), .env files support (2023.2)]
Disabled plugins:[Machinet AI GPT4 & ChatGPT (2022.1.50)]
```

**Comment by aldanchenko** [comment]
Hi @NitishGameChanges,

Thanks for reporting! Could you please update to the latest version?

Best regards,
Alex

**Comment by ArtsiomCh** [comment]
Error seems to be from third party plugin **sass**
