### ISSUE TITLE
[0.6.17][INTELLIJ IDEA IU 2023.1.2] java.lang.RuntimeException: Cannot invoke (class=, method=repositoryChanged, topi...

### ISSUE THREAD

**Issue by jim-trux** [Codium-ai/codiumai-jetbrains-release#138]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.RuntimeException: Cannot invoke (class=, method=repositoryChanged, topic=GitRepository change)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:657)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:415)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:394)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:454)
	at jdk.proxy17/jdk.proxy17.$Proxy174.repositoryChanged(Unknown Source)
	at git4idea.repo.GitRepositoryUpdater.filesChanged(GitRepositoryUpdater.java:138)
	at com.intellij.vfs.AsyncVfsEventsPostProcessorImpl.processEvents$lambda$2(AsyncVfsEventsPostProcessorImpl.kt:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:361)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:339)
	at com.intellij.vfs.AsyncVfsEventsPostProcessorImpl.processEvents(AsyncVfsEventsP

<TRIMMED STACKTRACE>

utineScheduler.kt:664)
Caused by: java.lang.RuntimeException: Cannot invoke (class=CodiumPrePRPanel$$Lambda$10441/0x0000000303d3ea00, method=repositoryChanged, topic=GitRepository change)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:657)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:415)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:384)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:454)
	at jdk.proxy1/jdk.proxy1.$Proxy175.dirtyUnder(Unknown Source)
	at git4idea.annotate.GitAnnotationsListener$1.repositoryChanged(GitAnnotationsListener.java:24)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:680)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:640)
	... 42 more
Caused by: java.lang.IndexOutOfBoundsException: bitIndex < 0: -1
	at java.base/java.util.BitSet.get(BitSet.java:626)
	at java.desktop/javax.swing.DefaultListSelectionModel.insertIndexInterval(DefaultListSelectionModel.java:652)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.intervalAdded(BasicListUI.java:2773)
	at java.desktop/javax.swing.AbstractListModel.fireIntervalAdded(AbstractListModel.java:157)
	at java.desktop/javax.swing.DefaultComboBoxModel.addElement(DefaultComboBoxModel.java:130)
	at java.desktop/javax.swing.JComboBox.addItem(JComboBox.java:746)
	at ai.codium.ui.prePR.CodiumPrePRPanel.setBranches(CodiumPrePRPanel.kt:80)
	at ai.codium.ui.prePR.CodiumPrePRPanel.setRepositoryListener$lambda$3(CodiumPrePRPanel.kt:114)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:680)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:640)
	... 50 more

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2023.1.2 Build: #IU-231.9011.34 May 16, 2023
Theme: IntelliJ Light
JRE: 17.0.6+10-b829.9, JetBrains s.r.o.
JVM: 17.0.6+10-b829.9, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.6.1 (aarch64)

=== Plugins ===
Custom plugins: [Error Prone Compiler (231.8109.90), Pom Format (0.0.6), Native Debugging Support (231.8770.15), CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.6.17), AWS Toolkit (1.84-231), POJO to JSON (2.0.3), Resource Bundle Editor (231.8109.91), Kotlin (231-1.9.10-release-459-IJ8770.65), Statistic (4.2.7), BoB the Builder of Beans (1.8), JPA Buddy (2023.3.5-231), OpenAPI (Swagger) Editor (1.69), EasyCode (1.2.8-RELEASE), Case conversion (0.7.1), RoboPOJOGenerator (2.4.1), MapStruct Support (1.6.1), Machinet AI GPT-4 Chat and Unit Tests (2022.1.53), GitHub Actions Manager (1.13.5), Code Generator (1.5.2), Translation (3.5.5), Jira Integration (4.5.0), Database Navigator (3.4.1710.0), JSON to Schema (1.1), GraalVM Native Debugger (231.8770.17), codeCreator (2022.2.8)]
Disabled plugins:[Jakarta EE: Bean Validation (231.9011.34), Jakarta EE: Messaging (JMS) (231.9011.34), WildFly (231.9011.34), Jakarta EE: Server Pages (JSP) (231.9011.34), IntelliJDeodorant (2020.3-1.0), Spring Data (231.9011.34), AOP Pointcut Language (231.9011.34), Ktor (231.9011.34), Perforce Helix Core (231.9011.34), Jakarta EE: RESTful Web Services (JAX-RS) (231.9011.34), CodeGen (2.0.231), Spring Security (231.9011.34), Mercurial (231.9011.34), UI Designer (231.9011.34), Spring (231.9011.34), Android (2022.1.1.231.9011.34), GlassFish (231.9011.34), Jakarta EE: Persistence (JPA) (231.9011.34), Code Complexity (1.0.1), Jakarta EE: Gradle Integration (231.9011.34), GenerateCopyConstructor (1.2), Spring Integration Patterns (231.9011.34), Spring Web (231.9011.34), Jakarta EE: Expression Language (EL) (231.9011.34), Tomcat and TomEE (231.9011.34), Integration Testing of Workspace Model (231.9011.34), Thymeleaf (231.9011.34), Hibernate (231.9011.34), Jakarta EE: Web/Servlets (231.9011.34), Spring Boot (231.9011.34), Spring Messaging (231.9011.34), Current date generator (1.1), Selenium UI Testing (231.8109.91), Subversion (231.9011.34), Plugin DevKit (231.9011.34), Spring Cloud (231.9011.34), Android Design Tools (231.9011.34), Jakarta EE: Contexts and Dependency Injection (CDI) (231.9011.34), Quarkus (231.9011.34), Jakarta EE Platform (231.9011.34), Jakarta EE: Application Servers (231.9011.34), TestNG (231.9011.34), Eclipse Interoperability (231.9011.34), Ant (231.9011.34)]
```

**Comment by aldanchenko** [comment]
Hello @jim-trux 

Thanks for reporting!
