### ISSUE TITLE
[0.6.17][PYCHARM PC 2023.2.3] java.lang.Throwable: Invalid folding descriptor detected ((65,2632) for AST: Element(Py...

### ISSUE THREAD

**Issue by PyGamiQ** [Codium-ai/codiumai-jetbrains-release#139]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable: Invalid folding descriptor detected ((65,2632) for AST: Element(Py:STATEMENT_LIST)). It ends beyond the document range (1651)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.intellij.codeInsight.folding.impl.UpdateFoldRegionsOperation.addNewRegions(UpdateFoldRegionsOperation.java:126)
	at com.intellij.codeInsight.folding.impl.UpdateFoldRegionsOperation.run(UpdateFoldRegionsOperation.java:87)
	at com.intellij.openapi.editor.impl.FoldingModelImpl.runBatchFoldingOperation(FoldingModelImpl.java:292)
	at com.intellij.openapi.editor.impl.FoldingModelImpl.runBatchFoldingOperation(FoldingModelImpl.java:233)
	at com.intellij.openapi.editor.FoldingModel.runBatchFoldingOperationDoNotCollapseCaret(FoldingModel.java:107)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.lambda$buildInitialFoldings$1(CodeFoldingManagerImpl.java:148)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.loadEditorInBackground$lambda$6(PsiAwareTextEditorImpl.kt:99)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.loaded(AsyncEditorLoader.kt:154)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.access$loaded(AsyncEditorLoader.kt:43)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader$start$1$1.invokeSuspend(AsyncEditorLoader.kt:124)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:193)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Event

<TRIMMED STACKTRACE>

4)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:690)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:638)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:592)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:997)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:997)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

# Other Information
```
=== About ===
Build version: PyCharm 2023.2.3 Build: #PC-232.10072.31 October 12, 2023
Theme: Xcode-Dark
JRE: 17.0.8.1+7-b1000.32, JetBrains s.r.o.
JVM: 17.0.8.1+7-b1000.32, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 14.2 (aarch64)

=== Plugins ===
Custom plugins: [.ignore (4.5.2), JavaFX Runtime for Plugins (1.0.4), Battery Status (2.0), CSV Editor (3.2.2-232), MicroPython (1.4.2-2023.2), codetime (0.0.9), Ideolog (222.1.0.0), PlantUML Integration (7.3.0-IJ2023.2), AppMap (0.52.0), Monocai Color Theme (2.0.2c), Coding counter (0.6), Rainbow CSV (2.0.2), Codeium: AI Autocomplete and Chat for Python, JS, TS, Java, Go… (1.4.2), Sequoia Theme (1.0.1), DataGraph - JSON, YAML, XML Visualization (1.0.4-232), Statistics (1.0), Python Security (1.29.0), Xcode-Dark Theme (1.2.4), Database Navigator (3.4.1710.0), Quick File Preview (1.6.4), Python Enhancements (0.4.2), SonarLint (10.0.0.76954), PlantUML Parser (0.0.6), Statistic (4.2.7), File Path Autocomplete (0.4.1), SQLFormatter (1.5.7-SNAPSHOT), Pytest Parametrize Inlay Hint (0.0.4), MediaFilePreviewer (1.1.3), Python Annotations (2022.2), CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.6.17), Better Highlights (2023.8.4), Key Promoter X (2023.2.0), Automatic GitHub Issue Navigation Configuration (1.1.3), Python External Documentation (0.1.2), Github Tools (2.1.1), Github Workflow (3.1.0), CodeGlance Pro (1.7.6), Makefile Language (232.8660.88), Test Management (232.8660.88), Typeformation (0.3), Rainbow Brackets (2023.3.7), python-typing-adder (1.1), pytest imp (1.1.2), CodeStats (1.5.1), PyCharm Help (232.10072.31), ChatGPT GPT-4 - Bito AI Code Assistant (1.1.10), Hunspell (232.10072.32), GitHub Actions Manager (1.14.0)]
Disabled plugins:[aiXcoder Code Completer (4.1.31-2020), Docgen (0.1.2), JumPy (0.0.7), autoTest (0.0.4.8), Design Preview for Figma (0.0.9), AWS Toolkit (1.85-232), Open Commit On GitHub (1.0.2), GitToolBox (500.0.22+222), Tasks (1.8.4), Better Comments (1.0), Prettify Python (2022.1), Statistics View (1.0.1)]
```

**Comment by ArtsiomCh** [comment]
IDE internal issue (JetBrains Python plugin related)
