### ISSUE TITLE
[0.6.17][INTELLIJ IDEA IU 2023.2.4] *** exception class was changed or removed

### ISSUE THREAD

**Issue by arefinic** [Codium-ai/codiumai-jetbrains-release#142]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
  An invalid state was detected that occurs if the key's equals or hashCode was modified while it resided in the cache. This violation of the Map  contract can lead to non-deterministic behavior (key: com.intellij.psi.impl.ElementBase$ElementIconRequest@8f6, key type: ElementIconRequest, node type: PSMS, cache type: SSMS).
  
  java.lang.IllegalStateException
at com.github.benmanes.caffeine.cache.BoundedLocalCache.logIfAlive(BoundedLocalCache.java:302)
at com.github.benmanes.caffeine.cache.BoundedLocalCache.evictEntry(BoundedLocalCache.java:1102)
at com.github.benmanes.caffeine.cache.BoundedLocalCache.evictFromMain(BoundedLocalCache.java:861)
at com.github.benmanes.caffeine.cache.BoundedLocalCache.evictEntries(BoundedLocalCache.java:708)
at com.github.benmanes.caffeine.cache.BoundedLocalCache.maintenance(BoundedLocalCache.java:1720)
at com.github.benmanes.caffeine.cache.BoundedLocalCache.performCleanUp(BoundedLocalCache.java:1658)
at com.github.benmanes.caffeine.cache.BoundedLocalCache$PerformCleanupTask.run(BoundedLocalCache.java:3880)
at com.intellij.util.concurrency.SameThreadExecutor.execute(SameThreadExecutor.java:15)
at com.github.benmanes.caffeine.cache.BoundedLocalCache.scheduleDrainBuffers(BoundedLocalCache.java:1631)
at com.github.benmanes.caffeine.cache.BoundedLocalCache.scheduleAfterWrite(BoundedLocalCache.java:1597)
at com.github.benmanes.caffeine.cache.BoundedLocalCache.afterWrite(BoundedLocalCache.java:1529)
at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2756)
at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2666)
at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
at com.intellij.ui.IconDeferrerImpl.defer(IconDeferrerImpl.kt:75)
at com.intellij.ui.icons.CoreIconManager.createDeferredIcon(CoreIconManager.kt:117)
at com.intellij.psi.impl.ElementBase.computeIcon(ElementBase.java:85)
at com.intellij.psi.impl.ElementBase.getIcon(ElementBase.java:62)
at ai.codium.elements.CutElement.getIcon(CutElement.kt:56)
at ai.codium.ui.structureview.CodiumStructureViewChildElement$getPresentation$1.getIcon(CodiumStructureViewElements.kt:38)
at com.intellij.ide.projectView.PresentationData.updateFrom(PresentationData.java:163)
at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.update(TreeElementWrapper.java:27)
at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:88)
at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:32)
at com.intellij.ui.tree.StructureTreeModel$Node.update(StructureTreeModel.java:486)
at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:467)
at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:460)
at com.intelli

<TRIMMED STACKTRACE>

til.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:133)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:114)
at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:111)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:76)
at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:188)
at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:165)
at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:433)
at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:24)
at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
at java.base/java.lang.Thread.run(Thread.java:833)

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2023.2.4 Build: #IU-232.10203.10 October 25, 2023
Theme: Dark
JRE: 17.0.8.1+7-b1000.32, JetBrains s.r.o.
JVM: 17.0.8.1+7-b1000.32, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.4 (aarch64)

=== Plugins ===
Custom plugins: [CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.6.17), DGS (1.3.3), Copy Git Link (0.5.2), Kubernetes (232.10203.2), JPA Buddy (2023.3.5-232), GraphQL (4.0.2)]
Disabled plugins:[Key Promoter X (2023.2.0)]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Seems to be third party plugin `com.github.benmanes.caffeine` problem.
Please report to them if happened again/often.
