### ISSUE TITLE
[0.6.18][INTELLIJ IDEA IU 2023.2.4] java.lang.NullPointerException: Cannot invoke "javax.swing.text.View.getParent()"...

### ISSUE THREAD

**Issue by inanalper** [Codium-ai/codiumai-jetbrains-release#143]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.NullPointerException: Cannot invoke "javax.swing.text.View.getParent()" because "child" is null
	at java.desktop/javax.swing.text.CompositeView.replace(CompositeView.java:189)
	at java.desktop/javax.swing.text.BoxView.replace(BoxView.java:182)
	at java.desktop/javax.swing.text.FlowView$FlowStrategy.layoutRow(FlowView.java:597)
	at java.desktop/javax.swing.text.FlowView$FlowStrategy.layout(FlowView.java:503)
	at java.desktop/javax.swing.text.FlowView.layout(FlowView.java:209)
	at java.desktop/javax.swing.text.BoxView.setSize(BoxView.java:398)
	at java.desktop/javax.swing.text.BoxView.updateChildSizes(BoxView.java:367)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:335)
	at java.desktop/javax.swing.text.BoxView.layout(BoxView.java:710)
	at java.desktop/javax.swing.text.BoxView.setSize(BoxView.java:398)
	at java.desktop/javax.swing.text.BoxView.updateChildSizes(BoxView.java:367)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:335)
	at java.desktop/javax.swing.text.BoxView.layout(BoxView.java:710)
	at java.desktop/javax.swing.text.BoxView.setSize(BoxView.java:398)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1826)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$RootView.paint(BasicTextUI.java:1537)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.paintSafely(BasicTextUI.java:757)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.paint(BasicTextUI.java:915)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.update(BasicTextUI.java:894)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:845)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1115)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5312)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:247)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1347)
	at java.desktop/javax.swing.JComponent.paintForceDoubleBuffered(JComponent.java:1151)
	at java.desktop/javax.swing.JViewport.paintView(JViewport.java:1752)
	at java.desktop/javax.swing.JViewport.windowBlitPaint(JViewport.java:1675)
	at java.desktop/javax.swing.JViewport.setViewPosition(JViewport.java:1219)
	at java.desktop/javax.swing.plaf.basic.BasicScrollPaneUI$Handler.vsbStateChanged(BasicScrollPaneUI.java:1189)
	at java.desktop/javax.swing.plaf.basic.BasicScrollPaneUI$Handler.stateChanged(BasicScrollPaneUI.java:1178)
	at java.desktop/javax.swing.DefaultBoundedRangeModel.fireStateChanged(DefaultBoundedRangeModel.java:371)
	at java.desktop/javax.swing.DefaultBoundedRangeModel.setRangeProperties(DefaultBoundedRangeModel.java:309)
	at java.desktop/javax.swing.DefaultBoundedRangeModel.setValue(DefaultBoundedRangeModel.java:175)
	at java.desktop/javax.swing.JScrollBar.setValue(JScrollBar.java:486)
	at ai.codium.ui.prePR.CodiumPrePRPanel.updateMessageUI$lambda$11$lambda$10(CodiumPrePRPanel.kt:363)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:254)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:373)
	at com.intellij.util.Alarm$Request.run(Alarm.java:360)
	at com.intellij.util.concurrency.Propagation.contextAwareCallable$lambda$2(propagation.kt:328)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2023.2.4 Build: #IU-232.10203.10 October 24, 2023
Theme: Dark
JRE: 17.0.8.1+7-b1000.32, JetBrains s.r.o.
JVM: 17.0.8.1+7-b1000.32, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 14.0 (aarch64)

=== Plugins ===
Custom plugins: [Snyk Security - Code, Open Source, Container, IaC Configurations (2.5.6), CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.6.18), Big Data Tools Core (232.10203.10), Big Data File Viewer (232.10072.27), Remote File Systems (232.10203.10), Maven Helper (4.26.0-IJ2022.2)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Fixed at 0.6.19.
Let us know if happened again, please.
