### ISSUE TITLE
[0.6.17][INTELLIJ IDEA IU 2023.2.2] *** exception class was changed or removed

### ISSUE THREAD

**Issue by martin00000** [Codium-ai/codiumai-jetbrains-release#144]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
   provider: de.plushnikov.intellij.plugin.provider.LombokAugmentProvider@3beecf6e
   
   java.lang.RuntimeException: java.io.IOException: Record[4159383] is deleted
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:138)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecordsImpl.lambda$static$0(FSRecordsImpl.java:96)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecordsImpl.handleError(FSRecordsImpl.java:1172)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecordsImpl.list(FSRecordsImpl.java:501)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.list(FSRecords.java:237)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.listAll(PersistentFSImpl.java:320)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.loadAllChildren(VirtualDirectoryImpl.java:408)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.getChildren(VirtualDirectoryImpl.java:401)
	at com.intellij.openapi.roots.impl.PackageDirectoryCacheImpl$PackageInfo.lambda$new$0(PackageDirectoryCacheImpl.java:121)
	at com.intellij.openapi.util.NotNullLazyValue$4.compute(NotNullLazyValue.java:120)
	at com.intellij.openapi.util.NotNullLazyValue$4.getValue(NotNullLazyValue.java:105)
	at com.intellij.openapi.roots.impl.PackageDirectoryCacheImpl$PackageInfo.getSubPackageDirectories(PackageDirectoryCacheImpl.java:135)
	at com.intellij.openapi.roots.impl.PackageDirectoryCacheImpl.getPackageInfo(PackageDirectoryCacheImpl.java:72)
	at com.intellij.openapi.roots.impl.PackageDirectoryCacheImpl.getPackageInfo(PackageDirectoryCacheImpl.java:70)
	at com.intellij.openapi.roots.impl.PackageDirectoryCacheImpl.getDirectoriesByPackageName(PackageDirectoryCacheImpl.java:54)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getDirectoriesByPackageName(WorkspaceFileIndexDataImpl.kt:309)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getDirectoriesByPackageName(WorkspaceFileIndexImpl.kt:252)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getDirectoriesByPackageName(DirectoryIndexImpl.java:104)
	at com.intellij.openapi.roots.impl.ProjectPackageIndexImpl.getDirsByPackageName(ProjectPackageIndexImpl.java:35)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findPackage(JavaFileManagerImpl.java:62)
	at com.intellij.psi.impl.PsiElementFinderImpl.findPackage(PsiElementFinderImpl.java:58)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findPackage(JavaPsiFacadeImpl.java:202)
	at de.plushnikov.intellij.plugin.util.LombokLibraryUtil.lambda$hasLombokLibrary$0(LombokLibraryUtil.java:34)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lamb

<TRIMMED STACKTRACE>

nsight.daemon.impl.TextEditorBackgroundHighlighter.getPasses(TextEditorBackgroundHighlighter.java:80)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$submitInBackground$24(DaemonCodeAnalyzerImpl.java:1131)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:923)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:76)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$submitInBackground$25(DaemonCodeAnalyzerImpl.java:1120)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.submitInBackground(DaemonCodeAnalyzerImpl.java:1117)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$queuePassesCreation$20(DaemonCodeAnalyzerImpl.java:1082)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:190)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.io.IOException: Record[4159383] is deleted
	at com.intellij.openapi.vfs.newvfs.persistent.dev.blobstorage.LargeSizeStreamlinedBlobStorage.readRecord(LargeSizeStreamlinedBlobStorage.java:394)
	at com.intellij.openapi.vfs.newvfs.persistent.dev.blobstorage.LargeSizeStreamlinedBlobStorage.readRecord(LargeSizeStreamlinedBlobStorage.java:287)
	at com.intellij.openapi.vfs.newvfs.persistent.AttributesStorageOverBlobStorage.readAttributeValue(AttributesStorageOverBlobStorage.java:914)
	at com.intellij.openapi.vfs.newvfs.persistent.AttributesStorageOverBlobStorage.readAttribute(AttributesStorageOverBlobStorage.java:91)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSAttributeAccessor.readAttribute(PersistentFSAttributeAccessor.java:38)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSTreeAccessor.doLoadChildren(PersistentFSTreeAccessor.java:105)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecordsImpl.list(FSRecordsImpl.java:498)
	... 82 more

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2023.2.2 Build: #IU-232.9921.47 September 13, 2023
Theme: One Dark
JRE: 17.0.8+7-b1000.22, JetBrains s.r.o.
JVM: 17.0.8+7-b1000.22, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 11.7.8 (x86_64)

=== Plugins ===
Custom plugins: [GitHub Copilot (1.3.3.3572), Go (232.9921.28), Easy Javadoc (3.6.0), Free MyBatis Tool (2.2.1), One Dark theme (5.9.0), ChatGPT GPT-4 - Bito AI Code Assistant (1.1.8), CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.6.17), Codeium: AI Autocomplete and Chat for Python, JS, TS, Java, Go… (1.4.2), Translation (3.5.5), Package Search (232.9921.28), Git Commit Template (1.2.0)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Third party plugin issue: Lombok plugin (de.plushnikov.intellij.plugin).
PS Please update to the latest 0.6.19
