### ISSUE TITLE
[0.6.19][PYCHARM PC 2023.2.4] java.lang.RuntimeException: Cannot invoke (class=, method=repositoryChanged, topic=GitR...

### ISSUE THREAD

**Issue by lironesamoun** [Codium-ai/codiumai-jetbrains-release#145]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.RuntimeException: Cannot invoke (class=, method=repositoryChanged, topic=GitRepository change)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:676)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:422)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:401)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:460)
	at jdk.proxy15/jdk.proxy15.$Proxy192.repositoryChanged(Unknown Source)
	at git4idea.repo.GitRepositoryManager.lambda$notifyListenersAsync$2(GitRepositoryManager.java:84)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:24)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Cannot invoke (class=CodiumPrePRPanel$$Lambda$11542/0x000000e803dcc000, method=repositoryChanged, topic=GitRepository change)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:676)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:422)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:391)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:460)
	at jdk.proxy2/jdk.proxy2.$Proxy193.dirtyUnder(Unknown Source)
	at git4idea.annotate.GitAnnotationsListener$1.repositoryChanged(GitAnnotationsListener.java:24)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:699)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:659)
	... 19 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at com.intellij.ui.components.WideSelectionListUI.updateLayoutState(WideSelectionListUI.java:207)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1394)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2815)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:224)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:204)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:251)
	at java.desktop/javax.swing.DefaultListSelectionModel.insertIndexInterval(DefaultListSelectionModel.java:675)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.intervalAdded(BasicListUI.java:2773)
	at java.desktop/javax.swing.AbstractListModel.fireIntervalAdded(AbstractListModel.java:157)
	at java.desktop/javax.swing.DefaultComboBoxModel.addElement(DefaultComboBoxModel.java:130)
	at java.desktop/javax.swing.JComboBox.addItem(JComboBox.java:746)
	at ai.codium.ui.prePR.CodiumPrePRPanel.setBranches(CodiumPrePRPanel.kt:80)
	at ai.codium.ui.prePR.CodiumPrePRPanel.setRepositoryListener$lambda$3(CodiumPrePRPanel.kt:114)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:699)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:659)
	... 27 more

```

# Other Information
```
=== About ===
Build version: PyCharm 2023.2.4 Build: #PC-232.10203.26 November 1, 2023
Theme: Legacy Gerry Dark
JRE: 17.0.8.1+7-b1000.32, JetBrains s.r.o.
JVM: 17.0.8.1+7-b1000.32, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.4 (aarch64)

=== Plugins ===
Custom plugins: [SonarLint (10.0.1.77000), Docker (232.10203.2), Color Highlighter (17.1.0), One Dark theme (5.9.0), Key Promoter X (2023.3.0), Database Navigator (3.4.2251.0), Tabnine: AI Code Completion & Chat in Java JS/TS Python & More (1.26.0), Python: Styled DataFrame Viewer (0.12.0), ChatGPT GPT-4 - Bito AI Code Assistant (1.2.4), Conventional Commit (0.22.0), Atom Material Icons (93.1.0), CSV Editor (3.2.3-232), Ideolog (222.1.0.0), Ini (232.10203.2), Gerry Themes (2023.1.80), Unit File Support (systemd) (223.230322.126), Monokai Pro Theme (1.10), Pydantic (0.4.9), CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.6.19), .ignore (4.5.2), Makefile Language (232.8660.88), AWS Toolkit (1.87-232), .env files support (2023.2), Requirements (2022.4.1)]
Disabled plugins:[Hiberbee Theme (2023.11.10.2029), Terraform and HCL (232.8660.88), AutoDev (1.4.2-221), Git Commit Template (1.2.0), GitToolBox (500.0.22+222), Code With Me (232.10203.26)]
```

**Comment by aldanchenko** [comment]
Hi @lironesamoun 

Thanks for reporting! Maybe you could share any additional steps to reproduce this issue?

Thanks!
