### ISSUE TITLE
[0.6.19][INTELLIJ IDEA IC 2023.2.5] java.lang.Throwable: find: An invalid record was encountered. (-67701)

### ISSUE THREAD

**Issue by igor-budi** [Codium-ai/codiumai-jetbrains-release#147]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable: find: An invalid record was encountered. (-67701)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.intellij.credentialStore.KeyChainCredentialStore$Companion.checkForError(macOsKeychainLibrary.kt:88)
	at com.intellij.credentialStore.KeyChainCredentialStore$Companion.findGenericPassword(macOsKeychainLibrary.kt:37)
	at com.intellij.credentialStore.KeyChainCredentialStore$Companion.access$findGenericPassword(macOsKeychainLibrary.kt:29)
	at com.intellij.credentialStore.KeyChainCredentialStore.get(macOsKeychainLibrary.kt:96)
	at com.intellij.credentialStore.NativeCredentialStoreWrapper.get(NativeCredentialStoreWrapper.kt:46)
	at com.intellij.ide.passwordSafe.impl.BasePasswordSafe.get(PasswordSafeImpl.kt:92)
	at com.intellij.credentialStore.CredentialStore.getPassword(CredentialStore.java:30)
	at ai.codium.CodiumCredentialStorageKt.getCodiumRefreshToken(CodiumCredentialStorage.kt:16)
	at ai.codium.net.CodiumLoginManager.getRefreshToken(CodiumLoginManager.kt:21)
	at ai.codium.net.CodiumApiClientImpl.getIdToken(CodiumApiClient.kt:537)
	at ai.codium.net.CodiumApiClientImpl.generateTests(CodiumApiClient.kt:155)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at ai.codium.net.SecretsObfuscationInvocationHandler.invoke(CodiumNetworkService.kt:351)
	at jdk.proxy8/jdk.proxy8.$Proxy186.generateTests(Unknown Source)
	at ai.codium.net.CodiumNetworkService.generateTests(CodiumNetworkService.kt:39)
	at ai.codium.AnalysisManagerKt$runAnalysis$2$1.run(AnalysisManager.kt:118)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:478)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2023.2.5 Build: #IC-232.10227.8 November 9, 2023
Theme: Dark
JRE: 17.0.9+7-b1000.46, JetBrains s.r.o.
JVM: 17.0.9+7-b1000.46, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 14.1.1 (aarch64)

=== Plugins ===
Custom plugins: [GitHub Copilot (1.4.1.3828), Swift Support (0.19.0.167-232), Package Search (232.9921.28), CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.6.19), Kotlin (232-1.9.20-release-507-IJ10072.27)]
Disabled plugins:[Mercurial (232.10227.8), Android Design Tools (232.10227.8), Machine Learning Code Completion (232.10227.8), WebP Support (232.10227.8), Space (232.10227.8), JavaFX (232.10227.8), YAML (232.10227.8), Task Management (232.10227.8), Groovy (232.10227.8), Ant (232.10227.8), Grazie Lite (232.10227.8), TestNG (232.10227.8), Maven (232.10227.8), Shell Script (232.10227.8), Code With Me (232.10227.8), Copyright (232.10227.8), Gradle-Maven (232.10227.8), UI Designer (232.10227.8), TextMate Bundles (232.10227.8), Plugin DevKit (232.10227.8), Subversion (232.10227.8), Qodana (232.10227.8), Android (2022.3.1 Final.232.10227.8), Java Internationalization (232.10227.8), Eclipse Interoperability (232.10227.8), Java Stream Debugger (232.10227.8), JetBrains Marketplace Licensing (232.10227.8), Properties (232.10227.8), Perforce Helix Core (232.10227.8), Markdown (232.10227.8), EditorConfig (232.10227.8)]
```

**Comment by ArtsiomCh** [comment]
Here we're unable to read our saved Token from `CredentialStore`
Either internal OS glitch or user intentionally restrict access of IDE to that storage
