### ISSUE TITLE
[Exception][PyCharm 2022.3.3] java.lang.NullPointerException: Cannot invoke "javax.swing.text.View.getViewCount()" be...

### ISSUE THREAD

**Issue by access525** [Codium-ai/codiumai-jetbrains-release#15]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.NullPointerException: Cannot invoke "javax.swing.text.View.getViewCount()" because "view" is null
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$UpdateHandler.forwardPreferenceChangeToView(BasicTextUI.java:1934)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$UpdateHandler.forwardPreferenceChangeToView(BasicTextUI.java:1940)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$UpdateHandler.forwardPreferenceChangeToView(BasicTextUI.java:1940)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$UpdateHandler.forwardPreferenceChangeToView(BasicTextUI.java:1940)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$UpdateHandler.propertyChange(BasicTextUI.java:1928)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8750)
	at java.desktop/java.awt.Component.updateSelfGraphicsData(Component.java:1216)
	at java.desktop/java.awt.Component.updateGraphicsData(Component.java:1189)
	at java.desktop/java.awt.Container.updateChildGraphicsData(Container.java:1187)
	at java.desktop/java.awt.Component.updateGraphicsData(Component.java:1191)
	at java.desktop/java.awt.Container.updateChildGraphicsData(Container.java:1187)
	at java.desktop/java.awt.Component.updateGraphicsData(Component.java:1191)
	at java.desktop/java.awt.Container.updateChildGraphicsData(Container.java:1187)
	at java.desktop/java.awt.Component.updateGraphicsData(Component.java:1191)
	at java.desktop/java.awt.Container.updateChildGraphicsData(Container.java:1187)
	at java.desktop/java.awt.Component.updateGraphicsData(Component.java:1191)
	at java.desktop/java.awt.Container.updateChildGraphicsData(Container.java:1187)
	at java.desktop/java.awt.Component.updateGraphicsData(Component.java:1191)
	at java.desktop/java.awt.Container.updateChildGraphicsData(Container.java:1187)
	at java.desktop/java.awt.Component.updateGraphicsData(Component.java:1191)
	at java.desktop/java.awt.Component.setGraphicsConfiguration(Component.java:1179)
	at java.desktop/java.awt.Container.remove(Container.java:1249)
	at java.desktop/java.awt.Container.remove(Container.java:1293)
	at com.intellij.openapi.ui.ThreeComponentsSplitter.setLastComponent(ThreeComponentsSplitter.java:492)
	at com.intellij.toolWindow.ToolWindowPane.setComponent(ToolWindowPane.kt:242)
	at com.intellij.toolWindow.ToolWindowPane.addDecorator(ToolWindowPane.kt:173)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:995)
	at com.intellij.openapi.wm.impl.

<TRIMMED STACKTRACE>

iner.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:831)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

# Other Information
```
=== About ===
Build version: PyCharm 2022.3.3 Build: #PC-223.8836.43 March 10, 2023
Theme: Darcula
JRE: 17.0.6+1-b653.34, JetBrains s.r.o.
JVM: 17.0.6+1-b653.34, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11 10.0 (amd64)

=== Plugins ===
Custom plugins: [Codeium (1.1.69), Live Coding in Python (4.9.1), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.4.9), ChatGPT (2.1.10-222.231), JetBrains Academy (2023.3-2022.3-633), CodeAssist (1.3.2), CodeGeeX (1.0.7), ChatGPT Tool (1.1.1)]
Disabled plugins:[Subversion (223.8836.43), Monokai Color Scheme (223.8836.43), Github Color Scheme (223.8836.43), WarmNeon Color Scheme (223.8836.43), Mercurial (223.8836.43), Twilight Color Scheme (223.8836.43), GitHub (223.8836.43), Shell Script (223.8836.43), Properties (223.8836.43), YAML (223.8836.43), Git (223.8836.43)]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/cwwbL9JP) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Hi @access525 ! Thanks for reporting!
Do you see that exception more the once? Is there way to reproduce it?
PS I don't see any of our classes in stack-trace, probably it's trimmed due to GitHub limitations :(  So if you get it again please look into first (from the top) line with class from **ai.codium** package...

**Comment by access525** [comment]
No, it hasn't since. Thank you.
