### ISSUE TITLE
[0.6.19][PHPSTORM 2023.3 Beta] com.intellij.diagnostic.PluginException: 1397 ms to call on EDT CreateCommitMessageAct...

### ISSUE THREAD

**Issue by pandiya-nithra** [Codium-ai/codiumai-jetbrains-release#151]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
com.intellij.diagnostic.PluginException: 1397 ms to call on EDT CreateCommitMessageAction#Update@ChangesView.CommitToolbar (ai.codium.ui.actions.CreateCommitMessageAction). Revise AnAction.getActionUpdateThread property [Plugin: codiumai.codiumai]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:89)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.computeOnEdt(ActionUpdater.kt:225)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.access$computeOnEdt(ActionUpdater.kt:73)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$computeOnEdt$1.invokeSuspend(ActionUpdater.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: java.lang.Throwable: EDT-trace-at-315-ms (5/5)
		at java.desktop/sun.awt.windows.WComponentPeer.getLocationOnScreen(Native Method)
		at java.desktop/java.awt.Component.getLocationOnScreen_NoTreeLock(Component.java:2131)
		at java.desktop/java.awt.Component.getLocationOnScreen(Component.java:2109)
		at java.desktop/javax.swing.SwingUtilities.convertPointToScreen(SwingUtilities.java:437)
		at java.desktop/javax.swing.SwingUtilities.convertPoint(SwingUtilities.java:197)
		at com.intellij.ui.awt.RelativePoint.getPoint(RelativePoint.java:77)
		at com.intellij.ui.BalloonImpl.show(BalloonImpl.java:500)
		at com.intellij.ui.BalloonImpl.show(BalloonImpl.java:448)
		at com.intellij.openapi.wm.impl.status.ProcessBalloon.show(ProcessBalloon.java:89)
		at com.intellij.openapi.wm.impl.status.ProcessBalloon.addIndicator(ProcessBalloon.java:45)
		at com.intellij.openapi.wm.impl.status.InfoAndProgressPanel.addProgress(InfoAndProgressPanel.kt:247)
		at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.addProgress(IdeStatusBarImpl.kt:462)
		at com.intellij.openapi.progress.impl.BackgroundableProcessIndicator.doBackground(BackgroundableProcessIndicator.java:177)
		at com.intellij.openapi.progress.impl.BackgroundableProcessIndicator.initializeStatusBar(Background

<TRIMMED STACKTRACE>

733)
		at java.base@17.0.9/java.security.AccessController.executePrivileged(AccessController.java:776)
		at java.base@17.0.9/java.security.AccessController.doPrivileged(AccessController.java:399)
		at java.base@17.0.9/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
		at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
		at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
		at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
		at com.intellij.ide.IdeEventQueue$$Lambda$732/0x0000000800760758.run(Unknown Source)
		at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
		at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
		at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
		at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
		at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
		at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
		at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
		at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
		at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
		at com.intellij.ide.IdeEventQueueKt$$Lambda$731/0x000000080075f540.run(Unknown Source)
		at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
		at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
		at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
		at com.intellij.ide.IdeEventQueue$$Lambda$730/0x000000080075d5b8.run(Unknown Source)
		at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
		at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
		at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
		at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
		at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
		at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
		at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

# Other Information
```
=== About ===
Build version: PhpStorm 2023.3 Beta Build: #PS-233.11799.21 November 13, 2023
Theme: Dark
JRE: 17.0.9+7-b1087.3, JetBrains s.r.o.
JVM: 17.0.9+7-b1087.3, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [Laravel Tinker (2.6.1), FileSync (1.15.0), .env files support (2023.3), Elm (4.4.1), PHP Advanced AutoComplete (1.1.0), Python custom import (2.0.2), AI Assistant (233.11799.38), CodeGPT - ChatGPT For Laravel (1.05), GitHub Copilot (1.4.2.3864), Copilot Word by Word (0.1.0), PHP Toolbox (6.2.0), Space (233.11799.29), Laravel Query (4.0.2), SQL Optimizer, Indexing Advisor, MySQL, PostgreSQL, by EverSQL (1.3.1), Php Inspections (EA Extended) (5.0.0.0), PHP Annotations (9.4.0), CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.6.19)]
Disabled plugins:[Copilot Dark Theme (1.0.4), PHPUnit code coverage (0.5.0), ChatGPT X-Copilot Context Aware & Function calling (2023.10.21)]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting! We are working on it.
