### ISSUE TITLE
[0.6.17][WEBSTORM 2023.2.3] java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 1 out of bounds fo...

### ISSUE THREAD

**Issue by gramcha** [Codium-ai/codiumai-jetbrains-release#153]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 1 out of bounds for int[0]
	at java.base/java.lang.System.arraycopy(Native Method)
	at java.desktop/javax.swing.text.BoxView.updateLayoutArray(BoxView.java:215)
	at java.desktop/javax.swing.text.BoxView.replace(BoxView.java:186)
	at java.desktop/javax.swing.text.View.append(View.java:416)
	at java.desktop/javax.swing.text.FlowView$FlowStrategy.layout(FlowView.java:499)
	at java.desktop/javax.swing.text.FlowView.layout(FlowView.java:209)
	at java.desktop/javax.swing.text.BoxView.setSize(BoxView.java:398)
	at java.desktop/javax.swing.text.BoxView.updateChildSizes(BoxView.java:367)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:349)
	at java.desktop/javax.swing.text.BoxView.layout(BoxView.java:709)
	at java.desktop/javax.swing.text.BoxView.setSize(BoxView.java:398)
	at java.desktop/javax.swing.text.BoxView.updateChildSizes(BoxView.java:367)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:349)
	at java.desktop/javax.swing.text.BoxView.layout(BoxView.java:709)
	at java.desktop/javax.swing.text.BoxView.setSize(BoxView.java:398)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1826)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$RootView.paint(BasicTextUI.java:1537)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.paintSafely(BasicTextUI.java:757)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.paint(BasicTextUI.java:915)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.update(BasicTextUI.java:894)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:845)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1115)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5312)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:247)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1347)
	at java.desktop/javax.swing.JComponent.paintForceDoubleBuffered(JComponent.java:1151)
	at java.desktop/javax.swing.JViewport.paintView(JViewport.java:1752)
	at java.desktop/javax.swing.JViewport.windowBlitPaint(JViewport.java:1675)
	at java.desktop/javax.swing.JViewport.setViewPosition(JViewport.java:1219)
	at java.desktop/javax.swing.plaf.basic.BasicScrollPaneUI$Handler.vsbStateChanged(BasicScrollPaneUI.java:1189)
	at java.desktop/javax.swing.plaf.basic.BasicScrollPaneUI$Handler.stateChanged(BasicScrollPaneUI.java:1178)
	at java.desktop/javax.swing.DefaultBoundedRangeModel.fireStateChanged(DefaultBoundedRangeModel.java:371)
	at java.desktop/javax.swing.DefaultBoundedRangeModel.setRangeProperties(DefaultBoundedRangeModel.java:309)
	at java.desktop/javax.swing.DefaultBoundedRangeModel.setValue(DefaultBoundedRangeModel.java:175)
	at java.desktop/javax.swing.JScrollBar.setValue(JScrollBar.java:486)
	at ai.codium.ui.prePR.CodiumPrePRPanel.updateMessageUI$lambda$11$lambda$10(CodiumPrePRPanel.kt:363)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:254)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:373)
	at com.intellij.util.Alarm$Request.run(Alarm.java:360)
	at com.intellij.util.concurrency.Propagation.contextAwareCallable$lambda$2(propagation.kt:328)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

# Other Information
```
=== About ===
Build version: WebStorm 2023.2.3 Build: #WS-232.10072.28 October 11, 2023
Theme: Light
JRE: 17.0.8.1+7-b1000.32, JetBrains s.r.o.
JVM: 17.0.8.1+7-b1000.32, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.0 (aarch64)

=== Plugins ===
Custom plugins: [AI Assistant (232.9826), .ignore (4.5.2), ESLint Restart Service Action (0.0.1), Space (232.10072.29), SonarLint (10.0.0.76954), Makefile Language (232.8660.88), CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.6.17), String Manipulation (9.11.3)]
Disabled plugins:[Node.js Remote Interpreter (232.10072.28), SSH Remote Run (232.10072.28), ANSI Highlighter Premium (23.2.0), SonarQube Analyzer (2.9.9), Vuesion Theme (1.9.2), deep-js-completion (2020.06.22.001), Key Promoter X (2023.2.0), Angular and AngularJS (232.10072.28), Ideolog (222.1.0.0), Properties (232.8660.88), GapStyle Color Scheme (4.1), Cucumber + (15.3.3), Vagrant (232.10072.28), FTP/SFTP/WebDAV Connectivity (232.10072.28), AWS Toolkit (1.85-232), IDE Features Trainer (232.9559.6), Gradianto (5.5)]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting! We are working on it, but unfortunately it looks like IDE internal error :(
