### ISSUE TITLE
[0.7.02][INTELLIJ IDEA IU 2023.3 RC] java.lang.RuntimeException: Cannot invoke (class=CodiumPrePRPanel$$Lambda$13743/...

### ISSUE THREAD

**Issue by vikky49** [Codium-ai/codiumai-jetbrains-release#154]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.RuntimeException: Cannot invoke (class=CodiumPrePRPanel$$Lambda$13743/0x0000008804c4a3a8, method=repositoryChanged, topic=GitRepository change)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:677)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:423)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:402)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:461)
	at jdk.proxy12/jdk.proxy12.$Proxy154.repositoryChanged(Unknown Source)
	at git4idea.repo.GitRepositoryUpdater.filesChanged(GitRepositoryUpdater.java:138)
	at com.intellij.vfs.AsyncVfsEventsPostProcessorImpl.processEvents$lambda$2(AsyncVfsEventsPostProcessorImpl.kt:51)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$runUnderDisposeAwareIndicator$15(BackgroundTaskUtil.java:371)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:366)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:349)
	at com.intellij.vfs.AsyncVfsEventsPostProcessorImpl.processEvents(AsyncVfsEventsPostProcessorImpl.kt:50)
	at com.intellij.vfs.AsyncVfsEventsPostProcessorImpl.access$processEvents(AsyncVfsEventsPostProcessorImpl.kt:20)
	at com.intellij.vfs.AsyncVfsEventsPostProcessorImpl$queue$1.invoke(AsyncVfsEventsPostProcessorImpl.kt:21)
	at com.intellij.vfs.AsyncVfsEventsPostProcessorImpl$queue$1.invoke(AsyncVfsEve

<TRIMMED STACKTRACE>

m.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 16 out of bounds for length 16
	at com.intellij.ui.components.WideSelectionListUI.updateLayoutState(WideSelectionListUI.java:207)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1394)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.getCellBounds(BasicListUI.java:1032)
	at com.intellij.ui.components.WideSelectionListUI.getCellBounds(WideSelectionListUI.java:159)
	at java.desktop/javax.swing.JList.getCellBounds(JList.java:1668)
	at java.desktop/javax.swing.JList.ensureIndexIsVisible(JList.java:1180)
	at java.desktop/javax.swing.plaf.basic.BasicComboPopup.setListSelection(BasicComboPopup.java:1274)
	at java.desktop/javax.swing.plaf.basic.BasicComboPopup$Handler.itemStateChanged(BasicComboPopup.java:1097)
	at java.desktop/javax.swing.JComboBox.fireItemStateChanged(JComboBox.java:1257)
	at java.desktop/javax.swing.JComboBox.selectedItemChanged(JComboBox.java:1318)
	at java.desktop/javax.swing.JComboBox.contentsChanged(JComboBox.java:1365)
	at java.desktop/javax.swing.AbstractListModel.fireContentsChanged(AbstractListModel.java:127)
	at java.desktop/javax.swing.DefaultComboBoxModel.setSelectedItem(DefaultComboBoxModel.java:94)
	at java.desktop/javax.swing.DefaultComboBoxModel.addElement(DefaultComboBoxModel.java:132)
	at java.desktop/javax.swing.JComboBox.addItem(JComboBox.java:746)
	at ai.codium.ui.prePR.CodiumPrePRPanel.setBranches(CodiumPrePRPanel.kt:84)
	at ai.codium.ui.prePR.CodiumPrePRPanel.setRepositoryListener$lambda$3(CodiumPrePRPanel.kt:118)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:700)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:660)
	... 47 more

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2023.3 RC Build: #IU-233.11799.196 November 29, 2023
Theme: Light
JRE: 17.0.9+7-b1087.7, JetBrains s.r.o.
JVM: 17.0.9+7-b1087.7, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 14.1.1 (aarch64)

=== Plugins ===
Custom plugins: [Native Debugging Support (233.11799.188), PlantUML Integration (7.3.0-IJ2023.2), Python (233.11799.241), JPA Buddy (2023.4.1-233), GraalVM Native Debugger (233.11799.196), Dev Containers (233.11799.244), FitNesse (1.13.0), Spring WebSocket (233.11799.196), Tabnine: AI Code Completion & Chat in Java JS/TS Python & More (1.37.0), Rainbow Brackets (2023.3.9-233), JavaCC (1.12.1), AI Assistant (233.11799.241), IntelliJ New UI (0.4), .env files support (2023.3), GraphQL (233.11799.172), AWS Toolkit - Amazon Q, CodeWhisperer, and more (2.1-233), Goctl (1.1.9), Archive Browser (0.32), AsciiDoc (0.41.2), Go (233.11799.196), CheckStyle-IDEA (5.85.0), CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.7.02)]
Disabled plugins:[Metastore Core (233.11799.196), Fig (2.0.0), Gitlab CI Pipeline Dashboard (2023.8.1), wl Spring Assistant (1.4.6.222.232), Code With Me (233.11799.196), Kafka (233.11799.241), Sapient AI Test Coder (2023.1.228), [Deprecated] Rust (0.4.201.5424-232), Spring Web Services (233.11799.196), Flink (233.11799.196), Remote File Systems (233.11799.241), Spark (233.11799.241), Big Data Tools (233.11799.196), DynamoDB (2023.3.0-233), CodeGPT (2.2.9), Zeppelin (233.11799.196), Big Data File Viewer (233.11799.196), Digma Continuous Feedback (2.0.209+233)]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting! We are working on it.
