### ISSUE TITLE
[0.7.07][PYCHARM PY 2023.2.1] com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl....

### ISSUE THREAD

**Issue by BorisPervushin** [Codium-ai/codiumai-jetbrains-release#159]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl.source.tree.CompositeElement of type Py:CLASS_DECLARATION (class com.jetbrains.python.psi.impl.stubs.PyClassElementType)
	at com.intellij.psi.PsiInvalidElementAccessException.createByNode(PsiInvalidElementAccessException.java:80)
	at com.intellij.psi.impl.source.SubstrateRef$2.getContainingFile(SubstrateRef.java:74)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:235)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getProject(StubBasedPsiElementBase.java:271)
	at ai.codium.elements.CutElement$getProject$$inlined$runReadAction$1.compute(actions.kt:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at ai.codium.elements.CutElement.getProject(CutElement.kt:181)
	at ai.codium.ui.contentParts.ContextPanel.getUserCodeSnippetContextItems(ContextPanel.kt:107)
	at ai.codium.ui.contentParts.ContextPanel.getContextItems(ContextPanel.kt:86)
	at ai.codium.ui.contentParts.ContextPanel.displayContextItems(ContextPanel.kt:190)
	at ai.codium.ui.contentParts.ContextPanel.setContextAnalysis(ContextPanel.kt:68)
	at ai.codium.ui.CodiumTestSuiteContentPanel.loadingTestSuiteDataFinished(CodiumTestSuiteContentPanel.kt:77)
	at ai.codium.ui.CodiumToolWindowFactory$createToolWindowContent$4.generateResponseReceived$lambda$0(CodiumToolWindowFactory.kt:234)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

# Other Information
```
=== About ===
Build version: PyCharm 2023.2.1 Build: #PY-232.9559.58 August 22, 2023
Theme: Darcula
JRE: 17.0.8+7-b1000.8, JetBrains s.r.o.
JVM: 17.0.8+7-b1000.8, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.4 (aarch64)

=== Plugins ===
Custom plugins: [Monokai Pro Theme (1.10), CSV Editor (3.2.1-232), Dark Purple Theme (1.3), CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.7.07), Xcode-Dark Theme (1.2.4), Visual Studio Code Dark Plus Theme (2.8), Xcode Theme (1.6.3), Nord (0.13.0), Monocai Color Theme (2.0.2c), Dracula Theme (1.15.2), Pylint (0.14.0), Atom One Theme (1.5.1)]
Disabled plugins:[TLDR (1.0.0), Requirements Pro (2022.4)]
```

**Comment by ArtsiomCh** [comment]
Thank you for reporting!
Fixed in 0.7.10 (and up)
