### ISSUE TITLE
[0.7.10][ANDROID STUDIO Hedgehog | 2023.1.1] java.lang.NullPointerException: Cannot invoke "java.awt.FontMetrics.getF...

### ISSUE THREAD

**Issue by barnett-yuxiang** [Codium-ai/codiumai-jetbrains-release#163]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.NullPointerException: Cannot invoke "java.awt.FontMetrics.getFont()" because "<parameter4>" is null
	at java.desktop/sun.swing.SwingUtilities2.getFontCharsWidth(Unknown Source)
	at java.desktop/sun.swing.SwingUtilities2.getFontCharWidth(Unknown Source)
	at java.desktop/javax.swing.text.Utilities.getTabbedTextOffset(Unknown Source)
	at java.desktop/javax.swing.text.GlyphPainter1.getBoundedPosition(Unknown Source)
	at java.desktop/javax.swing.text.GlyphView.getBreakWeight(Unknown Source)
	at java.desktop/javax.swing.text.html.InlineView.getBreakWeight(Unknown Source)
	at java.desktop/javax.swing.text.ParagraphView.findEdgeSpan(Unknown Source)
	at java.desktop/javax.swing.text.ParagraphView.calculateMinorAxisRequirements(Unknown Source)
	at java.desktop/javax.swing.text.html.ParagraphView.calculateMinorAxisRequirements(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.checkRequests(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.getMinimumSpan(Unknown Source)
	at java.desktop/javax.swing.text.html.ParagraphView.getMinimumSpan(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.calculateMinorAxisRequirements(Unknown Source)
	at java.desktop/javax.swing.text.html.BlockView.calculateMinorAxisRequirements(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.checkRequests(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.getMinimumSpan(Unknown Source)
	at java.desktop/javax.swing.text.html.BlockView.getMinimumSpan(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.calculateMinorAxisRequirements(Unknown Source)
	at java.desktop/javax.swing.text.html.BlockView.calculateMinorAxisRequirements(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.checkRequests(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.getPreferredSpan(Unknown Source)
	at java.desktop/javax.swing.text.html.BlockView.getPreferredSpan(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicHTML$Renderer.<init>(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicHTML.createHTMLView(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicHTML.updateRenderer(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicLabelUI.propertyChange(Unknown Source)
	at java.desktop/java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.desktop/java.awt.Component.firePropertyChange(Unknown Source)
	at java.desktop/java.awt.Component.updateGraphicsData(Unknown Source)
	at java.desktop/java.awt.Container.updateChildGraphicsData(Unknown Source)
	at java.desktop/java.awt.Component.updateGraphicsData(Unknown Source)
	at java.desktop/java.awt.Container.updateChildGraphicsData(Unknown Source)
	at java.desktop/java.awt.Component.updateGraphicsData(Unknown Source)
	at java.desktop/java.awt.Container.u

<TRIMMED STACKTRACE>

1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:829)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:571)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1444)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:571)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:829)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

```

# Other Information
```
=== About ===
Build version: Android Studio Hedgehog | 2023.1.1 Build: #AI-231.9392.1.2311.11076708 November 10, 2023
Theme: Dark
JRE: 17.0.7+0-17.0.7b1000.6-10550314, JetBrains s.r.o.
JVM: 17.0.7+0-17.0.7b1000.6-10550314, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 14.2.1 (aarch64)

=== Plugins ===
Custom plugins: [Codeium: AI Autocomplete and Chat for Python, JS, TS, Java, Go… (1.6.11), GitHub Copilot (1.4.5.4049), CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.7.10)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Thank you for reporting!
Seems like IDE internal bug with UI components.
