### ISSUE TITLE
[0.7.10][RUBYMINE 2023.3.2] java.lang.RuntimeException: Cannot invoke (class=, method=repositoryChanged, topic=GitRep...

### ISSUE THREAD

**Issue by alessiobussolari** [Codium-ai/codiumai-jetbrains-release#165]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.RuntimeException: Cannot invoke (class=, method=repositoryChanged, topic=GitRepository change)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:677)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:423)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:402)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:461)
	at jdk.proxy6/jdk.proxy6.$Proxy149.repositoryChanged(Unknown Source)
	at git4idea.repo.GitRepositoryManager.lambda$notifyListenersAsync$2(GitRepositoryManager.java:84)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:244)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:222)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.RuntimeException: Cannot invoke (class=CodiumPrePRPanel$$Lambda$4130/0x0000000801debd80, method=repositoryChanged, topic=GitRepository change)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:677)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:423)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:392)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:461)
	at jdk.proxy1/jdk.proxy1.$Proxy150.dirtyUnder(Unknown Source)
	at git4idea.annotate.GitAnnotationsListener$1.repositoryChanged(GitAnnotationsListener.java:24)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:700)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:660)
	... 19 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at com.intellij.ui.components.WideSelectionListUI.updateLayoutState(WideSelectionListUI.java:207)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1394)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2815)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:224)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:204)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:251)
	at java.desktop/javax.swing.DefaultListSelectionModel.insertIndexInterval(DefaultListSelectionModel.java:675)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.intervalAdded(BasicListUI.java:2773)
	at java.desktop/javax.swing.AbstractListModel.fireIntervalAdded(AbstractListModel.java:157)
	at java.desktop/javax.swing.DefaultComboBoxModel.addElement(DefaultComboBoxModel.java:130)
	at java.desktop/javax.swing.JComboBox.addItem(JComboBox.java:746)
	at ai.codium.ui.prePR.CodiumPrePRPanel.setBranches(CodiumPrePRPanel.kt:86)
	at ai.codium.ui.prePR.CodiumPrePRPanel.setRepositoryListener$lambda$3(CodiumPrePRPanel.kt:120)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:700)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:660)
	... 27 more

```

# Other Information
```
=== About ===
Build version: RubyMine 2023.3.2 Build: #RM-233.13135.91 December 19, 2023
Theme: Dark
JRE: 17.0.9+7-b1087.9, JetBrains s.r.o.
JVM: 17.0.9+7-b1087.9, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.4.1 (aarch64)

=== Plugins ===
Custom plugins: [Json Formatter (1.4), .ignore (4.5.2), RubyRefactorings (0.1.22), AI Assistant (233.13135.103), Jsoncrack (1.2.1), .env files support (2023.3), Rainbow Brackets (2023.3.9-233), CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.7.10), Atom Material Icons (94.1.0)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Thank you for reporting!
