### ISSUE TITLE
[0.7.10][PYCHARM PY 2023.3.1] java.lang.IllegalStateException: GitRepository not found

### ISSUE THREAD

**Issue by DojiTrav** [Codium-ai/codiumai-jetbrains-release#166]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.IllegalStateException: GitRepository not found
	at ai.codium.vcsIntegration.GitHelper.<init>(GitHelper.kt:20)
	at ai.codium.ui.prePR.CodiumPrePRPanel.<init>(CodiumPrePRPanel.kt:36)
	at ai.codium.ui.prePR.CodiumPrePRToolWindow$createToolWindowContent$determineToolWindowContent$2$1.invoke(CodiumPrePRToolWindow.kt:84)
	at ai.codium.ui.prePR.CodiumPrePRToolWindow$createToolWindowContent$determineToolWindowContent$2$1.invoke(CodiumPrePRToolWindow.kt:82)
	at ai.codium.CodiumLoginHelperKt$runRefreshTokenBackgroundCheck$1.run(CodiumLoginHelper.kt:108)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:484)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

# Other Information
```
=== About ===
Build version: PyCharm 2023.3.1 Build: #PY-233.11799.298 December 12, 2023
Theme: High Contrast
JRE: 17.0.9+7-b1087.7, JetBrains s.r.o.
JVM: 17.0.9+7-b1087.7, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [GitHub Copilot (1.4.5.4049), .env files support (2023.3), AI Assistant (233.11799.306), CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.7.10)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Seems like internal IDE glitch. :-/ Please let us know if it happens again.
