### ISSUE TITLE
[Exception][PyCharm 2022.3.2] java.lang.ClassCastException: class ai.codium.analytic.CodiumAnalyticService cannot be ...

### ISSUE THREAD

**Issue by noonetown1997** [Codium-ai/codiumai-jetbrains-release#17]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.ClassCastException: class ai.codium.analytic.CodiumAnalyticService cannot be cast to class ai.codium.analytic.CodiumAnalyticService (ai.codium.analytic.CodiumAnalyticService is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @20a1ec44; ai.codium.analytic.CodiumAnalyticService is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @14e6dd10)
	at ai.codium.UtilsKt.getCodiumAnalyticService(Utils.kt:128)
	at ai.codium.net.CodiumLoginManager$Companion.sendLoginFinishedEvent(CodiumLoginManager.kt:58)
	at ai.codium.net.CodiumHttpRequestHandler.process$processError(CodiumHttpRequestHandler.kt:37)
	at ai.codium.net.CodiumHttpRequestHandler.access$process$processError(CodiumHttpRequestHandler.kt:19)
	at ai.codium.net.CodiumHttpRequestHandler$process$signInResponse$1.invoke(CodiumHttpRequestHandler.kt:63)
	at ai.codium.net.CodiumHttpRequestHandler$process$signInResponse$1.invoke(CodiumHttpRequestHandler.kt:60)
	at ai.codium.net.CodiumNetworkClient.executeRequest(CodiumNetworkClient.kt:26)
	at ai.codium.net.CodiumNetworkClient.executeRequest(CodiumNetworkClient.kt:41)
	at ai.codium.net.CodiumNetworkClient.executeRequest$default(CodiumNetworkClient.kt:18)
	at ai.codium.net.CodiumFirebaseApiClient.signInWithProvider$codium_ai_plugin(CodiumFirebaseApiClient.kt:19)
	at ai.codium.net.CodiumNetworkService.loginToFirebase(CodiumNetworkService.kt:39)
	at ai.codium.net.CodiumHttpRequestHandler.process(CodiumHttpRequestHandler.kt:60)
	at org.jetbrains.io.DelegatingHttpRequestHandler.process$checkAndProcess(DelegatingHttpRequestHandler.kt:21)
	at org.jetbrains.io.DelegatingHttpRequestHandler.access$process$checkAndProcess(DelegatingHttpRequestHandler.kt:15)
	at org.jetbrains.io.DelegatingHttpRequestHandler$process$1.invoke(DelegatingHttpRequestHandler.kt:35)
	at org.jetbrains.io.DelegatingHttpRequestHandler$process$1.invoke(DelegatingHttpRequestHandler.kt:34)
	at org.jetbrains.io.DelegatingHttpRequestHandler.process$lambda$0(DelegatingHttpRequestHandler.kt:34)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.lambda$findFirstSafe$0(ExtensionProcessingHelper.java:47)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.java:57)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.findFirstSafe(ExtensionProcessingHelper.java:47)
	at com.intellij.openapi.extensions.ExtensionPointName.findFirstSafe(ExtensionPointName.java:50)
	at org.jetbrains.io.DelegatingHttpRequestHandler.process(DelegatingHttpRequestHandler.kt:34)
	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpReques

<TRIMMED STACKTRACE>

va:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.jetbrains.io.PortUnificationServerHandler.decode(PortUnificationServerHandler.java:129)
	at org.jetbrains.io.PortUnificationServerHandler.messageReceived(PortUnificationServerHandler.java:76)
	at org.jetbrains.io.Decoder.channelRead(Decoder.java:24)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

# Other Information
```
=== About ===
Build version: PyCharm 2022.3.2 Build: #PY-223.8617.48 January 24, 2023
Theme: VSCode Dark
JRE: 17.0.5+1-b653.25, JetBrains s.r.o.
JVM: 17.0.5+1-b653.25, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.3 (aarch64)

=== Plugins ===
Custom plugins: [ChatGPT (2.1.12-222.231), Material Theme UI (8.4.1), Atom OneDark Theme (1.6), Json Parser (1.4.1), .env files support (2022.3), Big Data Tools (223.8617.9), String Manipulation (9.7.1), VSCode Theme (1.7.8), Perl (2022.3.3), Chinese (Simplified) Language Pack / 中文语言包 (223.228), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.4.11), Requirements (2022.4.1), Green lite theme (0.1.2), Darcula Darker Theme (1.2.0), XPathView + XSLT (223.7571.112), Ideolog (203.0.30.0), Key Promoter X (2023.1.0), Atom Material Icons (85.1.0), CodeGlance Pro (1.6.0), CSV Editor (3.1.0-223), Gerry Themes (2023.1.30), .ignore (4.4.4), One Dark Native (1.5), Nyan Progress Bar (1.14)]
Disabled plugins:[Selenium UI Testing (223.7571.117), Just Another Dark Theme (2022.2), Aqua (223.7571.117)]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/w6zcYQti) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Hi @noonetown1997 !
Thanks for reporting!
Was it one time glitch or is it happening again and there's a way to reproduce it?
PS do you have PyCharm installed locally or some kind of remote connection to ide is used?

**Comment by almog-lv** [comment]
Hey @noonetown1997, were you able to reproduce this bug again?

**Comment by ArtsiomCh** [comment]
Looks like one time PyCharm glitch. Will close for now and we'll keep our eyes for this component.
