### ISSUE TITLE
[0.7.12][GOLAND 2023.3.2] java.lang.Throwable: psiElement is not instance of requiredClass.psiElement=FIELD_DEFINITI...

### ISSUE THREAD

**Issue by kasumusof** [Codium-ai/codiumai-jetbrains-release#171]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable: psiElement is not instance of requiredClass.
psiElement=FIELD_DEFINITION, psiElement.class=class com.goide.psi.impl.GoFieldDefinitionImpl, requiredClass=interface com.goide.psi.GoMethodDeclaration, operation=Looking for subscription.Subscription in go.method, stubIdList=[93].
ref: 50cf572587cf
com.intellij.psi.stubs.UpToDateStubIndexMismatch: PSI and index do not match.
Please report the problem to JetBrains with the files attached
INDEXED VERSION IS THE CURRENT ONE file=GO_FILE, file.class=class com.goide.psi.GoFile, file.lang=Language: go, modStamp=454
 tree consistent
 stub debugInfo=created in calcStubTree; with backReference
 viewProvider=com.intellij.psi.SingleRootFileViewProvider{vFile=file:///Users/kasumusof/Documents/busha/groot/pkg/yield/subscription/models.go, vFileId=7666, content=VirtualFileContent{size=3493}, eventSystemEnabled=true}
 viewProvider stamp: 291403; file stamp: 291403; file modCount: 1705315162967; file length: 3493
 doc saved: true; doc stamp: 291403; doc size: 3493; committed: true
indexing info: indexing timestamp = 1705315162967, binary = false, byte size = 3493, char size = 3493
ref: 50cf572587cf
latestIndexedStub=StubTree{myDebugInfo='created from index; with backReference', myRoot=GoFileStub}828726368
   same size=false
   debugInfo=created from index; with backReference
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.psi.stubs.StubProcessingHelperBase.inconsistencyDetected(StubProcessingHelperBase.java:156)
	at com.intellij.psi.stubs.StubProcessingHelperBase.checkType(StubProcessingHelperBase.java:90)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:61)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$5(StubIndexEx.java:152)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:202)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:102)
	at com.goide.stubs.index.GoMethodIndex.find(GoMethodIndex.java:52)
	at com.goide.psi.impl.GoPsiImplUtil.calcMethods(GoPsiImplUtil.java:1654)
	at com.goide.psi.impl.GoPsiImplUtil.lambda$getMethods$32(GoPsiImplUtil.java:1510)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:24

<TRIMMED STACKTRACE>

(GoPsiImplUtil.java:1506)
	at com.goide.psi.impl.GoTypeSpecImpl.getMethods(GoTypeSpecImpl.java:48)
	at ai.codium.language.GoLanguageService.doGetSupportedElementsForClass$codium_ai_plugin(GoLanguageService.kt:66)
	at ai.codium.language.LanguageService.getSupportedElementsForClass(LanguageService.kt:81)
	at ai.codium.language.LanguageService.getSupportedElements$codium_ai_plugin(LanguageService.kt:63)
	at ai.codium.CodiumInlayProvider.getCollectorFor(CodiumInlayProvider.kt:80)
	at ai.codium.CodiumInlayProvider.getCollectorFor(CodiumInlayProvider.kt:35)
	at com.intellij.codeInsight.hints.InlayHintsUtilsKt.getCollectorWrapperFor(InlayHintsUtils.kt:50)
	at com.intellij.codeInsight.daemon.impl.InlayHintsPassFactoryInternal.createHighlightingPass(InlayHintsPassFactoryInternal.kt:46)
	at com.intellij.codeInsight.daemon.impl.TextEditorHighlightingPassRegistrarImpl.instantiatePasses(TextEditorHighlightingPassRegistrarImpl.java:186)
	at com.intellij.codeInsight.daemon.impl.TextEditorBackgroundHighlighter.getPasses(TextEditorBackgroundHighlighter.kt:65)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$submitInBackground$25(DaemonCodeAnalyzerImpl.java:1163)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$submitInBackground$26(DaemonCodeAnalyzerImpl.java:1152)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.submitInBackground(DaemonCodeAnalyzerImpl.java:1149)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$queuePassesCreation$21(DaemonCodeAnalyzerImpl.java:1114)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:187)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

# Other Information
```
=== About ===
Build version: GoLand 2023.3.2 Build: #GO-233.13135.104 December 20, 2023
Theme: Dark
JRE: 17.0.9+7-b1087.9, JetBrains s.r.o.
JVM: 17.0.9+7-b1087.9, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 14.0 (aarch64)

=== Plugins ===
Custom plugins: [CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.7.12), Codeium: AI Autocomplete and Chat for Python, JS, TS, Java, Go… (1.6.11), Mermaid (0.0.18+IJ.232), Space (233.13135.68)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Thanks  for reporting!
Seems like internal IDE bug:
```
com.intellij.psi.stubs.UpToDateStubIndexMismatch: PSI and index do not match.
Please report the problem to JetBrains with the files attached
```
