### ISSUE TITLE
[0.7.14][WEBSTORM 2023.3.2] A suspiciously high nesting of suppressPrioritizing, forgot to call restorePrioritizing?

### ISSUE THREAD

**Issue by owaismg9** [Codium-ai/codiumai-jetbrains-release#175]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:130)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:388)
	at com.intellij.openapi.progress.impl.CoreProgressManager.suppressPrioritizing(CoreProgressManager.java:830)
	at com.intellij.openapi.progress.impl.CoreProgressManager.avoidBlockingPrioritizingThread(CoreProgressManager.java:886)
	at com.intellij.openapi.progress.impl.CoreProgressManager.sleepIfNeededToGivePriorityToAnotherThread(CoreProgressManager.java:846)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runCheckCanceledHooks(ProgressManagerImpl.java:223)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:147)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:233)
	at com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled(ProgressIndicatorProvider.java:23)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:162)
	at com.intellij.util.PsiErrorElementUtil.lambda$hasErrors$0(PsiErrorElementUtil.java:25)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65)
	at com.intellij.util.PsiErrorElementUtil.hasErrors(PsiErrorElementUtil.java:23)
	at ai.codium.UtilsKt.hasPsiErrors(Utils.kt:234)
	at ai.codium.ui.structureview.CodiumStructureViewRootElement.getChildren(CodiumStructureViewElements.kt:87)
	at ai.codium.ui.structureview.CodiumStructureViewRootElement.getChildren(CodiumStructureViewElements.kt:70)
	at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.initChildren(TreeElementWrapper.java:35)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.rebuildSubtree(CachingChildrenTreeNode.java:207)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.ensureChildrenAreInitialized(CachingChildrenTreeNode.java:41)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.getChildren(Ca

<TRIMMED STACKTRACE>

i.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:108)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:73)
	at com.intellij.util.concurrency.Invoker.startTask(Invoker.java:238)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:194)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:177)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:508)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:244)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:222)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

# Other Information
```
=== About ===
Build version: WebStorm 2023.3.2 Build: #WS-233.13135.92 December 19, 2023
Theme: Light
JRE: 17.0.9+7-b1087.9, JetBrains s.r.o.
JVM: 17.0.9+7-b1087.9, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [.env files support (2023.3), React Buddy (233.13135.65), CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.7.14)]
Disabled plugins:[Task Management (233.13135.92), WarmNeon Color Scheme (233.13135.92), FTP/SFTP/WebDAV Connectivity (233.13135.92), Angular and AngularJS (233.13135.92), Refactor-X (233.13135.92), Handlebars/Mustache (233.13135.92), Vite (233.13135.92), IntelliLang (233.13135.92), EJS (233.13135.92), VSCode Keymap (233.13135.92), Performance Testing (Dynamic Plugins) (233.13135.92), Monokai Color Scheme (233.13135.92), Mercurial (233.13135.92), Visual Studio Keymap (233.13135.92), TSLint (233.13135.92), Polymer & Web Components (233.13135.92), All Hallow's Eve Color Scheme (233.13135.92), AI Assistant (233.13135.92), Pug (ex-Jade) (233.13135.92), GitHub Color Scheme (233.13135.92), Karma (233.13135.92), Live Edit (233.13135.92), VibrantInk Color Scheme (233.13135.92), EditorConfig (233.13135.92), Vagrant (233.13135.92), JavaScript Intention Power Pack (233.13135.92), Space (233.13135.92), Node.js Remote Interpreter (233.13135.92), Cucumber.js (233.13135.92), GitHub Copilot (1.2.17.2887), Diagrams (233.13135.92), WebP Support (233.13135.92), Less (233.13135.92), SSH Remote Run (233.13135.92), Performance Testing (233.13135.92), Time Tracking (233.13135.92), Code With Me (233.13135.92), Gherkin (233.13135.92), Machine Learning in Search Everywhere (233.13135.92), Machine Learning Code Completion (233.13135.92), Cobalt Color Scheme (233.13135.92), NetBeans Keymap (233.13135.92), Remote Development Gateway (233.13135.92), HTML Tools (233.13135.92), CSharp (0.1), Styled Components & Styled JSX (233.13135.92), TextMate Bundles (233.13135.92), Blackboard Color Scheme (233.13135.92), Next.js Support (233.13135.92), Twilight Color Scheme (233.13135.92), Subversion (233.13135.92), Vue.js (233.13135.92), Copyright (233.13135.92), Eclipse Keymap (233.13135.92), Terminal for Gateway (233.13135.92), Dev Containers (233.13135.92), Railscasts Color Scheme (233.13135.92)]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
