### ISSUE TITLE
[0.7.15][PHPSTORM 2023.3.2] java.nio.file.InvalidPathException: UNC path is missing sharename: /\.codiumai.toml

### ISSUE THREAD

**Issue by meran77777** [Codium-ai/codiumai-jetbrains-release#176]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.nio.file.InvalidPathException: UNC path is missing sharename: /\.codiumai.toml
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:118)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at ai.codium.configuration.CodiumTomlFileManagerKt.readTomlTestsTable(CodiumTomlFileManager.kt:49)
	at ai.codium.configuration.CodiumTomlFileManagerKt.readTomlConfigurations(CodiumTomlFileManager.kt:36)
	at ai.codium.configuration.ConfigurationsManager.getAnalysisConfiguration(ConfigurationsManager.kt:67)
	at ai.codium.configuration.ConfigurationsManager.getAnalysisConfiguration$default(ConfigurationsManager.kt:61)
	at ai.codium.AnalysisManagerKt$runAnalysis$2$1.run(AnalysisManager.kt:91)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:484)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

# Other Information
```
=== About ===
Build version: PhpStorm 2023.3.2 Build: #PS-233.13135.108 December 21, 2023
Theme: Dark
JRE: 17.0.9+7-b1087.9, JetBrains s.r.o.
JVM: 17.0.9+7-b1087.9, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [ChatGPT GPT-4 - Bito AI Code Assistant (1.2.7), CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.7.15), CodeGPT (2.2.12), AI Assistant (233.13135.116)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Seems like IDE internal glitch with parent directory recognition... 
Let us know please, if it happens again to you.
