### ISSUE TITLE
[0.7.15][JETBRAINS RIDER 2023.3.3] com.intellij.util.IncorrectOperationException: Sorry but parent: CodiumAI Chat (cl...

### ISSUE THREAD

**Issue by ofuochi** [Codium-ai/codiumai-jetbrains-release#177]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
com.intellij.util.IncorrectOperationException: Sorry but parent: CodiumAI Chat (class com.intellij.openapi.util.Disposer$2) has already been disposed (see the cause for stacktrace) so the child: Animator 'Loading' @1568948327 (stopped) (class com.intellij.openapi.ui.LoadingLayerAnimator) will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:43)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:161)
	at com.intellij.openapi.ui.LoadingDecorator.<init>(LoadingDecorator.kt:76)
	at com.intellij.openapi.ui.LoadingDecorator.<init>(LoadingDecorator.kt:26)
	at com.intellij.ui.components.JBLoadingPanel._init_$lambda$0(JBLoadingPanel.kt:27)
	at com.intellij.ui.components.JBLoadingPanel.<init>(JBLoadingPanel.kt:34)
	at com.intellij.ui.components.JBLoadingPanel.<init>(JBLoadingPanel.kt:25)
	at com.intellij.ui.components.JBLoadingPanel.<init>(JBLoadingPanel.kt:25)
	at ai.codium.ui.chat.CodiumChatToolWindow.determinePrePrPanelContent(CodiumChatToolWindow.kt:70)
	at ai.codium.ui.chat.CodiumChatToolWindow.access$determinePrePrPanelContent(CodiumChatToolWindow.kt:32)
	at ai.codium.ui.chat.CodiumChatToolWindow$initContents$1.invoke(CodiumChatToolWindow.kt:113)
	at ai.codium.ui.chat.CodiumChatToolWindow$initContents$1.invoke(CodiumChatToolWindow.kt:105)
	at ai.codium.CodiumLoginHelperKt$runRefreshTokenBackgroundCheck$1.run(CodiumLoginHelper.kt:108)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:484)
	at com.intellij.codeWithMe.ClientId$Companion.decorateFunction$lambda$8(ClientId.kt:383)
	at com.intellij.codeWithMe.ClientId$Companion.decorateFunction$lambda$8(ClientId.kt:383)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

# Other Information
```
=== About ===
Build version: JetBrains Rider 2023.3.3 Build: #RD-233.14015.60 January 18, 2024
Theme: Visual Studio Night
JRE: 17.0.9+7-b1087.11, JetBrains s.r.o.
JVM: 17.0.9+7-b1087.11, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 10.0 (amd64)

=== Plugins ===
Custom plugins: [Kubernetes (233.14015.29), SpecFlow for Rider (1.23.6), Ideolog (222.3.1.0), Terraform and HCL (233.13135.65), Atom Material Icons (94.1.0), AWS Toolkit - Amazon Q, CodeWhisperer, and more (2.4-233), CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.7.15), Azure Toolkit for Rider (3.50.0.1755-2023.3), React Buddy (233.13135.65), Heap Allocations Viewer (2023.3.0)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Fixed in 0.7.16
