### ISSUE TITLE
[0.7.16][PHPSTORM 2023.3.2] java.lang.RuntimeException: Cannot invoke (class=, method=selectionChanged, topic=FileEdi...

### ISSUE THREAD

**Issue by Hoshimxon** [Codium-ai/codiumai-jetbrains-release#178]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.RuntimeException: Cannot invoke (class=, method=selectionChanged, topic=FileEditorManagerListener)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:677)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:423)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:402)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:461)
	at jdk.proxy2/jdk.proxy2.$Proxy44.selectionChanged(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.fireSelectionChanged(FileEditorManagerImpl.kt:1754)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.access$fireSelectionChanged(FileEditorManagerImpl.kt:126)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$1$1$1.invoke(FileEditorManagerImpl.kt:240)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$1$1$1.invoke(FileEditorManagerImpl.kt:238)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:321)
	at com.intellij.openapi.progress.CoroutinesKt.access$blockingContextInner(coroutines.kt:1)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invokeSuspend(coroutines.kt:198)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:197)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$1$1.invokeSuspend(FileEditorManagerImpl.kt:238)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.intellij.openapi.application.impl.DispatchedRunnable.run(DispatchedRunnable.kt:43)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1436)
	at com.intellij.openapi.application.im

<TRIMMED STACKTRACE>

tToolwindowContent(CodiumStructureViewToolWindowFactory.kt:10)
	at ai.codium.ui.structureview.CodiumStructureViewToolWindowFactory$createToolWindowContent$1.selectionChanged(CodiumStructureViewToolWindowFactory.kt:29)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:700)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:660)
	... 61 more
	Suppressed: java.lang.RuntimeException: Cannot invoke (class=, method=selectionChanged, topic=FileEditorManagerListener)
		... 89 more
	Caused by: com.intellij.util.IncorrectOperationException: Sorry but parent: ai.codium.ui.chat.codeAssist.CodiumCodeAssistPanel[,0,0,632x966,invalid,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=] (class ai.codium.ui.chat.codeAssist.CodiumCodeAssistPanel) has already been disposed (see the cause for stacktrace) so the child: newDisposable (class com.intellij.openapi.util.Disposer$1) will never be disposed
		at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:43)
		at com.intellij.openapi.util.Disposer.register(Disposer.java:161)
		at com.intellij.openapi.util.Disposer.newDisposable(Disposer.java:125)
		at ai.codium.ui.chat.codeAssist.CodiumCodeAssistPanel.resetDocumentListener(CodiumCodeAssistPanel.kt:219)
		at ai.codium.ui.chat.codeAssist.CodiumCodeAssistPanel.access$resetDocumentListener(CodiumCodeAssistPanel.kt:53)
		at ai.codium.ui.chat.codeAssist.CodiumCodeAssistPanel$initContextPanel$1.selectionChanged(CodiumCodeAssistPanel.kt:115)
		at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:700)
		at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:660)
		... 88 more
Caused by: com.intellij.util.IncorrectOperationException: Sorry but parent: ai.codium.ui.chat.codeAssist.CodiumCodeAssistPanel[,0,0,632x966,invalid,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=] (class ai.codium.ui.chat.codeAssist.CodiumCodeAssistPanel) has already been disposed (see the cause for stacktrace) so the child: newDisposable (class com.intellij.openapi.util.Disposer$1) will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:43)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:161)
	at com.intellij.openapi.util.Disposer.newDisposable(Disposer.java:125)
	at ai.codium.ui.chat.codeAssist.CodiumCodeAssistPanel.resetDocumentListener(CodiumCodeAssistPanel.kt:219)
	at ai.codium.ui.chat.codeAssist.CodiumCodeAssistPanel.access$resetDocumentListener(CodiumCodeAssistPanel.kt:53)
	at ai.codium.ui.chat.codeAssist.CodiumCodeAssistPanel$initContextPanel$1.selectionChanged(CodiumCodeAssistPanel.kt:115)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:700)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:660)
	... 88 more

```

# Other Information
```
=== About ===
Build version: PhpStorm 2023.3.2 Build: #PS-233.13135.108 December 21, 2023
Theme: Dark
JRE: 17.0.9+7-b1087.9, JetBrains s.r.o.
JVM: 17.0.9+7-b1087.9, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [Codiumate - Code, test and review with confidence - by CodiumAI (0.7.16)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Fixed in upcoming 0.7.17
