### ISSUE TITLE
[0.7.16][PHPSTORM 2023.3.2] java.lang.ClassCastException: class com.intellij.lang.javascript.psi.impl.JSFunctionCache...

### ISSUE THREAD

**Issue by Dual-Ice** [Codium-ai/codiumai-jetbrains-release#179]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.ClassCastException: class com.intellij.lang.javascript.psi.impl.JSFunctionCachedData cannot be cast to class com.intellij.lang.javascript.index.gist.JSVariableBaseData (com.intellij.lang.javascript.psi.impl.JSFunctionCachedData and com.intellij.lang.javascript.index.gist.JSVariableBaseData are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @674ced13)
	at com.intellij.lang.javascript.index.gist.JSStubElementGist.getData(JSStubElementGist.java:116)
	at com.intellij.lang.javascript.psi.impl.JSCachingTypeOwner.lambda$static$0(JSCachingTypeOwner.java:32)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:31)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:21)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:82)
	at com.intellij.lang.javascript.psi.impl.JSStubElementImpl.getCachedValueStubBuildOptimized(JSStubElementImpl.java:364)
	at com.intellij.lang.javascript.psi.impl.JSCachingTypeOwner.getJSType(JSCachingTypeOwner.java:90)
	at com.intellij.lang.typescript.psi.TypeScriptPsiUtil.getThisParameterType(TypeScriptPsiUtil.java:361)
	at com.intellij.lang.javascript.psi.ecma6.impl.TypeScriptFunctionBaseImpl.getExplicitThisType(TypeScriptFunctionBaseImpl.java:94)
	at com.intellij.lang.javascript.psi.ecma6.impl.TypeScriptFunctionTypeImpl.getExplicitThisType(TypeScriptFunctionTypeImpl.java:27)
	at com.intellij.lang.javascript.psi.types.TypeScriptTypeParser.buildFunctionTypeImpl(TypeScriptTypeParser.java:138)
	at com.intellij.lang.javascript.psi.types.TypeScriptTypeParser.buildFunctionTypeImpl(TypeScriptTypeParser.java:123)
	at com.intellij.lang.javascript.psi.types.TypeScriptTypeParser.lambda$buildFunctionType$2(TypeScriptTypeParser.java:98)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.ja

<TRIMMED STACKTRACE>

j.openapi.project.DumbService.runReadActionInSmartMode(DumbService.kt:122)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.kt:77)
	at ai.codium.elements.CutElement$context$2.invoke(CutElement.kt:41)
	at ai.codium.elements.CutElement$context$2.invoke(CutElement.kt:40)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at ai.codium.elements.CutElement.getContext(CutElement.kt:40)
	at ai.codium.AnalysisManagerKt$runAnalysis$2$1.run(AnalysisManager.kt:112)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:484)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

# Other Information
```
=== About ===
Build version: PhpStorm 2023.3.2 Build: #PS-233.13135.108 December 21, 2023
Theme: Dark
JRE: 17.0.9+7-b1087.9, JetBrains s.r.o.
JVM: 17.0.9+7-b1087.9, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [.env files support (2023.3), PHP Annotations (9.4.0), GitToolBox (500.1.9+222), Rainbow Brackets (2024.1.0-233), GitHub Copilot (1.4.13.4415), Codiumate - Code, test and review with confidence - by CodiumAI (0.7.16)]
Disabled plugins:[Angular and AngularJS (233.13135.108), Next.js Support (233.13135.108), Vagrant (233.13135.108), Quokka (1.0.430), GitLab (233.13135.108), Code With Me (233.13135.108), Wallaby (1.0.284), Nuxt.js (2.0.10), Joomla! (233.13135.108), Drupal (233.13135.108), Perforce Helix Core (233.13135.108), AI Assistant (233.14015.106), Subversion (233.13135.108), WordPress (233.13135.108), Mercurial (233.13135.108), CodeGlance3 (2.1.1-2021.1.3)]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Seems like IDE internal glitch... will investigate if any workaround possible...
