### ISSUE TITLE
[Exception][PyCharm 2023.1] java.lang.NoClassDefFoundError: okhttp3/internal/Util

### ISSUE THREAD

**Issue by ka-suvorov** [Codium-ai/codiumai-jetbrains-release#18]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.NoClassDefFoundError: okhttp3/internal/Util
	at ai.codium.CodiumInlayProviderBase.addCodiumTestsGenerationInlay(CodiumInlayProviderBase.kt:101)
	at ai.codium.python.CodiumPythonInlayProvider.access$addCodiumTestsGenerationInlay(CodiumPythonInlayProvider.kt:17)
	at ai.codium.python.CodiumPythonInlayProvider$getCollectorFor$1.collect(CodiumPythonInlayProvider.kt:49)
	at com.intellij.codeInsight.hints.CollectorWithSettings.collectHints(InlayHintsUtils.kt:90)
	at com.intellij.codeInsight.hints.InlayHintsPass.doCollectInformation$lambda$0(InlayHintsPass.kt:46)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$2(JobLauncherImpl.java:137)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$3(JobLauncherImpl.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at com.intellij.concurrency.JobLauncherImpl.processImmediatelyIfTooFew(JobLauncherImpl.java:144)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:44)
	at com.intellij.codeInsight.hints.InlayHintsPass.doCollectInformation(InlayHintsPass.kt:37)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:374)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:373)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:349)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:187)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:347)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ClassNotFoundException: okhttp3.internal.Util PluginClassLoader(plugin=PluginDescriptor(name=CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4, id=codiumai.codiumai, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\PyCharmCE2023.1\plugins\codium-ai-plugin-0.4.11.jar, version=0.4.11, package=null, isBundled=false), packagePrefix=null, instanceId=60, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 36 more

```

# Other Information
```
=== About ===
Build version: PyCharm 2023.1 Build: #PC-231.8109.197 March 29, 2023
Theme: IntelliJ Light
JRE: 17.0.6+10-b829.5, JetBrains s.r.o.
JVM: 17.0.6+10-b829.5, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [Djaneiro for PyCharm (1.2), ChatGPT (2.1.13-222.231), CSV Editor (3.1.0-231), Spec & Math Symbols (1.9.0), Ini (231.8109.217), SnakeCharm (2023.1.1), .env files support (2023.1), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.4.11), GitHub Markdown Emojis (1.2.2), ChatGPT Tool (1.1.1)]
Disabled plugins:[Code With Me (231.8109.197)]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/FXPftSiw) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Hi @ka-suvorov ! Just for curiosity, you installed plugin as jar (extracted from zip) and that was the case for missing _okhttp_ dependency, right?
