### ISSUE TITLE
[0.7.16][INTELLIJ IDEA IU 2023.1] java.lang.NullPointerException: Cannot invoke "java.awt.FontMetrics.getFont()" beca...

### ISSUE THREAD

**Issue by rotemchen-hibob** [Codium-ai/codiumai-jetbrains-release#180]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.NullPointerException: Cannot invoke "java.awt.FontMetrics.getFont()" because "fm" is null
	at java.desktop/sun.swing.SwingUtilities2.getFontCharsWidth(SwingUtilities2.java:922)
	at java.desktop/sun.swing.SwingUtilities2.getFontCharWidth(SwingUtilities2.java:911)
	at java.desktop/javax.swing.text.Utilities.getTabbedTextOffset(Utilities.java:542)
	at java.desktop/javax.swing.text.GlyphPainter1.getBoundedPosition(GlyphPainter1.java:217)
	at java.desktop/javax.swing.text.GlyphView.getBreakWeight(GlyphView.java:717)
	at java.desktop/javax.swing.text.html.InlineView.getBreakWeight(InlineView.java:156)
	at java.desktop/javax.swing.text.ParagraphView.findEdgeSpan(ParagraphView.java:754)
	at java.desktop/javax.swing.text.ParagraphView.findEdgeSpan(ParagraphView.java:761)
	at java.desktop/javax.swing.text.ParagraphView.findEdgeSpan(ParagraphView.java:761)
	at java.desktop/javax.swing.text.ParagraphView.findEdgeSpan(ParagraphView.java:761)
	at java.desktop/javax.swing.text.ParagraphView.findEdgeSpan(ParagraphView.java:761)
	at java.desktop/javax.swing.text.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:722)
	at java.desktop/javax.swing.text.html.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:162)
	at java.desktop/javax.swing.text.BoxView.checkRequests(BoxView.java:936)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:344)
	at java.desktop/javax.swing.text.BoxView.layout(BoxView.java:709)
	at java.desktop/javax.swing.text.FlowView.layout(FlowView.java:228)
	at java.desktop/javax.swing.text.BoxView.setSize(BoxView.java:398)
	at java.desktop/javax.swing.text.BoxView.updateChildSizes(BoxView.java:367)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:349)
	at java.desktop/javax.swing.text.BoxView.layout(BoxView.java:709)
	at java.desktop/javax.swing.text.BoxView.setSize(BoxView.java:398)
	at java.desktop/javax.swing.text.BoxView.updateChildSizes(BoxView.java:367)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:349)
	at java.desktop/javax.swing.text.BoxView.layout(BoxView.java:709)
	at java.desktop/javax.swing.text.BoxView.setSize(BoxView.java:398)
	at java.desktop/javax.swing.plaf.basic.BasicHTML$Renderer.setSize(BasicHTML.java:674)
	at java.desktop/javax.swing.plaf.basic.BasicHTML$Renderer.<init>(BasicHTML.java:448)
	at java.desktop/javax.swing.plaf.basic.BasicHTML.createHTMLView(BasicHTML.java:91)
	at java.desktop/javax.swing.plaf.basic.BasicHTML.updateRenderer(BasicHTML.java:238)
	at java.desktop/javax.swing.plaf.basic.BasicLabelUI.propertyChange(BasicLabelUI.java:493)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8758)
	at java.desktop/javax.swing.JLabel.setText(JLabel.java:341)
	at ai.codium.ui.chat.CodiumPrePREmptyForm.<init>(CodiumPrePREmptyForm.java:10)
	at ai.codium.ui.chat.CodiumChatToolWindow.determinePrePrPanelContent(CodiumChatToolWindow.kt:71)
	at ai.codium.ui.chat.CodiumChatToolWindow.access$determinePrePrPanelContent(CodiumChatToolWindow.kt:31)
	at ai.codium.ui.chat.CodiumChatToolWindow$initContents$1.invoke(CodiumChatToolWindow.kt:112)
	at ai.codium.ui.chat.CodiumChatToolWindow$initContents$1.invoke(CodiumChatToolWindow.kt:105)
	at ai.codium.CodiumLoginHelperKt$runRefreshTokenBackgroundCheck$1.run(CodiumLoginHelper.kt:108)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2023.1 Build: #IU-231.8109.175 March 28, 2023
Theme: Darcula
JRE: 17.0.6+10-b829.5, JetBrains s.r.o.
JVM: 17.0.6+10-b829.5, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 14.2.1 (aarch64)

=== Plugins ===
Custom plugins: [Scala (2023.1.23), Kotlin (231-1.9.22-release-704-IJ8109.175), Codiumate - Code, test and review with confidence - by CodiumAI (0.7.16), Raftt (10.10.1-213)]
Disabled plugins:[Sass (231.8109.175), Ktor (231.8109.175), Android Design Tools (231.8109.175), Android (2022.1.1.231.8109.175)]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Seems like IDE internal glitch... will investigate if any workaround possible...

**Comment by YasserDbeis** [comment]
Any updates on this?

**Comment by ArtsiomCh** [comment]
@YasserDbeis What plugin version?

**Comment by YasserDbeis** [comment]
Nevermind, I thought this was an issue on the main intellij repository because I am getting it as well with the plugin I am developing (I am not using this plugin). Apologies!

**Comment by YasserDbeis** [comment]
DId you end up figuring out whether this was an intellij platform issue or not btw?
