### ISSUE TITLE
[0.7.15][INTELLIJ IDEA IU 2023.3.2] Unhandled exception in [CoroutineName(com.intellij.openapi.vcs.impl.VcsInitializa...

### ISSUE THREAD

**Issue by anto-metica** [Codium-ai/codiumai-jetbrains-release#182]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.NullPointerException: Cannot invoke "java.awt.FontMetrics.getFont()" because "fm" is null
	at java.desktop/sun.swing.SwingUtilities2.getFontCharsWidth(SwingUtilities2.java:922)
	at java.desktop/sun.swing.SwingUtilities2.getFontCharWidth(SwingUtilities2.java:911)
	at java.desktop/javax.swing.text.Utilities.getTabbedTextOffset(Utilities.java:542)
	at java.desktop/javax.swing.text.GlyphPainter1.getBoundedPosition(GlyphPainter1.java:217)
	at java.desktop/javax.swing.text.GlyphView.getBreakWeight(GlyphView.java:717)
	at java.desktop/javax.swing.text.html.InlineView.getBreakWeight(InlineView.java:156)
	at java.desktop/javax.swing.text.ParagraphView.findEdgeSpan(ParagraphView.java:754)
	at java.desktop/javax.swing.text.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:722)
	at java.desktop/javax.swing.text.html.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:162)
	at java.desktop/javax.swing.text.BoxView.checkRequests(BoxView.java:936)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:344)
	at java.desktop/javax.swing.text.BoxView.layout(BoxView.java:709)
	at java.desktop/javax.swing.text.FlowView.layout(FlowView.java:228)
	at java.desktop/javax.swing.text.BoxView.setSize(BoxView.java:398)
	at java.desktop/javax.swing.text.BoxView.updateChildSizes(BoxView.java:367)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:349)
	at java.desktop/javax.swing.text.BoxView.layout(BoxView.java:709)
	at java.desktop/javax.swing.text.BoxView.setSize(BoxView.java:398)
	at java.desktop/javax.swing.text.BoxView.updateChildSizes(BoxView.java:367)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:349)
	at java.desktop/javax.swing.text.BoxView.layout(BoxView.java:709)
	at java.desktop/javax.swing.text.BoxView.setSize(BoxView.java:398)
	at java.desktop/javax.swing.text.BoxView.updateChildSizes(BoxView.java:367)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:349)
	at java.desktop/javax.swing.text.BoxView.layout(BoxView.java:709)
	at java.desktop/javax.swing.text.BoxView.setSize(BoxView.java:398)
	at java.desktop/javax.swing.plaf.basic.BasicHTML$Renderer.setSize(BasicHTML.java:697)
	at java.desktop/javax.swing.plaf.basic.BasicHTML$Renderer.<init>(BasicHTML.java:471)
	at java.desktop/javax.swing.plaf.basic.BasicHTML.createHTMLView(BasicHTML.java:93)
	at java.desktop/javax.swing.plaf.basic.BasicHTML.updateRenderer(BasicHTML.java:240)
	at java.desktop/javax.swing.plaf.basic.BasicLabelUI.propertyChange(BasicLabelUI.java:493)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChange

<TRIMMED STACKTRACE>

pertyChange(PropertyChangeSupport.java:268)
	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8759)
	at java.desktop/javax.swing.JLabel.setText(JLabel.java:341)
	at com.intellij.ui.components.JBLabel.setText(JBLabel.java:170)
	at com.intellij.openapi.ui.panel.ComponentPanelBuilder.setCommentText(ComponentPanelBuilder.java:358)
	at com.intellij.openapi.ui.panel.ComponentPanelBuilder.createCommentComponent(ComponentPanelBuilder.java:318)
	at com.intellij.openapi.ui.panel.ComponentPanelBuilder$ComponentPanelImpl.<init>(ComponentPanelBuilder.java:395)
	at com.intellij.openapi.ui.panel.ComponentPanelBuilder.addToPanel(ComponentPanelBuilder.java:229)
	at com.intellij.openapi.ui.panel.ComponentPanelBuilder.createPanel(ComponentPanelBuilder.java:212)
	at ai.codium.ui.chat.prePR.CodiumPrePRPanel.<init>(CodiumPrePRPanel.kt:46)
	at ai.codium.ui.chat.CodiumChatToolWindow.determinePrePrPanelContent$lambda$1(CodiumChatToolWindow.kt:97)
	at com.intellij.openapi.vcs.impl.VcsInitialization$add$1$1.invoke(VcsInitialization.kt:90)
	at com.intellij.openapi.vcs.impl.VcsInitialization$add$1$1.invoke(VcsInitialization.kt:89)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:321)
	at com.intellij.openapi.progress.CoroutinesKt.access$blockingContextInner(coroutines.kt:1)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invokeSuspend(coroutines.kt:198)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:197)
	at com.intellij.openapi.vcs.impl.VcsInitialization$add$1.invokeSuspend(VcsInitialization.kt:89)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(com.intellij.openapi.vcs.impl.VcsInitialization), StandaloneCoroutine{Cancelled}@7012f514, Dispatchers.Default]

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2023.3.2 Build: #IU-233.13135.103 December 20, 2023
Theme: Light
JRE: 17.0.9+7-b1087.9, JetBrains s.r.o.
JVM: 17.0.9+7-b1087.9, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 14.2.1 (aarch64)

=== Plugins ===
Custom plugins: [AWS Toolkit - Amazon Q, CodeWhisperer, and more (2.4-233), Terraform and HCL (233.13135.65), Archive Browser (0.32), .ignore (4.5.2), Big Data File Viewer (233.11799.267), Zeppelin (233.13135.65), DynamoDB (2023.3.1-233), GitHub Copilot (1.4.12.4386), Package Search (233.11799.196), AI Assistant (233.13135.116), Python (233.13135.103), JSON To Kotlin Class (JsonToKotlinClass) (3.7.4), Remote File Systems (233.13135.103), Big Data Tools Core (233.13135.103), Kafka (233.13135.103), Metastore Core (233.13135.65), UUID Generator (4.5.1), Flink (233.13135.103), Codeium: AI Autocomplete and Chat for Python, JS, TS, Java, Go… (1.6.20), Big Data Tools (233.13135.65), CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.7.15), Spark (233.13135.103)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Seems like IDE internal glitch... will investigate if any workaround possible...

**Comment by YasserDbeis** [comment]
Any update on this? 

received this error with
IntelliJ IDEA 2024.2.1 (Community Edition)
Build #IC-242.21829.142, built on August 28, 2024
Runtime version: 21.0.3+13-b509.11 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.7.1
Kotlin analyzer version: 2.0.20-ij242-31
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
[REDACTED]
Kotlin: 242.21829.142-IJ
