### ISSUE TITLE
[Exception][WebStorm 2023.1] java.lang.IllegalArgumentException: Width (1) and height (0) cannot be <= 0

### ISSUE THREAD

**Issue by mjsilva** [Codium-ai/codiumai-jetbrains-release#19]
# User Description
![web-demo – CtbViewer tsx 2023-04-13 at 9 48 00 am](https://user-images.githubusercontent.com/158554/231610271-159c50e4-890d-4a05-83b0-c4cbca4ad36d.jpg)

# Stack Trace
```
java.lang.IllegalArgumentException: Width (1) and height (0) cannot be <= 0
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
	at com.intellij.ui.svg.SvgTranscoderKt.render(SvgTranscoder.kt:263)
	at com.intellij.ui.svg.SvgTranscoderKt.access$render(SvgTranscoder.kt:1)
	at com.intellij.ui.svg.SvgTranscoder$Companion.createImage(SvgTranscoder.kt:100)
	at com.intellij.ui.svg.SvgTranscoder$Companion.createImage$default(SvgTranscoder.kt:75)
	at com.intellij.util.SVGLoaderKt.loadAndCache(SVGLoader.kt:385)
	at com.intellij.util.SVGLoaderKt.access$loadAndCache(SVGLoader.kt:1)
	at com.intellij.util.SVGLoader.loadFromClassResource(SVGLoader.kt:109)
	at com.intellij.util.ImageLoaderKt.loadByDescriptorWithoutCache(ImageLoader.kt:580)
	at com.intellij.util.ImageLoaderKt.loadByDescriptor(ImageLoader.kt:542)
	at com.intellij.util.ImageLoaderKt.access$loadByDescriptor(ImageLoader.kt:1)
	at com.intellij.util.ImageLoader.loadImage(ImageLoader.kt:86)
	at com.intellij.openapi.util.ImageDataByUrlLoader.loadImage(ImageDataByUrlLoader.java:87)
	at com.intellij.openapi.util.CachedImageIcon.loadImage$intellij_platform_util_ui(CachedImageIcon.kt:269)
	at com.intellij.openapi.util.ScaledIconCache.getOrScaleIcon(ScaledIconCache.kt:46)
	at com.intellij.openapi.util.CachedImageIcon.getRealIcon$intellij_platform_util_ui(CachedImageIcon.kt:151)
	at com.intellij.openapi.util.CachedImageIcon.getIconWidth(CachedImageIcon.kt:104)
	at java.desktop/javax.swing.SwingUtilities.layoutCompoundLabelImpl(SwingUtilities.java:1091)
	at java.desktop/javax.swing.SwingUtilities.layoutCompoundLabel(SwingUtilities.java:1004)
	at java.desktop/javax.swing.plaf.basic.BasicLabelUI.layoutCL(BasicLabelUI.java:108)
	at com.intellij.ide.ui.laf.darcula.ui.DarculaLabelUI.layoutCL(DarculaLabelUI.java:94)
	at java.desktop/javax.swing.plaf.basic.BasicLabelUI.getPreferredSize(BasicLabelUI.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicLabelUI.getMinimumSize(BasicLabelUI.java:280)
	at com.intellij.ide.ui.laf.darcula.ui.DarculaLabelUI.getMinimumSize(DarculaLabelUI.java:46)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1801)
	at com.intellij.uiDesigner.core.Util.getMinimumSize(Util.java:13)
	at com.intellij.uiDesigner.core.DimensionInfo.getMinimumSize(DimensionInfo.java:238)
	at com.intellij.uiDesigner.core.HorizontalInfo.getMinimumWidth(HorizontalInfo.java:40)
	at com.intellij.uiDesigner.core.GridLayoutManager.getMinOrPrefSizes(GridLayoutManager.java:640)
	at com.intellij.uiDesigner.core.GridLayoutManager.getPrefSizes(GridLayoutManager.java:627)
	at com.intellij.uiDesigner.core.GridLayoutManager.preferredLayoutSize(GridLayoutManager.java:271)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1826)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/javax.swing.JCo

<TRIMMED STACKTRACE>

ionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:570)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

# Other Information
```
=== About ===
Build version: WebStorm 2023.1 Build: #WS-231.8109.174 March 28, 2023
Theme: Dark
JRE: 17.0.6+10-b829.5, JetBrains s.r.o.
JVM: 17.0.6+10-b829.5, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.2.1 (aarch64)

=== Plugins ===
Custom plugins: [Tailwind Formatter (2.0.7), GitHub Copilot (1.2.5.2507), .env files support (2023.1), Prisma ORM (231.8109.91), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.4.11)]
Disabled plugins:[]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/7yrfjUKV) by [Unito](https://www.unito.io)

**Comment by almog-lv** [comment]
Hey @mjsilva can you please update to the latest version (0.5) and see if it is reproduced?

**Comment by mjsilva** [comment]
no more errors on the new version. Thanks!
