### ISSUE TITLE
[0.7.10][INTELLIJ IDEA IC 2022.3.3] java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3

### ISSUE THREAD

**Issue by vinayM165** [Codium-ai/codiumai-jetbrains-release#192]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at com.intellij.credentialStore.kdbx.KdbxHeader.readKdbxHeader(KdbxHeader.kt:198)
	at com.intellij.credentialStore.kdbx.KdbxHeader.<init>(KdbxHeader.kt:83)
	at com.intellij.credentialStore.kdbx.KdbxKt.readKeePassDatabase(kdbx.kt:25)
	at com.intellij.credentialStore.kdbx.KdbxKt.loadKdbx(kdbx.kt:21)
	at com.intellij.credentialStore.keePass.KeePassCredentialStore.<init>(KeePassCredentialStore.kt:39)
	at com.intellij.credentialStore.keePass.KeePassCredentialStore.<init>(KeePassCredentialStore.kt:30)
	at com.intellij.ide.passwordSafe.impl.PasswordSafeImplKt.computeProvider(PasswordSafeImpl.kt:189)
	at com.intellij.ide.passwordSafe.impl.PasswordSafeImplKt.access$computeProvider(PasswordSafeImpl.kt:1)
	at com.intellij.ide.passwordSafe.impl.BasePasswordSafe$_currentProvider$1.invoke(PasswordSafeImpl.kt:38)
	at com.intellij.ide.passwordSafe.impl.BasePasswordSafe$_currentProvider$1.invoke(PasswordSafeImpl.kt:38)
	at com.intellij.util.concurrency.SynchronizedClearableLazy._get_value_$lambda$1$lambda$0(SynchronizedClearableLazy.kt:38)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at com.intellij.util.concurrency.SynchronizedClearableLazy.getValue(SynchronizedClearableLazy.kt:37)
	at com.intellij.ide.passwordSafe.impl.BasePasswordSafe.getCurrentProvider(PasswordSafeImpl.kt:44)
	at com.intellij.ide.passwordSafe.impl.BasePasswordSafe.get(PasswordSafeImpl.kt:91)
	at com.intellij.credentialStore.CredentialStore.getPassword(CredentialStore.java:30)
	at ai.codium.CodiumCredentialStorageKt.getCodiumRefreshToken(CodiumCredentialStorage.kt:16)
	at ai.codium.net.CodiumLoginManager.getRefreshToken(CodiumLoginManager.kt:21)
	at ai.codium.net.CodiumNetworkService.getIdToken(CodiumNetworkService.kt:253)
	at ai.codium.net.CodiumNetworkService.getUserData(CodiumNetworkService.kt:263)
	at ai.codium.UserDataManager$Companion.initUserData(UserDataManager.kt:28)
	at ai.codium.UserDataManager$Companion.initUserData$default(UserDataManager.kt:27)
	at ai.codium.CodiumInitialStartupActivity.runActivity(CodiumInitialStartupActivity.kt:16)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:340)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runActivityAndMeasureDuration(StartupManagerImpl.kt:66)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$2$2$1.invoke(StartupManagerImpl.kt:279)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$2$2$1.invoke(StartupManagerImpl.kt:278)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob$lambda$0(cancellation.kt:17)
	at com.intellij.openapi.progress.Cancellation.withCurrentJob(Cancellation.java:60)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob(cancellation.kt:17)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:142)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:278)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:66)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runStartupActivities$2.invokeSuspend(StartupManagerImpl.kt:184)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2022.3.3 Build: #IC-223.8836.41 March 10, 2023
Theme: Darcula
JRE: 17.0.6+1-b653.34, JetBrains s.r.o.
JVM: 17.0.6+1-b653.34, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11 10.0 (amd64)

=== Plugins ===
Custom plugins: [Spring Boot Assistant (222.17.3), CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.7.10), Docker (223.8836.46)]
Disabled plugins:[Spring Boot Helper (2022.4.3)]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Seems like an issue inside `KeePassCredentialStore`
Do you see it often/always? Or it was one time glitch?
Was you able to login/signing?
