### ISSUE TITLE
[0.7.20][INTELLIJ IDEA IU 2023.3.4] java.lang.Throwable: All stub element types should be created before index initia...

### ISSUE THREAD

**Issue by akobirabduganiev** [Codium-ai/codiumai-jetbrains-release#193]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable: All stub element types should be created before index initialization is complete.
Please add the class org.jetbrains.kotlin.psi.stubs.elements.KtClassElementType with external ID kotlin.CLASS containing stub element type constants to "stubElementTypeHolder" extension.
Registered extensions: [com.intellij.util.xml.stubs.DomElementTypeHolder, com.intellij.protobuf.lang.stub.type.PbStubElementTypes, com.intellij.psi.css.impl.CssStubElementTypes, org.jetbrains.plugins.less.LessStubElementTypes, org.intellij.plugins.postcss.PostCssStubElementTypes, org.jetbrains.plugins.scss.ScssStubElementTypes, org.jetbrains.plugins.sass.psi.SassStubElementTypes, org.intellij.plugins.markdown.lang.MarkdownStubElementTypes, com.intellij.lang.properties.parsing.PropertiesElementTypes, com.intellij.psi.impl.java.stubs.JavaStubElementTypes, org.jetbrains.plugins.groovy.lang.parser.GroovyStubElementTypes, org.jetbrains.plugins.groovy.lang.parser.GroovyEmptyStubElementTypes, org.jetbrains.kotlin.psi.stubs.elements.KtStubElementTypes, com.intellij.lang.javascript.JSStubElementTypes, com.intellij.lang.typescript.TypeScriptStubElementTypes, com.intellij.lang.javascript.flow.FlowJSStubElementTypes, com.intellij.lang.javascript.frameworks.jquery.JQueryCssStubElementTypes, com.intellij.lang.actionscript.ActionScriptStubElementTypes, com.intellij.lang.ecmascript6.ES6StubElementTypes, org.jetbrains.vuejs.lang.expr.parser.VueJSStubElementTypes, org.jetbrains.vuejs.lang.html.parser.VueStubElementTypes, com.intellij.httpClient.js.http.request.language.HttpClientJSEmbeddedContent, com.intellij.sql.psi.SqlCompositeElementTypes, com.intellij.sql.dialects.sql92.Sql92ElementTypes$Stubs, com.intellij.sql.dialects.cassandra.CassElementTypes$Stubs, com.intellij.sql.dialects.clickhouse.CHouseElementTypes$Stubs, com.intellij.sql.dialects.db2.Db2ElementTypes$Stubs, com.intellij.sql.dialects.derby.DerbyElementTypes$Stubs, com.intellij.sql.dialects.exasol.ExaElementTypes$Stubs, com.intellij.sql.dialects.greenplum.GPlumElementTypes$Stubs, com.intellij.sql.dialects.h2.H2ElementTypes$Stubs, com.intellij.sql.dialects.hive.HiveElementTypes$Stubs, com.intellij.sql.dialects.hsql.HsqlElementTypes$Stubs, com.intellij.sql.dialects.mssql.MsElementTypes$Stubs, com.intellij.sql.dialects.mysql.MysqlElementTypes$Stubs, com.intellij.sql.dialects.oracle.OraElementTypes$Stubs, com.intellij.sql.dialects.oraplus.OraPlusElementTypes$Stubs, com.intellij.sql.dialects.postgres.PgElementTypes$Stubs, com.intellij.sql.dialects.redshift.RsElementTypes$Stubs, com.intellij.sql.dialects.snowflake.SFlakeElementTypes$Stubs, com.intellij.sql.dialects.sqlite.SqliteElementTypes$Stubs, com.intellij.sql.dialects.sybase.AseElementTypes$Stubs, com.intellij.sql.dialects.vertica.VertElementTypes$Stubs, com.intellij.sql.dial

<TRIMMED STACKTRACE>

actory$Companion.hasClassMethod$default(LanguageServiceFactory.kt:10)
	at ai.codium.language.LanguageServiceFactory.<clinit>(LanguageServiceFactory.kt:25)
	at ai.codium.UtilsKt.getLanguageService(Utils.kt:63)
	at ai.codium.CodiumInlayProvider.getCollectorFor(CodiumInlayProvider.kt:75)
	at ai.codium.CodiumInlayProvider.getCollectorFor(CodiumInlayProvider.kt:34)
	at com.intellij.codeInsight.hints.InlayHintsUtilsKt.getCollectorWrapperFor(InlayHintsUtils.kt:50)
	at com.intellij.codeInsight.daemon.impl.InlayHintsPassFactoryInternal.createHighlightingPass(InlayHintsPassFactoryInternal.kt:46)
	at com.intellij.codeInsight.daemon.impl.TextEditorHighlightingPassRegistrarImpl.instantiatePasses(TextEditorHighlightingPassRegistrarImpl.java:186)
	at com.intellij.codeInsight.daemon.impl.TextEditorBackgroundHighlighter.getPasses(TextEditorBackgroundHighlighter.kt:65)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$submitInBackground$25(DaemonCodeAnalyzerImpl.java:1163)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$submitInBackground$26(DaemonCodeAnalyzerImpl.java:1152)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.submitInBackground(DaemonCodeAnalyzerImpl.java:1149)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$queuePassesCreation$21(DaemonCodeAnalyzerImpl.java:1114)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:187)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2023.3.4 Build: #IU-233.14475.28 February 13, 2024
Theme: Dark
JRE: 17.0.10+1-b1087.17, JetBrains s.r.o.
JVM: 17.0.10+1-b1087.17, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [Translation (3.5.6), JetBrains Academy (2024.1-2023.3-882), Codiumate - Code, test and review with confidence - by CodiumAI (0.7.20), Spring WebSocket (233.11799.196), Jump to Line (0.1.15), .ignore (4.5.2), AWS Toolkit - Amazon Q, CodeWhisperer, and more (2.9-233), Grazie Pro (0.3.284), GitHub Copilot (1.4.15.4632), JPA Buddy (2023.4.1-233), Rainbow Brackets (2024.2.1), Resource Bundle Editor (233.11799.172), TeamCity (2023.11.147331), Jmix (2.1.3-233), Restful Fast Request - API Buddy (2024.1.2.1)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Seems like internal IDE bug as on that stage all IDE internal indexes/stubs should be already created... we'll investigate
