### ISSUE TITLE
[0.7.21][INTELLIJ IDEA IU 2023.3.4] provider: de.plushnikov.intellij.plugin.provider.LombokAugmentProvider@22b39ec3

### ISSUE THREAD

**Issue by TechnicalRhino** [Codium-ai/codiumai-jetbrains-release#196]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.IllegalArgumentException: recordId(6587188) is not yet allocated: allocated ids are all < 6543806
	at com.intellij.openapi.vfs.newvfs.persistent.dev.blobstorage.StreamlinedBlobStorageHelper.checkRecordIdExists(StreamlinedBlobStorageHelper.java:398)
	at com.intellij.openapi.vfs.newvfs.persistent.dev.blobstorage.StreamlinedBlobStorageOverMMappedFile.readRecord(StreamlinedBlobStorageOverMMappedFile.java:200)
	at com.intellij.openapi.vfs.newvfs.persistent.dev.blobstorage.StreamlinedBlobStorageHelper.readRecord(StreamlinedBlobStorageHelper.java:216)
	at com.intellij.openapi.vfs.newvfs.persistent.AttributesStorageOverBlobStorage.readAttributeValue(AttributesStorageOverBlobStorage.java:1026)
	at com.intellij.openapi.vfs.newvfs.persistent.AttributesStorageOverBlobStorage.readAttributeRaw(AttributesStorageOverBlobStorage.java:134)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSAttributeAccessor.readAttributeRaw(PersistentFSAttributeAccessor.java:72)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSTreeRawAccessor.listIds(PersistentFSTreeRawAccessor.java:91)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecordsImpl.listIds(FSRecordsImpl.java:680)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.listIds(FSRecords.java:210)
	at com.intellij.openapi.vfs.PlatformVirtualFileManager.listAllChildIds(PlatformVirtualFileManager.java:64)
	at com.intellij.openapi.module.impl.scopes.ModuleWithDependenciesScope.doExtractFilIdEnumeration(ModuleWithDependenciesScope.java:198)
	at com.intellij.openapi.module.impl.scopes.ModuleWithDependenciesScope.lambda$extractFileEnumeration$3(ModuleWithDependenciesScope.java:191)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.intellij.openapi.module.impl.scopes.ModuleWithDepend

<TRIMMED STACKTRACE>

DaemonCodeAnalyzerImpl.java:1163)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$submitInBackground$26(DaemonCodeAnalyzerImpl.java:1152)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.submitInBackground(DaemonCodeAnalyzerImpl.java:1149)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$queuePassesCreation$21(DaemonCodeAnalyzerImpl.java:1114)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:187)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2023.3.4 Build: #IU-233.14475.28 February 13, 2024
Theme: Dark
JRE: 17.0.10+1-b1087.17, JetBrains s.r.o.
JVM: 17.0.10+1-b1087.17, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 14.2.1 (aarch64)

=== Plugins ===
Custom plugins: [GitToolBox (500.1.11+222), Maven Dependency Helper (2.5), SonarLint (10.3.0.77475), Rainbow Brackets (2024.2.1), Gopher (2021.1), Emoji Support Plugin (3.1.0), Markdown Editor (2.0.5), Nord (0.13.0), Cucumber for Scala (2023.3.2), RoboPOJOGenerator (2.4.2), CommitPrefix (1.4.1), Grep Console (12.25.0-IJ2023.3), Scala (2023.3.27), Terraform and HCL (233.13135.65), SpotBugs (1.2.7), Solarized Themes (2.4.0), Run Configuration for TypeScript (2022.11.14-1), AsciiDoc (0.41.8), POJO to JSON (2.0.4), Maven Archetype Catalogs (1.4.0), Copy as Json (1.0.4), GitHub Copilot (1.4.19.4986), Database Navigator (3.4.3073.0), Randomness (3.2.0), Statistic (4.2.14), ChatGPT Integration (0.2.12-231), OpenAPI (Swagger) Editor (1.82), String Manipulation (9.12.0), CMD Support (1.0.5), DTO generator (V0.997), Python (233.14475.28), Zalando OpenAPI Editor (1.3.0), Nyan Progress Bar (1.15), Codiumate - Code, test and review with confidence - by CodiumAI (0.7.21), Toolset (2024.3.1), Regexp Tester (2.2.0), AceJump (3.8.18), JPA Buddy (2023.4.1-233), Atom Material Icons (94.1.0), Extra ToolWindow Colorful Icons (1.33.0), GraphQL (233.13135.65), Json2Pojo (1.1.0), Paste Images into Markdown (1.3.2), Json Parser (1.7.1), Kafka (233.13135.103), PlantUML Integration (7.7.0-IJ2023.2), Requirements (2022.4.1), Big Data Tools Core (233.14475.28), Ruby (233.14475.28), Nx Console (1.19.0), SequenceDiagram (3.0.8), Indent Rainbow (2.2.0), JPA Support (2.2.1), Nest (1.2.26), RestfulTool (1.4.5), Full Line Code Completion (233.14732), Hiberbee Theme (2024.2.28.2100), DGS (1.3.7), One Dark Theme (5.10.0), Spring Boot Helper (2023.1.0), AWS Toolkit - Amazon Q, CodeWhisperer, and more (2.10-233), GitLink (4.4.0), Cron Descriptor (1.5), GenerateAllSetter (2.8.4), JProfiler (19.9.3), New Relic CodeStream (15.3.0+531), .env files support (2024.1), CSV Editor (3.3.0-233), Dummy Text Generator (1.2.0), Flyway Migration Creation (2.1), Yet another emoji support (1.0.7), Jakarta EE: Web Services (JAX-WS) (233.13135.65), Native Debugging Support (233.14015.106), Live Edit (233.13135.65), .ignore (4.5.2), Jira Integration (4.7.1), Go Template (233.11799.172), Go (233.14475.9), Maven Helper (4.27.1-IJ2022.2), WakaTime (14.3.11), JS Toolbox (1.10)]
Disabled plugins:[GitHub Codespaces (0.5.0.1214), Import from Postman Collections (1.0.3), Requirements Pro (2022.4.1), [Deprecated] Rust (233.15445), Save Actions (2.3.0), Extra Icons (2024.2.2), Rust Playground (2.1.5-stable), Gruvbox Theme (0.5.5)]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Seems like Lombok plugin internal issue... 
Is it reproduceable?
