### ISSUE TITLE
[0.7.21][GOLAND 2023.3.3] com.intellij.psi.PsiInvalidElementAccessException: Element: class com.goide.psi.impl.GoMeth...

### ISSUE THREAD

**Issue by erroshankr** [Codium-ai/codiumai-jetbrains-release#198]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
com.intellij.psi.PsiInvalidElementAccessException: Element: class com.goide.psi.impl.GoMethodDeclarationImpl; no psi for file stub GoFileStub (class com.goide.stubs.GoFileStub), invalidation reason=onContentReload
	at com.intellij.psi.impl.source.SubstrateRef$StubRef.reportFileInvalidError(SubstrateRef.java:125)
	at com.intellij.psi.impl.source.SubstrateRef$StubRef.getContainingFile(SubstrateRef.java:117)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:235)
	at com.goide.psi.impl.GoStubbedElementImpl.getContainingFile(GoStubbedElementImpl.java:79)
	at com.goide.psi.impl.GoStubbedElementImpl.getContainingFile(GoStubbedElementImpl.java:33)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:119)
	at com.intellij.psi.PsiInvalidElementAccessException.getPsiInvalidationTrace(PsiInvalidElementAccessException.java:98)
	at com.intellij.psi.PsiInvalidElementAccessException.<init>(PsiInvalidElementAccessException.java:61)
	at com.intellij.psi.impl.source.SubstrateRef$StubRef.reportFileInvalidError(SubstrateRef.java:125)
	at com.intellij.psi.impl.source.SubstrateRef$StubRef.getContainingFile(SubstrateRef.java:117)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:235)
	at com.goide.psi.impl.GoStubbedElementImpl.getContainingFile(GoStubbedElementImpl.java:79)
	at com.goide.psi.impl.GoStubbedElementImpl.getContainingFile(GoStubbedElementImpl.java:33)
	at ai.codium.language.GoLanguageService.doGetSupportedElementsForClass(GoLanguageService.kt:73)
	at ai.codium.language.LanguageService.getSupportedElementsForClass(LanguageService.kt:87)
	at ai.codium.language.LanguageService.getSupportedElements$codium_ai_plugin(LanguageService.kt:64)
	at ai.codium.ui.CodiumGutterIconLineMarkerProvider.collectSlowLineMarkers(CodiumGutterIconLineMarkerProvider.kt:48)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:225)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectMarkers$2(LineMarkersPass.java:113)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:98)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectMarkers(LineMarkersPass.java:103)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:76)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:406)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:76)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:34)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:401)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:184)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:187)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

# Other Information
```
=== About ===
Build version: GoLand 2023.3.3 Build: #GO-233.14015.113 January 26, 2024
Theme: Light
JRE: 17.0.9+7-b1087.11, JetBrains s.r.o.
JVM: 17.0.9+7-b1087.11, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 14.3.1 (aarch64)

=== Plugins ===
Custom plugins: [Key Promoter X (2023.3.0), Go Linter (1.6.6), Prettier (233.13135.104), Rainbow Brackets (2024.2.1), GitHub Copilot (1.4.18.4775), Codiumate - Code, test and review with confidence - by CodiumAI (0.7.21), Clojure LSP (1.14.10), Snyk Security - Code, Open Source, Container, IaC Configurations (2.7.4), CSV Editor (3.3.0-233)]
Disabled plugins:[Space (233.14475.8), Kubernetes (233.14475.2), Python Community Edition (233.14475.9)]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Will close that duplication of #199
