### ISSUE TITLE
[Exception][IDEA 2022.3.3 RC] com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.psi....

### ISSUE THREAD

**Issue by oranshiner** [Codium-ai/codiumai-jetbrains-release#2]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.psi.PsiFileFactory because container is already disposed (container=Project(name=codium-vs-chatGPT, containerState=DISPOSE_COMPLETED, componentStore=/Users/oranshiner/codium-vs-chatGPT) (disposed))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:40)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:695)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:629)
	at com.intellij.psi.PsiFileFactory.getInstance(PsiFileFactory.java:18)
	at com.intellij.ui.LanguageTextField.createDocument(LanguageTextField.java:93)
	at com.intellij.ui.LanguageTextField$SimpleDocumentCreator.createDocument(LanguageTextField.java:80)
	at com.intellij.ui.LanguageTextField.<init>(LanguageTextField.java:64)
	at com.intellij.ui.LanguageTextField.<init>(LanguageTextField.java:48)
	at com.intellij.ui.EditorTextFieldProviderImpl$MyEditorTextField.<init>(EditorTextFieldProviderImpl.java:45)
	at com.intellij.ui.EditorTextFieldProviderImpl.getEditorField(EditorTextFieldProviderImpl.java:37)
	at ai.codium.ui.contentParts.CodiumCodePanel.getCodeEditorField(CodiumCodePanel.kt:45)
	at ai.codium.ui.contentParts.CodiumCodePanel.addItems(CodiumCodePanel.kt:62)
	at ai.codium.ui.CodiumContentPanel.setCodePanelContent(CodiumContentPanel.kt:251)
	at ai.codium.ui.CodiumContentPanel.setCodePanelContent$default(CodiumContentPanel.kt:233)
	at ai.codium.ui.CodiumToolWindowFactory$createToolWindowContent$3.responseReceived$lambda$3(CodiumToolWindowFactory.kt:150)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2022.3.3 RC Build: #IU-223.8836.35 March 8, 2023
Theme: Darcula
JRE: 17.0.6+1-b653.34, JetBrains s.r.o.
JVM: 17.0.6+1-b653.34, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.2.1 (aarch64)

=== Plugins ===
Custom plugins: [CodiumAI - Meaningful tests powered by TestGPT (0.4.3), Python (223.8836.35)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Fixed in 0.4.4
