### ISSUE TITLE
[0.7.23][WEBSTORM 2023.3.4] java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by mohamedthabet-getir** [Codium-ai/codiumai-jetbrains-release#201]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.intellij.ui.components.WideSelectionListUI.updateLayoutState(WideSelectionListUI.java:207)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1394)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2815)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:224)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:204)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:251)
	at java.desktop/javax.swing.DefaultListSelectionModel.insertIndexInterval(DefaultListSelectionModel.java:675)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.intervalAdded(BasicListUI.java:2773)
	at java.desktop/javax.swing.AbstractListModel.fireIntervalAdded(AbstractListModel.java:157)
	at java.desktop/javax.swing.DefaultComboBoxModel.addElement(DefaultComboBoxModel.java:130)
	at java.desktop/javax.swing.JComboBox.addItem(JComboBox.java:746)
	at ai.codium.ui.chat.codeAssist.CodiumCodeAssistPanel.resetContextComponents$lambda$17(CodiumCodeAssistPanel.kt:314)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

# Other Information
```
=== About ===
Build version: WebStorm 2023.3.4 Build: #WS-233.14475.40 February 14, 2024
Theme: Dark
JRE: 17.0.10+1-b1087.17, JetBrains s.r.o.
JVM: 17.0.10+1-b1087.17, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 14.2.1 (aarch64)

=== Plugins ===
Custom plugins: [.env files support (2024.1), Kafka (233.13135.103), Big Data Tools Core (233.14475.28), Terraform and HCL (233.13135.65), JSTestDriver Plugin (202.5), .ignore (4.5.2), Codiumate - Code, test and review with confidence - by CodiumAI (0.7.23)]
Disabled plugins:[WarmNeon Color Scheme (233.14475.40), PostCSS (233.14475.40), Webpack (233.14475.40), Polymer & Web Components (233.14475.40), Copyright (233.14475.40), Styled Components & Styled JSX (233.14475.40), Pug (ex-Jade) (233.14475.40), SonarLint (10.3.0.77475), Remote Development Gateway (233.14475.40), VibrantInk Color Scheme (233.14475.40), Vagrant (233.14475.40), Task Management (233.14475.40), GitLab (233.14475.40), Terminal for Gateway (233.14475.40), Diagrams (233.14475.40), Angular and AngularJS (233.14475.40), Node.js Remote Interpreter (233.14475.40), All Hallow's Eve Color Scheme (233.14475.40), HTML Tools (233.14475.40), Live Edit (233.14475.40), Subversion (233.14475.40), TextMate Bundles (233.14475.40), Monokai Color Scheme (233.14475.40), GitHub (233.14475.40), Package Checker (233.14475.40), GitHub Color Scheme (233.14475.40), Cobalt Color Scheme (233.14475.40), Fig (2.0.0), Dev Containers (233.14475.40), EJS (233.14475.40), Qodana (233.14475.40), FTP/SFTP/WebDAV Connectivity (233.14475.40), OpenAPI Specifications (233.14475.40), Vue.js (233.14475.40), Refactor-X (233.14475.40), Time Tracking (233.14475.40), Cucumber.js (233.14475.40), Performance Testing (233.14475.40), Sass (233.14475.40), Handlebars/Mustache (233.14475.40), Code With Me (233.14475.40), Next.js Support (233.14475.40), Railscasts Color Scheme (233.14475.40), Twilight Color Scheme (233.14475.40), SSH Remote Run (233.14475.40), Vite (233.14475.40), Endpoints (233.14475.40), Karma (233.14475.40), Tailwind CSS (233.14475.40), Blackboard Color Scheme (233.14475.40), WebP Support (233.14475.40), AI Assistant (233.14475.40), HTTP Client (233.14475.40), Mercurial (233.14475.40), Performance Testing (Dynamic Plugins) (233.14475.40), Less (233.14475.40)]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Fixed in upcoming 0.7.24 version
