### ISSUE TITLE
[0.7.23][INTELLIJ IDEA IU 2023.3.4] java.lang.NullPointerException: Cannot invoke "javax.swing.Icon.getIconHeight()" ...

### ISSUE THREAD

**Issue by BAVhel** [Codium-ai/codiumai-jetbrains-release#202]
# Stack Trace
```
java.lang.NullPointerException: Cannot invoke "javax.swing.Icon.getIconHeight()" because "this.defaultIcon" is null
	at java.desktop/javax.swing.JLabel.setIcon(JLabel.java:415)
	at ai.codium.ui.chat.codeAssist.CodiumCodeAssistPanel$initChatHeaderPanel$1$4.getListCellRendererComponent(CodiumCodeAssistPanel.kt:210)
	at com.intellij.ide.ui.laf.darcula.ui.DarculaComboBoxUI$CustomComboPopup$MyDelegateRenderer.getListCellRendererComponent(DarculaComboBoxUI.java:867)
	at com.intellij.ui.components.WideSelectionListUI.updateLayoutState(WideSelectionListUI.java:197)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1394)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2815)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:224)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:204)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:251)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:448)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:458)
	at java.desktop/javax.swing.DefaultListSelectionModel.removeSelectionIntervalImpl(DefaultListSelectionModel.java:619)
	at java.desktop/javax.swing.DefaultListSelectionModel.clearSelection(DefaultListSelectionModel.java:463)
	at java.desktop/javax.swing.JList.clearSelection(JList.java:2082)
	at java.desktop/javax.swing.plaf.basic.BasicComboPopup.setListSelection(BasicComboPopup.java:1270)
	at java.desktop/javax.swing.plaf.basic.BasicComboPopup$Handler.itemStateChanged(BasicComboPopup.java:1099)
	at java.desktop/javax.swing.JComboBox.fireItemStateChanged(JComboBox.java:1257)
	at java.desktop/javax.swing.JComboBox.selectedItemChanged(JComboBox.java:1309)
	at java.desktop/javax.swing.JComboBox.contentsChanged(JComboBox.java:1365)
	at java.desktop/javax.swing.AbstractListModel.fireContentsChanged(AbstractListModel.java:127)
	at java.desktop/javax.swing.DefaultComboBoxModel.setSelectedItem(DefaultComboBoxModel.java:94)
	at ai.codium.ui.chat.codeAssist.CodiumCodeAssistPanel$initChatHeaderPanel$1$5.setSelectedItem(CodiumCodeAssistPanel.kt:234)
	at java.desktop/javax.swing.JComboBox.setSelectedItem(JComboBox.java:609)
	at ai.codium.ui.chat.codeAssist.CodiumCodeAssistPanel.resetContextComponents$lambda$17(CodiumCodeAssistPanel.kt:317)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2023.3.4 Build: #IU-233.14475.28 February 13, 2024
Theme: Darcula
JRE: 17.0.10+1-b1087.17, JetBrains s.r.o.
JVM: 17.0.10+1-b1087.17, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [Continue (0.0.37), AWS Toolkit - Amazon Q, CodeWhisperer, and more (2.11-233), JPA Buddy (2023.4.1-233), CheckStyle-IDEA (5.88.0), Jump to Line (0.1.15), One Dark Theme (5.10.0), Git Branch Cleaner (1.1.4), Codiumate - Code, test and review with confidence - by CodiumAI (0.7.23), EnvFile (3.4.2)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Fixed in 0.7.24 version
