### ISSUE TITLE
[0.7.24][GOLAND 2023.3.4] java.lang.Throwable: psiElement is not instance of requiredClass.psiElement=TYPE_REFERENCE...

### ISSUE THREAD

**Issue by chunshengster** [Codium-ai/codiumai-jetbrains-release#204]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable: psiElement is not instance of requiredClass.
psiElement=TYPE_REFERENCE_EXPRESSION, psiElement.class=class com.goide.psi.impl.GoTypeReferenceExpressionImpl, requiredClass=interface com.goide.psi.GoMethodDeclaration, operation=Looking for orders.OrderDeliveryService in go.method, stubIdList=[25, 56, 90, 112, 139, 163, 181, 199, 221, 244, 266, 294, 316].
ref: 50cf572587cf
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: PSI and index do not match.
Please report the problem to JetBrains with the files attached
 file=GO_FILE, file.class=class com.goide.psi.GoFile, file.lang=Language: go, modStamp=20
 tree consistent
 stub debugInfo=created in calcStubTree; with backReference
 viewProvider=com.intellij.psi.SingleRootFileViewProvider{vFile=file:///Users/chunsheng/Work/osqianxing/projects/guanpu-server/service/orders/order_delivery.go, vFileId=640, content=VirtualFileContent{size=28254}, eventSystemEnabled=true}
 viewProvider stamp: 7; file stamp: 7; file modCount: 1710477239893; file length: 28254
 doc saved: true; doc stamp: 7; doc size: 27098; committed: true
indexing info: indexing timestamp = 1710477239893, binary = false, byte size = 28254, char size = 30753
ref: 50cf572587cf
latestIndexedStub=null
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.psi.stubs.StubProcessingHelperBase.inconsistencyDetected(StubProcessingHelperBase.java:156)
	at com.intellij.psi.stubs.StubProcessingHelperBase.checkType(StubProcessingHelperBase.java:90)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:61)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$5(StubIndexEx.java:152)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:202)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:102)
	at com.goide.stubs.index.GoMethodIndex.find(GoMethodIndex.java:52)
	at com.goide.psi.impl.GoPsiImplUtil.calcMethods(GoPsiImplUtil.java:1658)
	at com.goide.psi.impl.GoPsiImplUtil.lambda$getMethods$32(GoPsiImplUtil.java:1514)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij

<TRIMMED STACKTRACE>

getSupportedElements$codium_ai_plugin(LanguageService.kt:64)
	at ai.codium.CodiumInlayProvider.getCollectorFor(CodiumInlayProvider.kt:79)
	at ai.codium.CodiumInlayProvider.getCollectorFor(CodiumInlayProvider.kt:34)
	at com.intellij.codeInsight.hints.InlayHintsUtilsKt.getCollectorWrapperFor(InlayHintsUtils.kt:50)
	at com.intellij.codeInsight.daemon.impl.InlayHintsPassFactoryInternal.createHighlightingPass(InlayHintsPassFactoryInternal.kt:46)
	at com.intellij.codeInsight.daemon.impl.TextEditorHighlightingPassRegistrarImpl.instantiatePasses(TextEditorHighlightingPassRegistrarImpl.java:186)
	at com.intellij.codeInsight.daemon.impl.TextEditorBackgroundHighlighter.getPasses(TextEditorBackgroundHighlighter.kt:65)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$submitInBackground$25(DaemonCodeAnalyzerImpl.java:1163)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$submitInBackground$26(DaemonCodeAnalyzerImpl.java:1152)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.submitInBackground(DaemonCodeAnalyzerImpl.java:1149)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$queuePassesCreation$21(DaemonCodeAnalyzerImpl.java:1114)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:187)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

# Other Information
```
=== About ===
Build version: GoLand 2023.3.4 Build: #GO-233.14475.38 February 14, 2024
Theme: Solarized Dark
JRE: 17.0.10+1-b1087.17, JetBrains s.r.o.
JVM: 17.0.10+1-b1087.17, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 14.2 (x86_64)

=== Plugins ===
Custom plugins: [Go Orm Code Helper (1.4.3), IdeaVim (2.9.1), Codiumate - Code, test and review with confidence - by CodiumAI (0.7.24), Chinese (Simplified) Language Pack / 中文语言包 (233.287), Solarized Theme (3.0.0), Codeium: AI Autocomplete and Chat for Python, JS, Java, Go... (1.8.10)]
Disabled plugins:[Code With Me (233.14475.38), Database Tools and SQL (233.14475.38), Remote Development Gateway (233.14475.38), Performance Testing (233.14475.38), Docker (233.14475.38), Performance Testing (Dynamic Plugins) (233.14475.38), JavaScript and TypeScript (233.14475.38), Qodana (233.14475.38), Refactor-X (233.14475.38), Dev Containers (233.14475.38), JavaScript Intention Power Pack (233.14475.38), Webpack (233.14475.38), GitHub Actions Manager (1.17.0), OpenAPI Specifications (233.14475.38), CSS (233.14475.38), JavaScript Debugger (233.14475.38), Terminal for Gateway (233.14475.38)]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
IDE internal error:
```
RuntimeExceptionWithAttachments: PSI and index do not match.
Please report the problem to JetBrains with the files attached
```
