### ISSUE TITLE
[0.7.16][INTELLIJ IDEA IC 2023.2.1] java.lang.Throwable: find: An invalid record was encountered. (-67701)

### ISSUE THREAD

**Issue by himanshu-housing** [Codium-ai/codiumai-jetbrains-release#205]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable: find: An invalid record was encountered. (-67701)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.intellij.credentialStore.KeyChainCredentialStore$Companion.checkForError(macOsKeychainLibrary.kt:88)
	at com.intellij.credentialStore.KeyChainCredentialStore$Companion.findGenericPassword(macOsKeychainLibrary.kt:37)
	at com.intellij.credentialStore.KeyChainCredentialStore$Companion.access$findGenericPassword(macOsKeychainLibrary.kt:29)
	at com.intellij.credentialStore.KeyChainCredentialStore.get(macOsKeychainLibrary.kt:96)
	at com.intellij.credentialStore.NativeCredentialStoreWrapper.get(NativeCredentialStoreWrapper.kt:46)
	at com.intellij.ide.passwordSafe.impl.BasePasswordSafe.get(PasswordSafeImpl.kt:92)
	at com.intellij.credentialStore.CredentialStore.getPassword(CredentialStore.java:30)
	at ai.codium.CodiumCredentialStorageKt.getCodiumRefreshToken(CodiumCredentialStorage.kt:16)
	at ai.codium.net.CodiumLoginManager.getRefreshToken(CodiumLoginManager.kt:21)
	at ai.codium.net.CodiumNetworkService.getIdToken(CodiumNetworkService.kt:304)
	at ai.codium.net.CodiumNetworkService.getUserData(CodiumNetworkService.kt:314)
	at ai.codium.UserDataManager$Companion.doInitUserData(UserDataManager.kt:32)
	at ai.codium.UserDataManager$Companion.doInitUserData$lambda$1(UserDataManager.kt:39)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:254)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:373)
	at com.intellij.util.Alarm$Request.run(Alarm.java:360)
	at com.intellij.util.concurrency.Propagation.contextAwareCallable$lambda$2(propagation.kt:328)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2023.2.1 Build: #IC-232.9559.62 August 23, 2023
Theme: Darcula
JRE: 17.0.8+7-b1000.8, JetBrains s.r.o.
JVM: 17.0.8+7-b1000.8, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 12.6.8 (aarch64)

=== Plugins ===
Custom plugins: [Visual Studio Code Dark Plus Theme (2.8), Lombok (232.9559.34), One Dark theme (5.9.0), Codiumate - Code, test and review with confidence - by CodiumAI (0.7.16)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Some kind of glitch happened in IDE to MacOS CredentialStore request...
Does it happened often/always or it was one-time glitch? 
Did you allow IDE to store/read data to/form CredentialStore?
