### ISSUE TITLE
[0.7.24][GOLAND 2023.3.4] java.lang.Throwable: psiElement is not instance of requiredClass.psiElement=PARAMETERS, ps...

### ISSUE THREAD

**Issue by chunshengster** [Codium-ai/codiumai-jetbrains-release#206]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable: psiElement is not instance of requiredClass.
psiElement=PARAMETERS, psiElement.class=class com.goide.psi.impl.GoParametersImpl, requiredClass=interface com.goide.psi.GoMethodDeclaration, operation=Looking for orders.OrderService in go.method, stubIdList=[40, 78, 94, 116, 134, 167, 212, 240, 264, 320, 340, 360, 381, 406, 426].
ref: 50cf572587cf
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: PSI and index do not match.
Please report the problem to JetBrains with the files attached
 file=GO_FILE, file.class=class com.goide.psi.GoFile, file.lang=Language: go, modStamp=504
 tree consistent
 stub debugInfo=created in calcStubTree; with backReference
 viewProvider=com.intellij.psi.SingleRootFileViewProvider{vFile=file:///Users/chunsheng/Work/osqianxing/projects/guanpu-server/service/orders/order.go, vFileId=10856, content=VirtualFileContent{size=80912}, eventSystemEnabled=true}
 viewProvider stamp: 543408; file stamp: 544317; file modCount: 1710750916593; file length: 80912
 doc saved: true; doc stamp: 544317; doc size: 77070; committed: false
indexing info: indexing timestamp = 1710750916593, binary = false, byte size = 80912, char size = 77070
ref: 50cf572587cf
latestIndexedStub=null
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.psi.stubs.StubProcessingHelperBase.inconsistencyDetected(StubProcessingHelperBase.java:156)
	at com.intellij.psi.stubs.StubProcessingHelperBase.checkType(StubProcessingHelperBase.java:90)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:61)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$5(StubIndexEx.java:152)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:202)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:102)
	at com.goide.stubs.index.GoMethodIndex.find(GoMethodIndex.java:52)
	at com.goide.psi.impl.GoPsiImplUtil.calcMethods(GoPsiImplUtil.java:1658)
	at com.goide.psi.impl.GoPsiImplUtil.lambda$getMethods$32(GoPsiImplUtil.java:1514)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.Re

<TRIMMED STACKTRACE>

ger.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:108)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:73)
	at com.intellij.util.concurrency.Invoker.startTask(Invoker.java:238)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:194)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:177)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:508)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:244)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:222)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

# Other Information
```
=== About ===
Build version: GoLand 2023.3.4 Build: #GO-233.14475.38 February 14, 2024
Theme: Solarized Dark
JRE: 17.0.10+1-b1087.17, JetBrains s.r.o.
JVM: 17.0.10+1-b1087.17, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 14.2 (x86_64)

=== Plugins ===
Custom plugins: [Go Orm Code Helper (1.4.3), IdeaVim (2.9.1), Codiumate - Code, test and review with confidence - by CodiumAI (0.7.24), Chinese (Simplified) Language Pack / 中文语言包 (233.287), Solarized Theme (3.0.0), Codeium: AI Autocomplete and Chat for Python, JS, Java, Go... (1.8.10)]
Disabled plugins:[Code With Me (233.14475.38), Database Tools and SQL (233.14475.38), Remote Development Gateway (233.14475.38), Performance Testing (233.14475.38), Docker (233.14475.38), Performance Testing (Dynamic Plugins) (233.14475.38), JavaScript and TypeScript (233.14475.38), Qodana (233.14475.38), Refactor-X (233.14475.38), Dev Containers (233.14475.38), JavaScript Intention Power Pack (233.14475.38), Webpack (233.14475.38), GitHub Actions Manager (1.17.0), OpenAPI Specifications (233.14475.38), CSS (233.14475.38), JavaScript Debugger (233.14475.38), Terminal for Gateway (233.14475.38)]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
IDE internal error:
```
RuntimeExceptionWithAttachments: PSI and index do not match.
Please report the problem to JetBrains with the files attached
```
