### ISSUE TITLE
[0.7.26][CLION 2023.2] java.lang.UnsatisfiedLinkError: 'boolean org.cef.CefApp.N_RegisterSchemeHandlerFactory(java.la...

### ISSUE THREAD

**Issue by meowser52** [Codium-ai/codiumai-jetbrains-release#209]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.UnsatisfiedLinkError: 'boolean org.cef.CefApp.N_RegisterSchemeHandlerFactory(java.lang.String, java.lang.String, org.cef.callback.CefSchemeHandlerFactory)'
	at jcef/org.cef.CefApp.N_RegisterSchemeHandlerFactory(Native Method)
	at jcef/org.cef.CefApp.registerSchemeHandlerFactory(CefApp.java:416)
	at ai.codium.webview.ChatWindowContentPanel.registerAppSchemeHandler(ChatWindowContentPanel.kt:23)
	at ai.codium.webview.ChatWindowContentPanel.initializeJBCefBrowser(ChatWindowContentPanel.kt:53)
	at ai.codium.webview.ChatWindowContentPanel.<init>(ChatWindowContentPanel.kt:63)
	at ai.codium.webview.ChatWebviewToolWindowFactory$initContent$1$1.invoke(ChatWebviewToolWindowFactory.kt:95)
	at ai.codium.webview.ChatWebviewToolWindowFactory$initContent$1$1.invoke(ChatWebviewToolWindowFactory.kt:92)
	at com.intellij.openapi.application.ActionsKt.invokeLater$lambda$5(actions.kt:74)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:789)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:759)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

# Other Information
```
=== About ===
Build version: CLion 2023.2 Build: #CL-232.8660.186 July 26, 2023
Theme: Dark
JRE: 17.0.7+7-b1000.6, JetBrains s.r.o.
JVM: 17.0.7+7-b1000.6, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.5.2 (aarch64)

=== Plugins ===
Custom plugins: [Codiumate - Code, test and review with confidence - by CodiumAI (0.7.26)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Hi Artem!
Thanks for reporting!
Seems like one time IDE internal glitch (at least I can't reproduce it and we don't have any other related reports so far)
Let us know if you see it again.
