### ISSUE TITLE
[0.7.24][RUBYMINE 2023.3.5] java.lang.RuntimeException: Cannot invoke (class=, method=repositoryChanged, topic=GitRep...

### ISSUE THREAD

**Issue by boazadato** [Codium-ai/codiumai-jetbrains-release#211]
# User Description
got report from RubyMine, forwarding 😅 

# Stack Trace
```
java.lang.RuntimeException: Cannot invoke (class=, method=repositoryChanged, topic=GitRepository change)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:677)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:423)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:402)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:461)
	at jdk.proxy6/jdk.proxy6.$Proxy154.repositoryChanged(Unknown Source)
	at git4idea.repo.GitRepositoryUpdater.filesChanged(GitRepositoryUpdater.java:138)
	at com.intellij.vfs.AsyncVfsEventsPostProcessorImpl.processEvents$lambda$2(AsyncVfsEventsPostProcessorImpl.kt:51)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$runUnderDisposeAwareIndicator$15(BackgroundTaskUtil.java:371)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:366)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:349)
	at com.intellij.vfs.AsyncVfsEventsPostProcessorImpl.processEvents(AsyncVfsEventsPostProcessorImpl.kt:50)
	at com.intellij.vfs.AsyncVfsEventsPostProcessorImpl.access$processEvents(AsyncVfsEventsPostProcessorImpl.kt:20)
	at com.intellij.vfs.AsyncVfsEventsPostProcessorImpl$queue$1.invoke(AsyncVfsEventsPostProcessorImpl.kt:21)
	at com.intellij.vfs.AsyncVfsEventsPostProcessorImpl$queue$1.invoke(AsyncVfsEventsPostProcessorImpl.kt:21)
	at com.intellij.vfs.AsyncVfsEventsPostProcessorImpl.queue$lambda$0(AsyncVfsEventsPostProcessorImpl.kt:21)
	at com.intellij.util.concurrency.QueueProcessor.lambda$wrappingProcessor$0(QueueProcessor.java:84)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:253)
	at com.intellij.util.concurrency.QueueProcessor.lambda$wrappingProcessor$1(QueueProcessor.java:84)
	at com.intellij.util.concurrency.QueueProcessor.lambda$startProcessing$3(QueueProcessor.java:227)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:253)
	at com.intellij.util.concurr

<TRIMMED STACKTRACE>

outines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.RuntimeException: Cannot invoke (class=GitHelper$$Lambda$6270/0x0000000802614750, method=repositoryChanged, topic=GitRepository change)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:677)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:423)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:392)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:461)
	at jdk.proxy2/jdk.proxy2.$Proxy155.dirtyUnder(Unknown Source)
	at git4idea.annotate.GitAnnotationsListener$1.repositoryChanged(GitAnnotationsListener.java:24)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:700)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:660)
	... 47 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 199 out of bounds for length 199
	at com.intellij.ui.components.WideSelectionListUI.updateLayoutState(WideSelectionListUI.java:207)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1394)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2815)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:224)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:204)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:251)
	at java.desktop/javax.swing.DefaultListSelectionModel.insertIndexInterval(DefaultListSelectionModel.java:675)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.intervalAdded(BasicListUI.java:2773)
	at java.desktop/javax.swing.AbstractListModel.fireIntervalAdded(AbstractListModel.java:157)
	at java.desktop/javax.swing.DefaultComboBoxModel.addElement(DefaultComboBoxModel.java:130)
	at java.desktop/javax.swing.JComboBox.addItem(JComboBox.java:746)
	at ai.codium.ui.chat.prePR.CodiumPrePRPanel.setBranches(CodiumPrePRPanel.kt:64)
	at ai.codium.ui.chat.prePR.CodiumPrePRPanel.access$setBranches(CodiumPrePRPanel.kt:18)
	at ai.codium.ui.chat.prePR.CodiumPrePRPanel$gitHelper$1.invoke(CodiumPrePRPanel.kt:25)
	at ai.codium.ui.chat.prePR.CodiumPrePRPanel$gitHelper$1.invoke(CodiumPrePRPanel.kt:25)
	at ai.codium.vcsIntegration.GitHelper._init_$lambda$0(GitHelper.kt:34)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:700)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:660)
	... 55 more

```

# Other Information
```
=== About ===
Build version: RubyMine 2023.3.5 Build: #RM-233.14808.14 March 8, 2024
Theme: Dark
JRE: 17.0.10+1-b1087.21, JetBrains s.r.o.
JVM: 17.0.10+1-b1087.21, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 14.3.1 (aarch64)

=== Plugins ===
Custom plugins: [Codiumate - Code, test and review with confidence - by CodiumAI (0.7.24), GitHub Copilot (1.5.0.5148)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Please update to 0.7.26
