### ISSUE TITLE
[0.7.26][JETBRAINS RIDER 2024.1 EAP 9] Catch

### ISSUE THREAD

**Issue by MBrekhof** [Codium-ai/codiumai-jetbrains-release#212]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable: Control-flow exceptions (e.g. this class com.intellij.openapi.progress.ProcessCanceledException) should never be logged. Instead, these should have been rethrown if caught.
	at com.intellij.openapi.diagnostic.Logger.ensureNotControlFlow(Logger.java:513)
	at com.intellij.idea.IdeaLogger.doLogError(IdeaLogger.java:154)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:145)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:423)
	at com.jetbrains.rd.platform.util.IdeaRdLoggerFactor$getLogger$1.log(IdeaRdLoggerFactor.kt:29)
	at com.jetbrains.rd.util.SwitchLogger.log(Logger.kt:38)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:86)
	at com.jetbrains.rd.util.reactive.Property.setValue(Property.kt:21)
	at com.jetbrains.rider.editors.RiderBackendInteractionHelper$syncFromBackend$3.invoke(RiderBackendInteractionHelper.kt:79)
	at com.jetbrains.rider.editors.RiderBackendInteractionHelper$syncFromBackend$3.invoke(RiderBackendInteractionHelper.kt:61)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.destruct(RLifetime.kt:501)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.terminate(RLifetime.kt:480)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.destruct(RLifetime.kt:505)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.terminate(RLifetime.kt:480)
	at com.jetbrains.rider.services.popups.nova.impl.DefaultPopupViewModel$prolongForExecuting$1.invoke(DefaultPopupViewModel.kt:127)
	at com.jetbrains.rider.services.popups.nova.impl.DefaultPopupViewModel$prolongForExecuting$1.invoke(DefaultPopupViewModel.kt:127)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.destruct(RLifetime.kt:501)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.terminate(RLifetime.kt:480)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.terminate$default(RLifetime.kt:447)
	at com.jetbrains.rider.services.popups.nova.ui.RiderPopupStep.K(RiderPopupStep.kt:88)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$18(AbstractPopup.java:1766)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$4(FocusManagerImpl.java:174)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:33)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.kt:226)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.kt:192)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:170)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:164)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1764)
	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:178)
	at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:404)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:130)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:162)
	

<TRIMMED STACKTRACE>

and(CoreCommandProcessor.java:216)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:187)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.doRunWriteCommandAction(WriteCommandAction.java:151)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:118)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:338)
	at com.intellij.codeInsight.template.impl.TemplateState.calcResults(TemplateState.java:667)
	at com.intellij.codeInsight.template.impl.TemplateState.lambda$processAllExpressions$1(TemplateState.java:362)
	at com.intellij.openapi.application.impl.RwLockHolder.runWriteAction(RwLockHolder.kt:344)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:883)
	at com.intellij.codeInsight.template.impl.TemplateState.performWrite(TemplateState.java:424)
	at com.intellij.codeInsight.template.impl.TemplateState.processAllExpressions(TemplateState.java:399)
	at com.intellij.codeInsight.template.impl.TemplateState.start(TemplateState.java:339)
	at com.intellij.codeInsight.template.impl.TemplateState.start(TemplateState.java:301)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.lambda$startTemplate$1(TemplateManagerImpl.java:163)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:225)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:177)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:167)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:153)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.startTemplate(TemplateManagerImpl.java:166)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.startTemplate(TemplateManagerImpl.java:128)
	at com.jetbrains.rider.template.FrontendLiveTemplateHost.startTemplate(FrontendLiveTemplateHost.kt:106)
	at com.jetbrains.rider.template.RiderLiveTemplateHost.access$startTemplate$s-1700594016(RiderLiveTemplateHost.kt:22)
	at com.jetbrains.rider.template.RiderLiveTemplateHost$startTemplate$1.K(RiderLiveTemplateHost.kt:72)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.runUndoTransparentAction(CoreCommandProcessor.java:382)
	at com.jetbrains.rider.template.RiderLiveTemplateHost$startTemplate$1.invoke(RiderLiveTemplateHost.kt:71)
	at com.jetbrains.rider.template.RiderLiveTemplateHost$startTemplate$1.invoke(RiderLiveTemplateHost.kt:70)
	at com.jetbrains.rider.editors.RiderBackendInteractionHelper$doAfterSyncFinished$1.invoke(RiderBackendInteractionHelper.kt:99)
	at com.jetbrains.rider.editors.RiderBackendInteractionHelper$doAfterSyncFinished$1.invoke(RiderBackendInteractionHelper.kt:89)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	... 181 more

```

# Other Information
```
=== About ===
Build version: JetBrains Rider 2024.1 EAP 9 Build: #RD-241.14494.107 March 15, 2024
Theme: Light
JRE: 17.0.10+8-b1207.6, JetBrains s.r.o.
JVM: 17.0.10+8-b1207.6, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 10.0 (amd64)

=== Plugins ===
Custom plugins: [Kubernetes (241.14494.150), Codiumate - Code, test and review with confidence - by CodiumAI (0.7.26), Dev Containers (241.14494.150)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Fixed in latest 0.7.28 version
