### ISSUE TITLE
[0.7.29][GOLAND 2023.3.6] java.lang.Throwable: psiElement is not instance of requiredClass.psiElement=TYPE_REFERENCE...

### ISSUE THREAD

**Issue by ceearrashee** [Codium-ai/codiumai-jetbrains-release#216]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable: psiElement is not instance of requiredClass.
psiElement=TYPE_REFERENCE_EXPRESSION, psiElement.class=class com.goide.psi.impl.GoTypeReferenceExpressionImpl, requiredClass=interface com.goide.psi.GoMethodDeclaration, operation=Looking for controllers.PaymentsController in go.method, stubIdList=[245, 263, 281, 299, 352].
ref: 50cf572587cf
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: PSI and index do not match.
Please report the problem to JetBrains with the files attached
 file=GO_FILE, file.class=class com.goide.psi.GoFile, file.lang=Language: go, modStamp=1
 tree consistent
 stub debugInfo=created in calcStubTree; with backReference
 viewProvider=com.intellij.psi.SingleRootFileViewProvider{vFile=file://C:/Users/eandr/Projects/Existlive/mouse-golang/web/controllers/payment_controller.go, vFileId=15946, content=VirtualFileContent{size=20827}, eventSystemEnabled=true}
 viewProvider stamp: 23393; file stamp: 7883; file modCount: 1712221121857; file length: 20827
 doc saved: false; doc stamp: 23393; doc size: 21219; committed: true
indexing info: indexing timestamp = 1712221121857, binary = false, byte size = 20827, char size = 21219
ref: 50cf572587cf
latestIndexedStub=StubTree{myDebugInfo='created from index; with backReference', myRoot=GoFileStub}1380311914
   same size=false
   debugInfo=created from index; with backReference
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.psi.stubs.StubProcessingHelperBase.inconsistencyDetected(StubProcessingHelperBase.java:156)
	at com.intellij.psi.stubs.StubProcessingHelperBase.checkType(StubProcessingHelperBase.java:90)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:61)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$5(StubIndexEx.java:152)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:202)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:102)
	at com.goide.stubs.index.GoMethodIndex.find(

<TRIMMED STACKTRACE>

intellij.codeInsight.daemon.impl.TextEditorBackgroundHighlighter.getPasses(TextEditorBackgroundHighlighter.kt:65)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$submitInBackground$25(DaemonCodeAnalyzerImpl.java:1163)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$submitInBackground$26(DaemonCodeAnalyzerImpl.java:1152)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.submitInBackground(DaemonCodeAnalyzerImpl.java:1149)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$queuePassesCreation$21(DaemonCodeAnalyzerImpl.java:1114)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:187)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

# Other Information
```
=== About ===
Build version: GoLand 2023.3.6 Build: #GO-233.15026.17 March 21, 2024
Theme: Dark
JRE: 17.0.10+1-b1087.23, JetBrains s.r.o.
JVM: 17.0.10+1-b1087.23, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [Angular and AngularJS (233.14475.38), Sass (233.14015.113), Handlebars/Mustache (233.11799.172), Grazie Pro (0.3.294), Time Tracking (233.14015.29), TSLint (233.11799.194), Go Linter (1.6.6), Kubernetes (233.14475.2), MultiHighlight (3.1.0), GitHub Copilot (1.5.1.5332-nightly), Branch in Window Title (2.0.0), macOS Light Theme (233.11799.172), .ignore (4.5.2), Cody: AI Coding Assistant with Autocomplete & Chat (5.5.2-nightly), Gemini + Google Cloud Code (24.4.1-api-version-223), Codiumate - Code, test and review with confidence - by CodiumAI (0.7.29), File Expander (2.4), Node.js (233.13135.104), AI Assistant (233.15026.24), Developer Tools (4.1.1), Translation (3.5.7), Properties (233.11799.172), SQL Complexity (233.13135.65), Prettier (233.13135.104), Task Management (233.14015.29), PowerShell (2.6.1), Hunspell (233.15026.24), PostCSS (233.11799.194), Rider UI Theme Pack (0.14.11), Karma (233.13135.104), Mermaid (0.0.21+IJ.232), Space (233.15026.16), Ini (233.15026.15), String Manipulation (9.12.0)]
Disabled plugins:[Design Preview for Figma (1.2.1), Toml (233.13135.67), GitToolBox (500.2.2+233), Github Workflow (3.2.1), EnvFile (3.4.2), Run Configuration as Action (2.2), Tasks (1.8.4), CodeLogic (23.18.0), Git Machete (4.2.0), GitLab (233.15026.17), Python Community Edition (233.14475.9), Draw Graph (1.11.2024.03.16_10.09), Go method generator (1.0), Sourcery (1.15.0), Batch Scripts Support (1.0.13), Dart (233.14888), GitHub Theme (1.2.0), Jira Integration (4.7.1), InlineProblems (0.5.1), Git Branch Cleaner (1.1.4), Changelist Organizer (1.10.3), WakaTime (14.3.11), GitHub Actions Manager (1.17.0), Mercurial (233.15026.17), Git Extender (0.8.1), Material Theme UI (8.13.2), Code Complexity (1.5.0), Lotus Theme (1.10), Better Highlights (2024.1.10), ChatGPT GPT-4 - Bito AI Code Assistant (1.3.0), Atom Material Icons (94.1.0), CSV Editor (3.3.0-233), TinyGo (0.5.11), GitHub Color Scheme (233.11799.172), RunAnything (2.0), Snyk Security - Code, Open Source, Container, IaC Configurations (2.7.7), Helm Values (0.8.1)]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Seems like internal IDE error:

> RuntimeExceptionWithAttachments: PSI and index do not match.
Please report the problem to JetBrains with the files attached
