### ISSUE TITLE
[0.7.26][JETBRAINS RIDER 2023.3.4] Catch

### ISSUE THREAD

**Issue by Tindavetran10** [Codium-ai/codiumai-jetbrains-release#219]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable: Control-flow exceptions (e.g. this class com.intellij.openapi.progress.ProcessCanceledException) should never be logged. Instead, these should have been rethrown if caught.
	at com.intellij.openapi.diagnostic.Logger.ensureNotControlFlow(Logger.java:513)
	at com.intellij.idea.IdeaLogger.doLogError(IdeaLogger.java:154)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:145)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:423)
	at com.jetbrains.rd.platform.util.IdeaRdLoggerFactor$getLogger$1.log(IdeaRdLoggerFactor.kt:29)
	at com.jetbrains.rd.util.SwitchLogger.log(Logger.kt:38)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:86)
	at com.jetbrains.rd.util.reactive.ViewableList.add(ViewableList.kt:25)
	at com.jetbrains.rd.framework.impl.RdList$onWireReceived$2.invoke(RdList.kt:177)
	at com.jetbrains.rd.framework.impl.RdList$onWireReceived$2.invoke(RdList.kt:161)
	at com.jetbrains.rd.framework.MessageBroker$RdWireableDispatchHelper$doDispatch$2.invoke(MessageBroker.kt:122)
	at com.jetbrains.rd.framework.MessageBroker$RdWireableDispatchHelper$doDispatch$2.invoke(MessageBroker.kt:115)
	at com.jetbrains.rdclient.protocol.RdDispatcher.flushAll(RdDispatcher.kt:109)
	at com.jetbrains.rdclient.protocol.RdDispatcher.flushAllRunnable$lambda$0(RdDispatcher.kt:33)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1436)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)

<TRIMMED STACKTRACE>

)
	at com.intellij.codeInsight.template.impl.TemplateState.calcResults(TemplateState.java:667)
	at com.intellij.codeInsight.template.impl.TemplateState.lambda$processAllExpressions$1(TemplateState.java:362)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:975)
	at com.intellij.codeInsight.template.impl.TemplateState.performWrite(TemplateState.java:424)
	at com.intellij.codeInsight.template.impl.TemplateState.processAllExpressions(TemplateState.java:399)
	at com.intellij.codeInsight.template.impl.TemplateState.start(TemplateState.java:339)
	at com.intellij.codeInsight.template.impl.TemplateState.start(TemplateState.java:301)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.lambda$startTemplate$1(TemplateManagerImpl.java:163)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:225)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:177)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:167)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:153)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.startTemplate(TemplateManagerImpl.java:166)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.startTemplate(TemplateManagerImpl.java:128)
	at com.jetbrains.rider.template.FrontendLiveTemplateHost.startTemplate(FrontendLiveTemplateHost.kt:106)
	at com.jetbrains.rider.template.RiderLiveTemplateHost.access$startTemplate$s-1700594016(RiderLiveTemplateHost.kt:22)
	at com.jetbrains.rider.template.RiderLiveTemplateHost$startTemplate$1.j(RiderLiveTemplateHost.kt:72)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.runUndoTransparentAction(CoreCommandProcessor.java:382)
	at com.jetbrains.rider.template.RiderLiveTemplateHost$startTemplate$1.invoke(RiderLiveTemplateHost.kt:71)
	at com.jetbrains.rider.template.RiderLiveTemplateHost$startTemplate$1.invoke(RiderLiveTemplateHost.kt:70)
	at com.jetbrains.rider.editors.RiderBackendInteractionHelper.onSyncFromBackendFinished(RiderBackendInteractionHelper.kt:119)
	at com.jetbrains.rider.template.RiderLiveTemplateHost.startTemplate(RiderLiveTemplateHost.kt:70)
	at com.jetbrains.rider.template.FrontendLiveTemplateHost.executeTemplate(FrontendLiveTemplateHost.kt:73)
	at com.jetbrains.rider.template.RiderLiveTemplateHost$ProtocolListener$extensionCreated$1.invoke(RiderLiveTemplateHost.kt:53)
	at com.jetbrains.rider.template.RiderLiveTemplateHost$ProtocolListener$extensionCreated$1.invoke(RiderLiveTemplateHost.kt:47)
	at com.jetbrains.rd.util.reactive.IViewableList$adviseAddRemove$1.invoke(ViewableCollections.kt:187)
	at com.jetbrains.rd.util.reactive.IViewableList$adviseAddRemove$1.invoke(ViewableCollections.kt:186)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	... 47 more

```

# Other Information
```
=== About ===
Build version: JetBrains Rider 2023.3.4 Build: #RD-233.14475.66 March 6, 2024
Theme: Rider Night
JRE: 17.0.10+1-b1087.17, JetBrains s.r.o.
JVM: 17.0.10+1-b1087.17, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [Cyberpunk Neon Theme (1.0.4), AI Assistant (233.14475.74), Codiumate - Code, test and review with confidence - by CodiumAI (0.7.26), GitHub Copilot (1.5.0.5148)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Seems like some internal IDE glitch... Will close for now, let us know if you experience it often and have a way to reproduce.
