### ISSUE TITLE
[Exception][WebStorm 2022.2.3] java.lang.NoClassDefFoundError: okhttp3/internal/Util

### ISSUE THREAD

**Issue by MauroMoyano** [Codium-ai/codiumai-jetbrains-release#22]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.NoClassDefFoundError: okhttp3/internal/Util
	at ai.codium.CodiumInlayProviderBase.addCodiumTestsGenerationInlay(CodiumInlayProviderBase.kt:101)
	at ai.codium.jsts.CodiumJsTsInlayProvider.access$addCodiumTestsGenerationInlay(CodiumJsTsInlayProvider.kt:20)
	at ai.codium.jsts.CodiumJsTsInlayProvider$getCollectorFor$2.addInlaysForFun(CodiumJsTsInlayProvider.kt:122)
	at ai.codium.jsts.CodiumJsTsInlayProvider$getCollectorFor$2.collect(CodiumJsTsInlayProvider.kt:67)
	at com.intellij.codeInsight.hints.CollectorWithSettings.collectHints(InlayHintsUtils.kt:91)
	at com.intellij.codeInsight.hints.InlayHintsPass$doCollectInformation$1.process(InlayHintsPass.kt:47)
	at com.intellij.codeInsight.hints.InlayHintsPass$doCollectInformation$1.process(InlayHintsPass.kt:27)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:86)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:63)
	at com.intellij.codeInsight.hints.InlayHintsPass.doCollectInformation(InlayHintsPass.kt:38)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:215)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ClassNotFoundException: okhttp3.internal.Util PluginClassLoader(plugin=PluginDescriptor(name=CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4, id=codiumai.codiumai, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\WebStorm2022.2\plugins\codium-ai-plugin-0.4.11.jar, version=0.4.11, package=null, isBundled=false), packagePrefix=null, instanceId=113, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:214)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 39 more

```

# Other Information
```
=== About ===
Build version: WebStorm 2022.2.3 Build: #WS-222.4345.14 October 5, 2022
Theme: DarkDark
JRE: 17.0.4.1+7-b469.62, JetBrains s.r.o.
JVM: 17.0.4.1+7-b469.62, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 10 10.0 (amd64)

=== Plugins ===
Custom plugins: [SuperDark Theme (1.0.2), .env files support (2022.2), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.4.11), Quokka (1.0.366), Atom Material Icons (73.0.0), ChatGPT (2.1.15-222.231)]
Disabled plugins:[One Dark theme (5.7.1), Xcode Theme (1.6.1), Visual Studio Code Dark Plus Theme (2.6), Atom One Theme (1.5.1), Monokai Pro Theme (1.9)]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/7nP9nfz3) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Hi @MauroMoyano 
Thanks for reporting!
Did you install our plugin from JetBrains marketplace or did manual install?

**Comment by almog-lv** [comment]
Hey @MauroMoyano can you please provide more information on the installation? Did you install our plugin from JetBrains marketplace or did manually install it? Can you also upgrade the version to 0.5 and see if it is reproduced?

**Comment by MauroMoyano** [comment]
my installation was through the marketplace

**Comment by ArtsiomCh** [comment]
Do you still see that exception with latest 0.5.0 ?
If so, did you try to uninstall then install plugin again?

**Comment by ArtsiomCh** [comment]
Looks like one time WebStorm glitch. Will close for now and we'll keep our eyes for this component.
