### ISSUE TITLE
Login credentials do not persist restart.

### ISSUE THREAD

**Issue by allComputableThings** [Codium-ai/codiumai-jetbrains-release#222]
I can enter login info, but I am required to login at every restart of PyCharm.

Latest codium plugin. Latest PyCharm community (Ubunutu 22.4, PyCharm installed via Snap which might have sandboxes).

```
Opening in existing browser session.
2024-04-19 11:12:56,991 [ 106814] SEVERE - #c.i.c.PasswordSafeSettings - secret_password_store_sync error code 23, error message The file was externally modified
java.lang.Throwable: secret_password_store_sync error code 23, error message The file was externally modified
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.credentialStore.SecretCredentialStore.set(linuxSecretLibrary.kt:224)
	at com.intellij.credentialStore.NativeCredentialStoreWrapper$set$1.invoke(NativeCredentialStoreWrapper.kt:76)
	at com.intellij.credentialStore.NativeCredentialStoreWrapper$set$1.invoke(NativeCredentialStoreWrapper.kt:72)
	at com.intellij.credentialStore.NativeCredentialStoreWrapper$1.invoke(NativeCredentialStoreWrapper.kt:26)
	at com.intellij.credentialStore.NativeCredentialStoreWrapper$1.invoke(NativeCredentialStoreWrapper.kt:26)
	at com.intellij.credentialStore.NativeCredentialStoreWrapper._init_$lambda$0(NativeCredentialStoreWrapper.kt:26)
	at com.intellij.util.concurrency.QueueProcessor.lambda$wrappingProcessor$0(QueueProcessor.java:84)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:253)
	at com.intellij.util.concurrency.QueueProcessor.lambda$wrappingProcessor$1(QueueProcessor.java:84)
	at com.intellij.util.concurrency.QueueProcessor.lambda$startProcessing$3(QueueProcessor.java:227)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:253)
	at com.intellij.util.concurrency.QueueProcessor.lambda$startProcessing$4(QueueProcessor.java:227)
	at com.intellij.util.concurrency.AppJavaExecutorUtil$executeOnPooledIoThread$1$1.invoke(executor.kt:23)
	at com.intellij.util.concurrency.AppJavaExecutorUtil$executeOnPooledIoThread$1$1.invoke(executor.kt:23)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:320)
	at com.intellij.openapi.progress.CoroutinesKt.access$blockingContextInner(coroutines.kt:1)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invokeSuspend(coroutines.kt:197)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:196)
	at com.intellij.util.concurrency.AppJavaExecutorUtil$executeOnPooledIoThread$1.invokeSuspend(executor.kt:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2024-04-19 11:12:56,992 [ 106815] SEVERE - #c.i.c.PasswordSafeSettings - PyCharm 2024.1  Build #PC-241.14494.241
2024-04-19 11:12:56,992 [ 106815] SEVERE - #c.i.c.PasswordSafeSettings - JDK: 17.0.10; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-04-19 11:12:56,992 [ 106815] SEVERE - #c.i.c.PasswordSafeSettings - OS: Linux
2024-04-19 11:12:58,396 [ 108219]   WARN - #c.i.s.ComponentManagerImpl - com.intellij.ui.jcef.JBCefApp$Holder <clinit> requests com.intellij.ui.jcef.JBCefAppCache instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.

(java:62576): Gtk-WARNING **: 11:12:58.642: gtk_disable_setlocale() must be called before gtk_init()
2024-04-19 11:13:01,451 [ 111274]   WARN - #ai.codium.webview.ChatWindowContentPanel - Webview not initialised within 3 sec.
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```

Related: https://github.com/Codium-ai/codiumai-jetbrains-release/issues/220

**Comment by ArtsiomCh** [comment]
Seems like password store been externally modified and seen as compromised by IDE
```
SEVERE - #c.i.c.PasswordSafeSettings - secret_password_store_sync error code 23, error message The file was externally modified
```

**Comment by stuz5000** [comment]
I see that.
However, I don't think my installation is exceptional.

**Comment by stuz5000** [comment]
See, installation by snap:
https://youtrack.jetbrains.com/issue/IJPL-4171/Intellij-idea-installed-via-Snap-does-not-have-access-to-keychain-e.g.-gnome-keyring

It seems this is resolvable automagically without the keychain though. When I click login with google, a browser is loaded and the login happens magically via the browser's storage. Perhaps relaunch the last login method via the browser at startup? Or advise your userbase to install intellj product outside of snap.

I wonder how vscode (also installable via snap) handles this?
