### ISSUE TITLE
[0.7.02][RUBYMINE 2022.3.3] com.intellij.diagnostic.PluginException: 574 ms to call on EDT CodiumToolWindowFactory$in...

### ISSUE THREAD

**Issue by jrae** [Codium-ai/codiumai-jetbrains-release#224]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
com.intellij.diagnostic.PluginException: 574 ms to call on EDT CodiumToolWindowFactory$init$1#update@ToolwindowTitle (ai.codium.ui.CodiumToolWindowFactory$init$1). Revise AnAction.getActionUpdateThread property [Plugin: codiumai.codiumai]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.computeOnEdt(ActionUpdater.java:255)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:203)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:161)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.updateActionReal(ActionUpdater.java:137)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$0(ActionUpdater.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.update(ActionUpdater.java:703)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:554)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$22(ActionUpdater.java:527)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1406)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:527)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:604)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$22(ActionUpdater.java:527)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1406)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:527)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:309)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$14(ActionUpdater.java:372)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$15(ActionUpdater.java:392)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1111)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$tryRunReadActionAndCancelBeforeWrite$19(ActionUpdater.java:424)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.tryRunReadActionAndCancelBeforeWrite(ActionUpdater.java:420)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$16(ActionUpdater.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgre

<TRIMMED STACKTRACE>

sactionGuardImpl.java:194)
		at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
		at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
		at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
		at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
		at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
		at com.intellij.openapi.application.impl.FlushQueue$$Lambda$414/0x00000003005988e8.run(Unknown Source)
		at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
		at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
		at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
		at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
		at java.base@17.0.6/java.security.AccessController.executePrivileged(AccessController.java:776)
		at java.base@17.0.6/java.security.AccessController.doPrivileged(AccessController.java:399)
		at java.base@17.0.6/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
		at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
		at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
		at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
		at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
		at com.intellij.ide.IdeEventQueue$$Lambda$394/0x0000000300567be8.compute(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
		at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
		at com.intellij.ide.IdeEventQueue$$Lambda$393/0x00000003005679a0.run(Unknown Source)
		at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
		at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
		at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
		at com.intellij.ide.IdeEventQueue$$Lambda$390/0x00000003005668e8.run(Unknown Source)
		at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
		at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
		at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
		at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
		at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
		at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
		at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

# Other Information
```
=== About ===
Build version: RubyMine 2022.3.3 Build: #RM-223.8836.42 March 10, 2023
Theme: Darcula
JRE: 17.0.6+1-b653.34, JetBrains s.r.o.
JVM: 17.0.6+1-b653.34, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 14.4.1 (aarch64)

=== Plugins ===
Custom plugins: [GitHub Copilot (1.4.2.3864), CodiumAI - Integrity Agent powered by GPT-3.5&4 (0.7.02)]
Disabled plugins:[Ember.js (2023.2.1), Sublime Text Keymap (231.7515.9)]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
0.7.02 is a way outdated plugin version.
Please update your IDE to at least 2023.1 (current release is 2024.1) and use latest plugin version (current 0.7.33)
