### ISSUE TITLE
[0.7.29][INTELLIJ IDEA IU 2024.1] provider: de.plushnikov.intellij.plugin.provider.LombokAugmentProvider@8094e26

### ISSUE THREAD

**Issue by nayimov** [Codium-ai/codiumai-jetbrains-release#227]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: PSI and index do not match.
Please report the problem to JetBrains with the files attached
 file=PsiJavaFile:CustomRequest.java, file.class=class com.intellij.psi.impl.source.PsiJavaFileImpl, file.lang=Language: JAVA, modStamp=2
 tree consistent
 stub debugInfo=created in getStubTree(), with AST = false; with backReference
 viewProvider=com.intellij.psi.SingleRootFileViewProvider{vFile=file://C:/Uzkassa/x-file-upgrade/src/main/java/uz/uzkassa/xfile/config/httpclient/CustomRequest.java, vFileId=477527, content=VirtualFileContent{size=6117}, eventSystemEnabled=true}
 viewProvider stamp: 43021; file stamp: 43021; file modCount: 1714969802151; file length: 6117
 doc saved: true; doc stamp: 43021; doc size: 5962; committed: true
indexing info: indexing timestamp = 1714969753525, binary = false, byte size = 6073, char size = 5962
ref: 50cf572587cf
latestIndexedStub=StubTree{myDebugInfo='created from index; with backReference', myRoot=PsiJavaFileStub [uz.uzkassa.xfile.config.httpclient]}1152673465
   same size=true
   debugInfo=created from index; with backReference
	at com.intellij.psi.stubs.StubTreeLoader$StubTreeAndIndexUnmatchCoarseException.doCreateCompleteException(StubTreeLoader.java:203)
	at com.intellij.psi.stubs.StubTreeLoader$StubTreeAndIndexUnmatchCoarseException.lambda$createCompleteException$0(StubTreeLoader.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:277)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:277)
	at com.intellij.psi.stubs.StubTreeLoader$StubTreeAndIndexUnmatchCoarseException.createCompleteException(StubTreeLoader.java:177)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:673)
	at com.intellij.psi.impl.source.SpineRef.getStub(SpineRef.java:27)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getStub(StubBasedPsiElementBase.java:332)
	at com.intellij.psi.impl.source.tree.java.PsiAnnotationImpl.getNameReferenceElement(PsiAnnotationImpl.java:37)
	at com.intellij.psi.impl.PsiImplUtil.findAnnotation(PsiImplUtil.java:295)
	at com.intellij.psi.impl.source.PsiModifierListImpl.findAnnotation(PsiModifierListImpl.java:307)
	at com.intellij.psi.PsiAnnotationOwner.hasAnnotation(PsiAnnotationOwner.java:44)
	at com.intelli

<TRIMMED STACKTRACE>

htingPassRegistrarImpl.java:186)
	at com.intellij.codeInsight.daemon.impl.TextEditorBackgroundHighlighter.getPasses(TextEditorBackgroundHighlighter.kt:65)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$submitInBackground$27(DaemonCodeAnalyzerImpl.java:1208)
	at com.intellij.openapi.application.impl.RwLockHolder.runReadAction(RwLockHolder.kt:289)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:850)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$submitInBackground$28(DaemonCodeAnalyzerImpl.java:1197)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.submitInBackground(DaemonCodeAnalyzerImpl.java:1194)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$queuePassesCreation$23(DaemonCodeAnalyzerImpl.java:1159)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:190)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.AssertionError: Cached PSI count doesn't match actual one
	at com.intellij.psi.impl.source.FileTrees.lambda$reconcilePsi$4(FileTrees.java:177)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:548)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:175)
	at com.intellij.psi.impl.source.FileTrees.withStub(FileTrees.java:147)
	at com.intellij.psi.impl.source.PsiFileImpl.setStubTree(PsiFileImpl.java:683)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:661)
	... 72 more

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2024.1 Build: #IU-241.14494.240 March 28, 2024
Theme: Darcula Solid
JRE: 17.0.10+8-b1207.12, JetBrains s.r.o.
JVM: 17.0.10+8-b1207.12, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 10.0 (amd64)

=== Plugins ===
Custom plugins: [Darcula Solid Theme (1.0.3), JetBrains AI Assistant (241.14494.240), Space (241.14494.150), Jakarta EE: Web Services (JAX-WS) (241.14494.158), Spring WebSocket (241.14494.158), Resource Bundle Editor (241.14494.150), Tabnine: AI Code Completion & Chat in Java JS/TS Python & More (1.83.0), JPA Buddy (241.14494.158), GraphQL (241.14494.150), Spring GraphQL (241.14494.158), Python (241.14494.240), Big Data Tools Core (241.14494.240), Big Data File Viewer (241.14494.158), Remote File Systems (241.14494.240), Codiumate - Code, test and review with confidence - by CodiumAI (0.7.29)]
Disabled plugins:[Kubernetes (241.15989.102)]
```

**Comment by aldanchenko** [comment]
Thanks for reporting! 
By stacktrace, seems like IDE internal error.
