### ISSUE TITLE
[Exception][PhpStorm 2023.1] java.lang.Throwable: Assert: must be called on EDT

### ISSUE THREAD

**Issue by Jomimorillo** [Codium-ai/codiumai-jetbrains-release#23]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable: Assert: must be called on EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.util.ui.EDT.assertIsEdt(EDT.java:68)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.show(ToolWindowImpl.kt:276)
	at com.intellij.openapi.wm.ToolWindow.show(ToolWindow.java:65)
	at ai.codium.ui.CodiumStatusBarWidget.showToolWindowIfNotLogged(CodiumStatusBarWidgetFactory.kt:53)
	at ai.codium.ui.CodiumStatusBarWidget.showToolWindowIfNotLogged$default(CodiumStatusBarWidgetFactory.kt:47)
	at ai.codium.ui.CodiumStatusBarWidget.<init>(CodiumStatusBarWidgetFactory.kt:61)
	at ai.codium.ui.CodiumStatusBarWidgetFactory.createWidget(CodiumStatusBarWidgetFactory.kt:32)
	at com.intellij.openapi.wm.StatusBarWidgetFactory.createWidget(StatusBarWidgetFactory.java:71)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetsManagerKt.createWidget(StatusBarWidgetsManager.kt:248)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetsManagerKt.access$createWidget(StatusBarWidgetsManager.kt:1)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetsManager.init$intellij_platform_ide_impl(StatusBarWidgetsManager.kt:202)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.init$intellij_platform_ide_impl(IdeStatusBarImpl.kt:273)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.init$intellij_platform_ide_impl$default(IdeStatusBarImpl.kt:270)
	at com.intellij.openapi.wm.impl.ProjectFrameHelper.installDefaultProjectStatusBarWidgets$suspendImpl(ProjectFrameHelper.kt:362)
	at com.intellij.openapi.wm.impl.ProjectFrameHelper.installDefaultProjectStatusBarWidgets(ProjectFrameHelper.kt)
	at com.intellij.openapi.project.impl.ProjectFrameAllocatorKt$initFrame$3.invokeSuspend(ProjectFrameAllocator.kt:387)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

# Other Information
```
=== About ===
Build version: PhpStorm 2023.1 Build: #PS-231.8109.199 March 29, 2023
Theme: Dark
JRE: 17.0.6+10-b829.5, JetBrains s.r.o.
JVM: 17.0.6+10-b829.5, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Linux 5.19.0-40-generic (amd64)

=== Plugins ===
Custom plugins: [CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.4.11), PHP Annotations (9.2.0), Symfony Support (2022.1.246)]
Disabled plugins:[GNU GetText files support (*.po) (231.8109.199), FTP/SFTP/WebDAV Connectivity (231.8109.199), Docker (231.8109.199), Karma (231.8109.199), PHP Remote Interpreter (231.8109.199), Code With Me (231.8109.199), Tailwind CSS (231.8109.199), SSH Remote Run (231.8109.199), Space (231.8109.199), Behat Support (231.8109.199), Angular and AngularJS (231.8109.199), Node.js (231.8109.199), Codeception Framework (231.8109.199), Cucumber.js (231.8109.199), Vagrant (231.8109.199), WordPress (231.8109.199), PHP Docker (231.8109.199), Drupal (231.8109.199), Webpack (231.8109.199), Vue.js (231.8109.199), Node.js Remote Interpreter (231.8109.199), Gherkin (231.8109.199), Translation (3.4.2), Next.js Support (231.8109.199), Qodana (231.8109.199), Joomla! (231.8109.199), GitHub (231.8109.199)]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/5dSa0Z52) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Issue will be fixed in next release.
