### ISSUE TITLE
[0.7.36][INTELLIJ IDEA IU 2023.1.3] kotlin.UninitializedPropertyAccessException: lateinit property jbCefBrowser has n...

### ISSUE THREAD

**Issue by Bex230** [Codium-ai/codiumai-jetbrains-release#236]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
kotlin.UninitializedPropertyAccessException: lateinit property jbCefBrowser has not been initialized
	at ai.codium.webview.WebviewPluginBridge.sendMessageJson(WebviewPluginBridge.kt:75)
	at ai.codium.webview.WebviewPluginBridge.sendMessage(WebviewPluginBridge.kt:94)
	at ai.codium.ui.actions.AddSnippetAsContextMenuAction.actionPerformed(AddSnippetAsContextMenuAction.kt:34)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:333)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:307)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:356)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:307)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$performAction$5(ActionMenuItem.java:299)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:225)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.java:292)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$0(ActionMenuItem.java:67)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$4(ActionMenuItem.java:114)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.imp

<TRIMMED STACKTRACE>

ess$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2023.1.3 Build: #IU-231.9161.38 June 20, 2023
Theme: Gerry Dark
JRE: 17.0.7+10-b829.16, JetBrains s.r.o.
JVM: 17.0.7+10-b829.16, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [JSTestDriver Plugin (202.5), Context Free Grammar (0.3.1), Writerside (2023.06.3869), Inspection Compare Plugin (1.02), Sapient AI Test Coder (2024.2.38), Cyan Light Theme (1.3), ChatGPT - EasyCode (3.3.1-231.233), ReStructuredText (231.8770.3), Minecraft Development (2023.1-1.6.12), Codiumate - Code, test and review with confidence - by CodiumAI (0.7.36), Maven Helper (4.28.0-IJ2022.2), Cap-Basic (2022.3.1), ChatGPT Integration (0.2.12-231), Machinet AI GPT-4 Chat and Unit Tests (2022.1.66), Smart-Commit (1.2.3), Plugin Importer+Exporter (0.0.3), Python (231.9011.34), PlantUML Diagram Generator (2022.2.0), Cute Pink Light Theme (0.9.0), Rainbow CSV (2.0.2), CMD Support (1.0.5), Google Search (0.0.2), PHP (231.9011.38), AI Coding Assistant (1.2.22), Kotlin (231-1.9.21-release-633-IJ8109.175), EnvFile (3.4.1), Espresso Lightgram (1.0.3.1), AskCodi (4.5), Ideolog (222.2.0.0), Ini (231.9011.41), Makefile Language (231.8109.91), SonarLint (10.5.0.78339), Spring Shell (231.8109.90), Cap-Basic-BigData (2022.2), Gerry Themes (2023.1.82), Space Theme (1.0.231018), SequenceDiagram (3.0.7), ChatGPT GPT-4 - Bito AI Code Assistant (1.3.2), Gray Theme (1.3), .env files support (2023.1), InnerBuilder (1.3.0), Batch Scripts Support (1.0.13), Gradianto (5.5), PlantUML Integration (6.5.0-IJ2022.2), AWS Toolkit - Amazon Q, CodeWhisperer, and more (2.17-231), Jakarta EE: Batch Applications (231.8109.90), Rainbow Brackets (2023.3.7), GDScript (0.35.0), Jakarta EE: Web Services (JAX-WS) (231.8109.90), String Manipulation (9.12.0), Dart (231.9065), Tabnine: AI Code Completion & Chat in Java JS/TS Python & More (1.85.0), JPA Buddy (2023.3.5-231), Rider UI Theme Pack (0.14.11), Espresso Light Theme (1.2.0), Apache config (.htaccess) (231.9011.41), Tranquil Light Theme (1.0.2), Developer Tools (1.0.1), Spring Batch (231.8770.17), Compare Tab With Editor 2 (1.0.16), One Dark Theme (5.10.0)]
Disabled plugins:[Eclipse Keymap (231.9161.38), Roboticket Light Theme (1.1.3), WildFly (231.9161.38), Visual Studio Keymap (231.9161.38), Velocity (231.9161.38), Qodana (231.9161.38), Codeium: AI Autocomplete and Chat for Python, JS, Java, Go... (1.8.31), Shared Project Caches (231.9161.38), Jakarta EE: Application Servers (231.9161.38), IDE Features Trainer (231.9161.38), FreeMarker (231.9161.38), Android Design Tools (231.9161.38), Tomcat and TomEE (231.9161.38), Nim (1.5.3-223), Shared Project Indexes (231.9161.38), qubTheme (1.2), GlassFish (231.9161.38), macOS Light Theme (231.8109.91), Mercurial (231.9161.38), Space (231.9161.38), Diagrams (231.9161.38), Perforce Helix Core (231.9161.38), Jakarta EE: Server Pages (JSP) (231.9161.38), NetBeans Keymap (231.9161.38), KS-Explorer (2023.1.6), JetBrains Academy (2023.11-2023.1-2235), Integration Testing of Workspace Model (231.9161.38)]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Fixed in 0.7.37
