### ISSUE TITLE
[0.7.36][WEBSTORM 2024.1] okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL

### ISSUE THREAD

**Issue by sabuhiteymurov** [Codium-ai/codiumai-jetbrains-release#237]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:355)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:281)
	at okio.Buffer.writeAll(Buffer.kt:1308)
	at okio.RealBufferedSource.readString(RealBufferedSource.kt:97)
	at okhttp3.ResponseBody.string(ResponseBody.kt:187)
	at ee.carlrobert.llm.completion.CompletionEventSourceListener.onFailure(CompletionEventSourceListener.java:107)
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:52)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

# Other Information
```
=== About ===
Build version: WebStorm 2024.1 Build: #WS-241.14494.235 March 27, 2024
Theme: One Dark Darker
JRE: 17.0.10+8-b1207.12, JetBrains s.r.o.
JVM: 17.0.10+8-b1207.12, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [json2ts (1.0.12), Atom One Theme (1.5.1), Excalidraw Integration (0.4.0), One Dark Theme (5.10.0), One Dark Darker (1.3.8), Key Promoter X (2024.1.0), Modern React Snippets (1.0.3), .env files support (2024.1), GitHub Actions Manager (2024.1.2), GitHub Copilot (1.5.4.5571), Database Tools and SQL for WebStorm (241.14494.180), Nx Console (1.24.0), GraphQL (241.14494.150), React Buddy (241.14494.140), Codiumate - Code, test and review with confidence - by CodiumAI (0.7.36), CodeGPT (2.7.1-241), Atom Material Icons (97.0.0), GitToolBox (500.2.7+233), Rainbow Brackets (2024.2.3-241)]
Disabled plugins:[JsonToTypeScript (2023.1.2), Tailwind CSS (241.14494.235), Angular (241.14494.235), Less (241.14494.235), JetBrains AI Assistant (241.15989.195), Mercurial (241.14494.235), Subversion (241.14494.235), Vue.js (241.14494.235), Space (241.15989.9), Webpack (241.14494.235)]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Third party plugin issue: `ee.carlrobert.llm`
