### ISSUE TITLE
[0.7.33][INTELLIJ IDEA IU 2023.3.2] java.lang.Throwable: All stub element types should be created before index initia...

### ISSUE THREAD

**Issue by ninkovic-consulting** [Codium-ai/codiumai-jetbrains-release#238]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable: All stub element types should be created before index initialization is complete.
Please add the class org.jetbrains.kotlin.psi.stubs.elements.KtDotQualifiedExpressionElementType with external ID kotlin.DOT_QUALIFIED_EXPRESSION containing stub element type constants to "stubElementTypeHolder" extension.
Registered extensions: [com.intellij.util.xml.stubs.DomElementTypeHolder, com.intellij.protobuf.lang.stub.type.PbStubElementTypes, com.intellij.psi.css.impl.CssStubElementTypes, org.jetbrains.plugins.less.LessStubElementTypes, org.intellij.plugins.postcss.PostCssStubElementTypes, org.jetbrains.plugins.stylus.psi.StylusStubElementTypes, org.jetbrains.plugins.scss.ScssStubElementTypes, org.jetbrains.plugins.sass.psi.SassStubElementTypes, org.intellij.plugins.markdown.lang.MarkdownStubElementTypes, com.intellij.lang.properties.parsing.PropertiesElementTypes, com.intellij.psi.impl.java.stubs.JavaStubElementTypes, org.jetbrains.plugins.groovy.lang.parser.GroovyStubElementTypes, org.jetbrains.plugins.groovy.lang.parser.GroovyEmptyStubElementTypes, org.jetbrains.kotlin.psi.stubs.elements.KtStubElementTypes, com.intellij.lang.javascript.JSStubElementTypes, com.intellij.lang.typescript.TypeScriptStubElementTypes, com.intellij.lang.javascript.flow.FlowJSStubElementTypes, com.intellij.lang.javascript.frameworks.jquery.JQueryCssStubElementTypes, com.intellij.lang.actionscript.ActionScriptStubElementTypes, com.intellij.lang.ecmascript6.ES6StubElementTypes, org.jetbrains.vuejs.lang.expr.parser.VueJSStubElementTypes, org.jetbrains.vuejs.lang.html.parser.VueStubElementTypes, com.intellij.httpClient.js.http.request.language.HttpClientJSEmbeddedContent, com.intellij.sql.psi.SqlCompositeElementTypes, com.intellij.sql.dialects.sql92.Sql92ElementTypes$Stubs, com.intellij.sql.dialects.cassandra.CassElementTypes$Stubs, com.intellij.sql.dialects.clickhouse.CHouseElementTypes$Stubs, com.intellij.sql.dialects.db2.Db2ElementTypes$Stubs, com.intellij.sql.dialects.derby.DerbyElementTypes$Stubs, com.intellij.sql.dialects.exasol.ExaElementTypes$Stubs, com.intellij.sql.dialects.greenplum.GPlumElementTypes$Stubs, com.intellij.sql.dialects.h2.H2ElementTypes$Stubs, com.intellij.sql.dialects.hive.HiveElementTypes$Stubs, com.intellij.sql.dialects.hsql.HsqlElementTypes$Stubs, com.intellij.sql.dialects.mssql.MsElementTypes$Stubs, com.intellij.sql.dialects.mysql.MysqlElementTypes$Stubs, com.intellij.sql.dialects.oracle.OraElementTypes$Stubs, com.intellij.sql.dialects.oraplus.OraPlusElementTypes$Stubs, com.intellij.sql.dialects.postgres.PgElementTypes$Stubs, com.intellij.sql.dialects.redshift.RsElementTypes$Stubs, com.intellij.sql.dialects.snowflake.SFlakeElementTypes$Stubs, com.intellij.sql.dialects.sqlite.SqliteEle

<TRIMMED STACKTRACE>

default(LanguageServiceFactory.kt:10)
	at ai.codium.language.LanguageServiceFactory.<clinit>(LanguageServiceFactory.kt:23)
	at ai.codium.UtilsKt.getLanguageService(Utils.kt:80)
	at ai.codium.CodiumInlayProvider.getCollectorFor(CodiumInlayProvider.kt:75)
	at ai.codium.CodiumInlayProvider.getCollectorFor(CodiumInlayProvider.kt:34)
	at com.intellij.codeInsight.hints.InlayHintsUtilsKt.getCollectorWrapperFor(InlayHintsUtils.kt:50)
	at com.intellij.codeInsight.daemon.impl.InlayHintsPassFactoryInternal.createHighlightingPass(InlayHintsPassFactoryInternal.kt:46)
	at com.intellij.codeInsight.daemon.impl.TextEditorHighlightingPassRegistrarImpl.instantiatePasses(TextEditorHighlightingPassRegistrarImpl.java:186)
	at com.intellij.codeInsight.daemon.impl.TextEditorBackgroundHighlighter.getPasses(TextEditorBackgroundHighlighter.kt:65)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$submitInBackground$25(DaemonCodeAnalyzerImpl.java:1163)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$submitInBackground$26(DaemonCodeAnalyzerImpl.java:1152)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.submitInBackground(DaemonCodeAnalyzerImpl.java:1149)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$queuePassesCreation$21(DaemonCodeAnalyzerImpl.java:1114)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:187)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2023.3.2 Build: #IU-233.13135.103 December 20, 2023
Theme: Dark
JRE: 17.0.9+7-b1087.9, JetBrains s.r.o.
JVM: 17.0.9+7-b1087.9, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 14.5 (aarch64)

=== Plugins ===
Custom plugins: [Codiumate - Code, test and review with confidence - by CodiumAI (0.7.33), Big Data Tools Core (233.13135.103), AI Assistant (233.13135.116), Stylus (233.11799.172), Nest (1.2.26), PHP (233.13135.108), Dart (233.15123), Flutter (78.4.2), AWS Core (3.5-233), Big Data File Viewer (233.11799.267), Spring WebSocket (233.11799.196), Statistic (4.2.14), Prisma ORM (233.13135.65), Flutter Snippets (2.0.0-stable-1), EnvFile (3.4.2), Android (233.13135.106), AWS Toolkit (3.5-233), Nginx Configuration (2022.1.1), .ignore (4.5.3), Remote File Systems (233.13135.103)]
Disabled plugins:[Nx Console (1.21.0), Redis (2023.10.28), Add to gitignore (0.3)]
```

**Comment by ArtsiomCh** [comment]
> Codiumate - Code, test and review with confidence - by CodiumAI (0.7.33)

please update to the latest plugin version
