### ISSUE TITLE
[0.9.2][PHPSTORM 2024.1] java.lang.Throwable: Invalid file

### ISSUE THREAD

**Issue by Muetze42** [Codium-ai/codiumai-jetbrains-release#258]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable: Invalid file: file://C:/xampp/htdocs/resources/js/store.ts (invalid)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:371)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:163)
	at com.intellij.psi.impl.file.impl.ResolveScopeManagerImpl.getDefaultResolveScope(ResolveScopeManagerImpl.java:160)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil.getResolveScope(JSResolveUtil.java:503)
	at com.intellij.lang.typescript.tsconfig.TypeScriptConfigService$Provider.getConfigResolveScope(TypeScriptConfigService.java:53)
	at com.intellij.lang.typescript.resolve.TypeScriptClassResolver.getGlobalTypeScriptScopeForJsOrTs(TypeScriptClassResolver.java:182)
	at com.intellij.lang.typescript.resolve.TypeScriptClassResolver.findGlobalElementsByQName(TypeScriptClassResolver.java:136)
	at com.intellij.lang.typescript.TypeScriptResolveHelper.processGlobalThings(TypeScriptResolveHelper.java:119)
	at com.intellij.lang.javascript.ecmascript6.TypeScriptReferenceExpressionResolver.doResolveReference(TypeScriptReferenceExpressionResolver.java:116)
	at com.intellij.lang.javascript.ecmascript6.TypeScriptReferenceExpressionResolver.resolve(TypeScriptReferenceExpressionResolver.java:76)
	at com.intellij.lang.javascript.ecmascript6.TypeScriptReferenceExpressionResolver.resolve(TypeScriptReferenceExpressionResolver.java:33)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$5.get(JSResolveUtil.java:1664)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$5.get(JSResolveUtil.java:1661)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluatorComplexityTracker.runTask(JSEvaluatorComplexityTracker.java:67)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.lambda$getCachedValue$0(JSComplexityAwareRecursionGuard.java:68)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$4.lambda$calculateWithCaching$0(JSResolveUtil.java:1677)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$5(ResolveCache.java:268)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:234)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:213)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:268)
	at com.intellij.lang.javascript.psi.resolve.J

<TRIMMED STACKTRACE>

oke(TestWebviewRequestDispatcher.kt:57)
	at ai.codium.webview.generateTest.TestWebviewRequestDispatcher$handleRequest$1.invoke(TestWebviewRequestDispatcher.kt:46)
	at ai.codium.UtilsKt$runBackgroundTask$4.run(Utils.kt:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:528)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:250)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:250)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:500)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

# Other Information
```
=== About ===
Build version: PhpStorm 2024.1 Build: #PS-241.14494.237 March 27, 2024
Theme: Darcula
JRE: 17.0.10+8-b1207.12, JetBrains s.r.o.
JVM: 17.0.10+8-b1207.12, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [Mario Progress Bar (1.9), Git Commit Message Helper (1.4.2), Codeium: AI Autocomplete and Chat for Python, JS, Java, Go... (1.10.11), Lorem Ipsum Generator (1.1), GitHub Markdown Emojis (1.3.4), PHPStan Toolbox (0.0.7), .env files support (2024.1), NEON support (0.5.4), Laravel Tinker (2.7.3), PHP Annotations (10.0.0), MJML Support (3.3.1), Symfony Support (2024.1.274), IntelliVue (1.2.4), Laravel Idea (8.2.2.241), Codiumate - Code, test and review with confidence - by CodiumAI (0.9.2), Automatic GitHub Issue Navigation Configuration (2.0.4), Atom Material Icons (97.0.0), Shopware 6 Toolbox (0.0.43), .ignore (4.5.3)]
Disabled plugins:[Markdown Editor (2.0.5), JSON Sorter (1.0.0-beta.3.4), Mercurial (241.14494.237), Code With Me (241.14494.237), CodeGPT (2.6.3-241), Laravel Generator (3.1.9), 3v4l Integration (241.14494.237)]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Seems like issue is inside IDE references resolving. Try to restart your IDE. If issue persist contact JetBrains and send them stacktrace.
