### ISSUE TITLE
[0.9.2][INTELLIJ IDEA IU 2024.2] Failed to convert com.intellij.ui.components.JBScrollPane[,1,29,632x179,invalid,layo...

### ISSUE THREAD

**Issue by N6REJ** [Codium-ai/codiumai-jetbrains-release#260]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.TypeNotPresentException: Type org.jetbrains.plugins.notebooks.ui.visualization.NotebookAboveCellDelimiterPanel not present
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at java.base/sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at java.base/sun.reflect.generics.repository.ClassRepository.computeSuperInterfaces(ClassRepository.java:117)
	at java.base/sun.reflect.generics.repository.ClassRepository.getSuperInterfaces(ClassRepository.java:95)
	at java.base/java.lang.Class.getGenericInterfaces(Class.java:1296)
	at com.jetbrains.rdserver.extension.GenericClassExtensionPoint.inferKeyFromTypeArgument(GenericClassExtensionPoint.kt:33)
	at com.jetbrains.rdserver.extension.GenericClassExtensionPoint.getKey(GenericClassExtensionPoint.kt:29)
	at com.intellij.openapi.util.ClassExtension.lambda$buildExtensionsWithInheritance$1(ClassExtension.java:40)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensionsFromExtensionPoint(KeyedExtensionCollector.java:158)
	at com.intellij.openapi.util.ClassExtension.buildExtensionsWithInheritance(ClassExtension.java:40)
	at com.intellij.openapi.util.ClassExtension.buildExtensions(ClassExtension.java:29)
	at com.intellij.openapi.util.ClassExtension.buildExtensions(ClassExtension.java:15)
	at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:112)
	at com.intellij.openapi.util.KeyedExtensionCollector.findSingle(KeyedExtensionCollector.java:126)
	at com.intellij.openapi.util.ClassExtension.forClass(ClassExtension.java:59)
	at com.jetbrains.rdserver.ui.converters.RdConverterRegistry$Companion.convert(ConverterRegistry.kt:45)
	at com.jetbrains.rdserver.ui.converters.RdConverterRegistry$Companion.convert(ConverterRegistry.kt:59)
	at com.jetbrains.rdserver.ui.converters.RdConverterRegistry.toBeModel(ConverterRegistry.kt:85)
	at com.jetbrains.rdserver.ui.converters.ConverterRegistryKt.toBeModel(ConverterRegistry.kt:129)
	at com.jetbrains.rdserver.ui.popup.settings.BePopupContentProvider.getBeModel(BePopupContentProvider.kt:45)
	at com.jetbrains.rdserver.ui.popup.settings.BePopupContentProvider.getPopupContent(BePopupContentProvider.kt:30)
	a

<TRIMMED STACKTRACE>

.compiler.charts, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\lib, version=242.20224.300, package=null, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.vcs, descriptorPath=intellij.java.vcs.xml, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\java, version=242.20224.300, package=null, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.unscramble, descriptorPath=intellij.java.unscramble.xml, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\java, version=242.20224.300, package=null, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.featuresTrainer, descriptorPath=intellij.java.featuresTrainer.xml, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\java, version=242.20224.300, package=null, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.structuralSearch, descriptorPath=intellij.java.structuralSearch.xml, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\java, version=242.20224.300, package=null, isBundled=true), PluginDescriptor(name=Python, id=Pythonid, moduleName=intellij.python.core.impl, descriptorPath=intellij.python.core.impl.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2024.2\plugins\python, version=242.20224.300, package=null, isBundled=false), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, descriptorPath=plugin.xml, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\markdown, version=242.20224.300, package=org.intellij.plugins.markdown, isBundled=true), PluginDescriptor(name=Python, id=Pythonid, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2024.2\plugins\python, version=242.20224.300, package=PythonId, isBundled=false), PluginDescriptor(name=Java, id=com.intellij.java, descriptorPath=plugin.xml, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\java, version=242.20224.300, package=null, isBundled=true), )
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:157)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	... 166 more

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2024.2 Build: #IU-242.20224.300 August 6, 2024
Theme: Darcula
JRE: 21.0.3+13-b509.4, JetBrains s.r.o.
JVM: 21.0.3+13-b509.4, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [Ini (242.20224.203), Classic UI (242.20224.159), Batch Scripts Support (1.0.13), Gerry Themes (2024.1.0724), Nyan Progress Bar (1.15), Python Community Edition (242.20224.300), Trash Panda Theme (1.6), Space (242.20224.155), VBScript (0.5.0), Python (242.20224.300), Codiumate - Code, test and review with confidence - by CodiumAI (0.9.2), PHP (242.20224.300), Rainbow Brackets (2024.2.6-241)]
Disabled plugins:[WSL Support Framework (242.20224.300), Tomcat and TomEE (242.20224.300), FTP/SFTP/WebDAV Connectivity (242.20224.300), Kubernetes (242.20224.300), Docker (242.20224.300), WildFly (242.20224.300), SSH Remote Run (242.20224.300), Dev Containers (242.20224.300), Ktor (242.20224.300), Remote Execution Agent (242.20224.300), Node.js Remote Interpreter (242.20224.300), Jakarta EE: Application Servers (242.20224.300), Kotlin (242.20224.300-IJ)]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Seems to be internal IDE glitch
Let us know if it happened again
