### ISSUE TITLE
[0.9.3][WEBSTORM 2024.2.0.1] https://identitytoolkit.googleapis.com/: no proxy, failed to get proxy configuration

### ISSUE THREAD

**Issue by dicolasi** [Codium-ai/codiumai-jetbrains-release#279]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.net.MalformedURLException: no protocol: zsc-man1-1d6-sme
	at java.base/java.net.URL.<init>(URL.java:772)
	at java.base/java.net.URL.<init>(URL.java:654)
	at java.base/java.net.URL.<init>(URL.java:590)
	at com.intellij.util.net.internal.HttpConfigurableMigrationUtilsKt.getProxyConfiguration(httpConfigurableMigrationUtils.kt:28)
	at com.intellij.util.net.internal.HttpConfigurableToProxySettingsAdapter.getProxyConfiguration(httpConfigurableMigrationUtils.kt:114)
	at com.intellij.util.net.ProxySettingsCompatibilityImpl.getProxyConfiguration(ProxySettingsCompatibilityImpl.kt)
	at com.intellij.util.net.OverrideCapableProxySettings.getProxyConfiguration(OverrideCapableProxySettings.kt:24)
	at com.intellij.util.net.PlatformJdkProxyProviderKt.asProxyConfigurationProvider$lambda$0(PlatformJdkProxyProvider.kt:15)
	at com.intellij.util.net.IdeProxySelector.select(IdeProxySelector.kt:39)
	at com.intellij.util.net.CustomizedPlatformJdkProxyProvider$CustomizedProxySelector.select(CustomizedPlatformJdkProxyProvider.kt:60)
	at com.intellij.util.proxy.CommonProxy.select(CommonProxy.java:196)
	at okhttp3.internal.connection.RouteSelector.resetNextProxy$selectProxies(RouteSelector.kt:106)
	at okhttp3.internal.connection.RouteSelector.resetNextProxy(RouteSelector.kt:113)
	at okhttp3.internal.connection.RouteSelector.<init>(RouteSelector.kt:53)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:202)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connecti

<TRIMMED STACKTRACE>

ess.ProgressManager.lambda$runProcess$0(ProgressManager.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:49)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:96)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:249)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:501)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:466)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:92)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:92)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:97)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:92)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:464)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

# Other Information
```
=== About ===
Build version: WebStorm 2024.2.0.1 Build: #WS-242.20224.426 August 21, 2024
Theme: Dark
JRE: 21.0.3+13-b509.4, JetBrains s.r.o.
JVM: 21.0.3+13-b509.4, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 14.5 (x86_64)

=== Plugins ===
Custom plugins: [Twig (242.20224.428), Space (242.20224.155), GitHub Copilot (1.5.20.6554), .ignore (4.5.3), GraphQL (242.20224.155), Deno (242.20224.155), Svelte (242.20224.155), Codiumate - Code, test and review with confidence - by CodiumAI (0.9.3)]
Disabled plugins:[Live Edit (242.20224.426), Angular (242.20224.426), Dev Containers (242.20224.426), Vue.js (242.20224.426), Run Configuration for TypeScript (2024.08.16-1), Styled Components & Styled JSX (242.20224.426), Force Shortcuts (0.4), Eclipse Keymap (242.20224.426), JetBrains AI Assistant (242.20224.393), NetBeans Keymap (242.20224.426), Vagrant (242.20224.426), SSH Remote Run (242.20224.426), Node.js Remote Interpreter (242.20224.426), PostCSS (242.20224.426), VSCode Keymap (242.20224.426), Sass (242.20224.426), Machine Learning in Search Everywhere (242.20224.426), Webpack (242.20224.426), Refactor-X (242.20224.426), Machine Learning Code Completion (242.20224.426), Tailwind CSS (242.20224.426), Less (242.20224.426), FTP/SFTP/WebDAV Connectivity (242.20224.426), Kubernetes (242.20224.175), Next.js (242.20224.426), Visual Studio Keymap (242.20224.426), Settings Sync (242.20224.426), HTML Tools (242.20224.426)]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Seems to be internal IDE glitch
Let us know if it happened again
