### ISSUE TITLE
[0.9.3][INTELLIJ IDEA IU 2023.2.6] *** exception class was changed or removed

### ISSUE THREAD

**Issue by abch98ru** [Codium-ai/codiumai-jetbrains-release#290]
# User Description
just first click on "Test this method"

# Stack Trace
```
   Unhandled exception in [CoroutineName(com.jetbrains.rdserver.toolWindow.BackendServerToolWindowManager), ModalityState.NON_MODAL, StandaloneCoroutine{Cancelling}@1208cf4b, Dispatchers.EDT]
   
   java.lang.RuntimeException: Cannot invoke (class=, method=newWebviewTestPanel, topic=Codium UX (business logic) events)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:676)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:422)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:401)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:460)
	at jdk.proxy9/jdk.proxy9.$Proxy253.newWebviewTestPanel(Unknown Source)
	at ai.codium.GenerationManager$Companion.generateTests$lambda$2(GenerationManager.kt:51)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$invokeLater$1.invokeSuspend(ToolWindowManagerImpl.kt:1409)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.application.impl.DispatchedRunnable.run(DispatchedRunnable.kt:43)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at

**Comment by abch98ru** [comment]
although, think the new bright Codium does not support Idea 2023. :( :)
