### ISSUE TITLE
[0.9.3][JETBRAINS RIDER 2024.2.3] Must be executed on UI thread or background threads with special permissions

### ISSUE THREAD

**Issue by Matthew-Oduamafu** [Codium-ai/codiumai-jetbrains-release#291]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.IllegalStateException: |E| Wrong thread RdOptionalProperty: `RiderBackend 1.ClipboardModel.content`
	at com.jetbrains.rdclient.protocol.RdDispatcher.assertThread(RdDispatcher.kt:72)
	at com.jetbrains.rd.framework.base.RdReactiveBase.assertThreading(RdReactiveBase.kt:28)
	at com.jetbrains.rd.framework.base.RdReactiveBase.localChange$rd_framework(RdReactiveBase.kt:43)
	at com.jetbrains.rd.framework.impl.RdOptionalProperty.set(RdProperty.kt:204)
	at com.jetbrains.rider.editors.RiderCopyPasteManager.B(RiderCopyPasteManager.kt:26)
	at com.jetbrains.rider.editors.RiderCopyPasteManager.setContents(RiderCopyPasteManager.kt:21)
	at com.intellij.ide.CopyPasteManagerEx.setContents(CopyPasteManagerEx.java:51)
	at ai.codium.UtilsKt$copyToClipboard$1.invoke(Utils.kt:574)
	at ai.codium.UtilsKt$copyToClipboard$1.invoke(Utils.kt:573)
	at com.intellij.openapi.application.ActionsKt.runReadAction$lambda$3(actions.kt:31)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction$lambda$3(AnyThreadWriteThreadingSupport.kt:219)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:264)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:219)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:852)
	at com.intellij.openapi.application.ActionsKt.runReadAction(actions.kt:31)
	at ai.codium.UtilsKt.copyToClipboard(Utils.kt:573)
	at ai.codium.webview.generateTest.TestWebviewBaseCommandDispatcher.dispatch(TestWebviewBaseCommandDispatcher.kt:197)
	at ai.codium.webview.generateTest.TestWebviewPluginBridge.postMessage(TestWebviewPluginBridge.kt:48)
	at ai.codium.webview.generateTest.TestWebviewPluginBridge.access$postMessage(TestWebviewPluginBridge.kt:22)
	at ai.codium.webview.generateTest.TestWebviewPluginBridge$1$1.invoke(TestWebviewPluginBridge.kt:34)
	at ai.codium.webview.generateTest.TestWebviewPluginBridge$1$1.invoke(TestWebviewPluginBridge.kt:34)
	at ai.codium.webview.generateTest.TestWebviewPluginBridge.lambda$1$lambda$0(TestWebviewPluginBridge.kt:34)
	at com.intellij.ui.jcef.JBCefJSQuery$1.onQuery(JBCefJSQuery.java:123)

```

# Other Information
```
=== About ===
Build version: JetBrains Rider 2024.2.3 Build: #RD-242.21829.166 August 29, 2024
Theme: Light Flat
JRE: 21.0.3+13-b509.11, JetBrains s.r.o.
JVM: 21.0.3+13-b509.11, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 14.6.1 (aarch64)

=== Plugins ===
Custom plugins: [Extra ToolWindow Colorful Icons (2024.4.1), Developer Tools (5.0.0), Heap Allocations Viewer (2024.2.0), Intellify (0.0.7), AWS Core (3.26-242), Space (242.21829.142), Light Flat Theme (0.14), NSubstituteComplete (2024.2.0), CognitiveComplexity (2024.2.0), Application Insights Debug Log Viewer (2024.2.0), String Manipulation (9.14.1), Key Promoter X (2024.2.0), JetBrains AI Assistant (242.21829.142), Grazie Pro (0.3.326), Battery Status (2.4), GitHub Actions Manager (2024.2.8), Amazon Q (3.26-242), Big Data Tools Core (242.21829.142), Kafka (242.20224.159), Big Data File Viewer (242.20224.159), Remote File Systems (242.21829.142), JetClient - The Ultimate REST Client (2024.3.8-242), GitHub Copilot (1.5.20.6554), New Relic CodeStream (15.14.0+556), SonarLint (10.8.1.79205), Codiumate - Code, test and review with confidence - by CodiumAI (0.9.3), Atom Material Icons (97.0.0), GitToolBox (500.2.15+242), Roboticket Light Theme (1.1.3), Azure Toolkit for Rider (4.1.0), AWS Toolkit (3.26-242)]
Disabled plugins:[Extra Icons (2024.4.2)]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Should be fixed in latest 0.9.5
Let us know if it happened again
