### ISSUE TITLE
[0.9.3][JETBRAINS RIDER 2024.2.2] Must be executed on UI thread or background threads with special permissions

### ISSUE THREAD

**Issue by diegochiodini** [Codium-ai/codiumai-jetbrains-release#297]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.IllegalStateException: |E| Wrong thread RdOptionalProperty: `RiderBackend 0.ClipboardModel.content`
	at com.jetbrains.rdclient.protocol.RdDispatcher.assertThread(RdDispatcher.kt:72)
	at com.jetbrains.rd.platform.protocol.SwitchingScheduler.assertThread(SwitchingScheduler.kt:22)
	at com.jetbrains.rd.framework.base.RdReactiveBase.assertThreading(RdReactiveBase.kt:28)
	at com.jetbrains.rd.framework.base.RdReactiveBase.localChange$rd_framework(RdReactiveBase.kt:43)
	at com.jetbrains.rd.framework.impl.RdOptionalProperty.set(RdProperty.kt:204)
	at com.jetbrains.rider.editors.RiderCopyPasteManager.a(RiderCopyPasteManager.kt:26)
	at com.jetbrains.rider.editors.RiderCopyPasteManager.setContents(RiderCopyPasteManager.kt:21)
	at com.intellij.ide.CopyPasteManagerEx.setContents(CopyPasteManagerEx.java:51)
	at ai.codium.UtilsKt$copyToClipboard$1.invoke(Utils.kt:574)
	at ai.codium.UtilsKt$copyToClipboard$1.invoke(Utils.kt:573)
	at com.intellij.openapi.application.ActionsKt.runReadAction$lambda$3(actions.kt:31)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction$lambda$3(AnyThreadWriteThreadingSupport.kt:219)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:264)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:219)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:852)
	at com.intellij.openapi.application.ActionsKt.runReadAction(actions.kt:31)
	at ai.codium.UtilsKt.copyToClipboard(Utils.kt:573)
	at ai.codium.webview.chat.ChatWebviewBaseCommandDispatcher.dispatch(ChatWebviewBaseCommandDispatcher.kt:81)
	at ai.codium.webview.chat.ChatWebviewPluginBridgeService.postMessage(ChatWebviewPluginBridge.kt:47)
	at ai.codium.webview.chat.ChatWebviewPluginBridgeService.access$postMessage(ChatWebviewPluginBridge.kt:22)
	at ai.codium.webview.chat.ChatWebviewPluginBridgeService$initInstance$1$1.invoke(ChatWebviewPluginBridge.kt:33)
	at ai.codium.webview.chat.ChatWebviewPluginBridgeService$initInstance$1$1.invoke(ChatWebviewPluginBridge.kt:33)
	at ai.codium.webview.chat.ChatWebviewPluginBridgeService.initInstance$lambda$1$lambda$0(ChatWebviewPluginBridge.kt:33)
	at com.intellij.ui.jcef.JBCefJSQuery$1.onQuery(JBCefJSQuery.java:123)

```

# Other Information
```
=== About ===
Build version: JetBrains Rider 2024.2.2 Build: #RD-242.20224.431 August 24, 2024
Theme: Dark
JRE: 21.0.3+13-b509.4, JetBrains s.r.o.
JVM: 21.0.3+13-b509.4, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [Ideolog (242.20224.428), Rider Android Support (242.20224.431), todo4me (1.4), Heap Allocations Viewer (2024.2.0), Solarized Themes (2.4.0), Codiumate - Code, test and review with confidence - by CodiumAI (0.9.3)]
Disabled plugins:[Live Edit (242.20224.431), Stylelint (242.20224.431), Angular (242.20224.431), React (242.20224.431), Polymer & Web Components (242.20224.431), Dev Containers (242.20224.431), Remote Execution Agent (242.20224.431), Subversion (242.20224.431), Vue.js (242.20224.431), Support for publishing to custom servers (242.20224.431), Git (242.20224.431), Perforce Helix Core (242.20224.431), Gruvbox Theme (0.5.5), Chinese (Simplified) Language Pack / 中文语言包 (242.20224.431), Styled Components & Styled JSX (242.20224.431), JavaScript Intention Power Pack (242.20224.431), Node.js (242.20224.431), Vagrant (242.20224.431), Docker (242.20224.431), Pug (ex-Jade) (242.20224.431), dotCover (242.20224.431), SSH Remote Run (242.20224.431), Mercurial (242.20224.431), JavaScript and TypeScript (242.20224.431), Node.js Remote Interpreter (242.20224.431), Database Tools and SQL (242.20224.431), GitLab (242.20224.431), JSONPath (242.20224.431), Korean Language Pack / 한국어 언어 팩 (242.20224.431), Entity Framework Core UI (242.20224.431), Karma (242.20224.431), F# Support (242.20224.431), JavaScript Debugger (242.20224.431), Webpack (242.20224.431), ChangeReminder (242.20224.431), .NET Aspire (1.3.0), Tailwind CSS (242.20224.431), Japanese Language Pack / 日本語言語パック (242.20224.431), FTP/SFTP/WebDAV Connectivity (242.20224.431), Kubernetes (242.20224.431), Next.js (242.20224.431), Prettier (242.20224.431), Vite (242.20224.431), TSLint (242.20224.431), GitHub (242.20224.431)]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Should be fixed in 0.9.5
Let us know if it happened again
