### ISSUE TITLE
[Exception][PyCharm 2022.3.3] java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by jackfs1919** [Codium-ai/codiumai-jetbrains-release#3]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:484)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1430)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1401)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:220)
	at com.mixpanel.mixpanelapi.MixpanelAPI.sendData(MixpanelAPI.java:165)
	at com.mixpanel.mixpanelapi.MixpanelAPI.sendMessages(MixpanelAPI.java:203)
	at com.mixpanel.mixpanelapi.MixpanelAPI.deliver(MixpanelAPI.java:121)
	at com.mixpanel.mixpanelapi.MixpanelAPI.deliver(MixpanelAPI.java:101)
	at com.mixpanel.mixpanelapi.MixpanelAPI.sendMessage(MixpanelAPI.java:89)
	at ai.codium.analytic.CodiumAnalyticService$sendMessage$1.run(CodiumAnalyticService.kt:213)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

# Other Information
```
=== About ===
Build version: PyCharm 2022.3.3 Build: #PC-223.8836.43 March 10, 2023
Theme: Darcula
JRE: 17.0.6+1-b653.34, JetBrains s.r.o.
JVM: 17.0.6+1-b653.34, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11 10.0 (amd64)

=== Plugins ===
Custom plugins: [Foldable ProjectView (1.1.4), .ignore (4.4.4), AI Coding Assistant (1.0.16), Bito – ChatGPT to write code, explain code, create tests (1.0.131), CodeGeeX (1.0.6), CodeGPT (1.6.1), Dedalow Coding (1.0.3), NexChatGPT (3.0.0), Terraform and HCL (223.8214.6), CodiumAI - Meaningful tests powered by TestGPT (0.4.3), CSV Editor (3.1.0-223), GitHub Actions Manager (1.10.2), Sourcery (1.0.9), I Love DevToys (1.8.0), Code-File-Grabber (1.0.3), H2O Wave (0.25.2), Easy Gitlab (6.7.1), Codify (1.1.31), Unix Timestamp Converter (4.1.4), Codeium (1.1.59), Test Data (223.8214.6), File Format Transformer (1.5.0), Ini (223.8836.46)]
Disabled plugins:[Space (223.8836.43)]
```

**Comment by ArtsiomCh** [comment]
fixed at 0.4.4
Thanks for reporting!
