### ISSUE TITLE
[Exception][PhpStorm 2023.1.1] java.lang.Throwable: Assert: must be called on EDT

### ISSUE THREAD

**Issue by Shuhratulloh** [Codium-ai/codiumai-jetbrains-release#31]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable: Assert: must be called on EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.util.ui.EDT.assertIsEdt(EDT.java:68)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.show(ToolWindowImpl.kt:276)
	at com.intellij.openapi.wm.ToolWindow.show(ToolWindow.java:65)
	at ai.codium.ui.CodiumStatusBarWidget.showToolWindowIfNotLogged(CodiumStatusBarWidgetFactory.kt:53)
	at ai.codium.ui.CodiumStatusBarWidget.showToolWindowIfNotLogged$default(CodiumStatusBarWidgetFactory.kt:47)
	at ai.codium.ui.CodiumStatusBarWidget.<init>(CodiumStatusBarWidgetFactory.kt:61)
	at ai.codium.ui.CodiumStatusBarWidgetFactory.createWidget(CodiumStatusBarWidgetFactory.kt:32)
	at com.intellij.openapi.wm.StatusBarWidgetFactory.createWidget(StatusBarWidgetFactory.java:71)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetsManagerKt.createWidget(StatusBarWidgetsManager.kt:248)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetsManagerKt.access$createWidget(StatusBarWidgetsManager.kt:1)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetsManager.init$intellij_platform_ide_impl(StatusBarWidgetsManager.kt:202)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.init$intellij_platform_ide_impl(IdeStatusBarImpl.kt:273)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.init$intellij_platform_ide_impl$default(IdeStatusBarImpl.kt:270)
	at com.intellij.openapi.wm.impl.ProjectFrameHelper.installDefaultProjectStatusBarWidgets$suspendImpl(ProjectFrameHelper.kt:347)
	at com.intellij.openapi.wm.impl.ProjectFrameHelper.installDefaultProjectStatusBarWidgets(ProjectFrameHelper.kt)
	at com.intellij.openapi.project.impl.ProjectFrameAllocatorKt$initFrame$3.invokeSuspend(ProjectFrameAllocator.kt:387)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

# Other Information
```
=== About ===
Build version: PhpStorm 2023.1.1 Build: #PS-231.8770.68 April 28, 2023
Theme: Dark
JRE: 17.0.6+10-b829.9, JetBrains s.r.o.
JVM: 17.0.6+10-b829.9, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Linux 6.2.15-200.fc37.x86_64 (amd64)

=== Plugins ===
Custom plugins: [Material Theme UI Lite (20.0.0), Dark Purple Theme (1.3), Symfony Support (2022.1.248), ChatGPT (2.2.2-222.231), .env files support (2023.1), GitHub Copilot (1.2.6.2594), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.5.0), PHP Annotations (9.3.1)]
Disabled plugins:[]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/m8fWohJP) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Fixed at 0.5.4
Please update
