### ISSUE TITLE
[Exception][PyCharm 2022.1.4] com.intellij.diagnostic.PluginException: Cannot create class ai.codium.analytic.CodiumA...

### ISSUE THREAD

**Issue by pzc163** [Codium-ai/codiumai-jetbrains-release#32]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
com.intellij.diagnostic.PluginException: Cannot create class ai.codium.analytic.CodiumAnalyticService (classloader=PluginClassLoader(plugin=PluginDescriptor(name=CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4, id=codiumai.codiumai, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\PyCharm2022.1\plugins\codium-ai-plugin-0.5.2.jar, version=0.5.2, package=null, isBundled=false), packagePrefix=null, instanceId=118, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:884)
	at com.intellij.serviceContainer.ComponentManagerImpl.createLightService(ComponentManagerImpl.kt:824)
	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:670)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:622)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:584)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at ai.codium.UtilsKt.getCodiumAnalyticService(Utils.kt:148)
	at ai.codium.ui.CodiumLoginPanel.<init>(CodiumLoginPanel.kt:43)
	at ai.codium.ui.CodiumToolWindowFactory$createToolWindowContent$2.newLoginRequired(CodiumToolWindowFactory.kt:69)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:639)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:621)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:391)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:373)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:34)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:180)
	at com.sun.proxy.$Proxy124.newLoginRequired(Unknown Source)
	at ai.codium.UtilsKt.isUserLogged(Utils.kt:60)
	at ai.codium.ui.CodiumToolWindowFactory.createToolWindowContent$showDefaultContentByLoggedStatus$lambda$1(CodiumToolWindowFactory.kt:40)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.

<TRIMMED STACKTRACE>

lushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.NoClassDefFoundError: com/mixpanel/mixpanelapi/MixpanelAPI
	at ai.codium.analytic.CodiumAnalyticService.<init>(CodiumAnalyticService.kt:26)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:845)
	... 50 more
Caused by: java.lang.ClassNotFoundException: com.mixpanel.mixpanelapi.MixpanelAPI PluginClassLoader(plugin=PluginDescriptor(name=CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4, id=codiumai.codiumai, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\PyCharm2022.1\plugins\codium-ai-plugin-0.5.2.jar, version=0.5.2, package=null, isBundled=false), packagePrefix=null, instanceId=118, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:215)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 52 more

```

# Other Information
```
=== About ===
Build version: PyCharm 2022.1.4 Build: #PY-221.6008.17 July 21, 2022
Theme: Darcula
JRE: 11.0.15+10-b2043.56, JetBrains s.r.o.
JVM: 11.0.15+10-b2043.56, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 10 10.0 (amd64)

=== Plugins ===
Custom plugins: [Chinese (Simplified) Language Pack / 中文语言包 (221.262), GitHub Copilot (1.2.6.2594), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.5.2)]
Disabled plugins:[]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/ncuW0I4U) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Hi @pzc163 Thanks for reporting!
Looks like one time PyCharm glitch. Will close for now and we'll keep our eyes for this component.
