### ISSUE TITLE
[Exception][PyCharm 2023.1] java.lang.Throwable: Assert: must be called on EDT

### ISSUE THREAD

**Issue by twofivecrypto** [Codium-ai/codiumai-jetbrains-release#33]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable: Assert: must be called on EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.util.ui.EDT.assertIsEdt(EDT.java:68)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.show(ToolWindowImpl.kt:276)
	at com.intellij.openapi.wm.ToolWindow.show(ToolWindow.java:65)
	at ai.codium.ui.CodiumStatusBarWidget.showToolWindowIfNotLogged(CodiumStatusBarWidgetFactory.kt:53)
	at ai.codium.ui.CodiumStatusBarWidget.showToolWindowIfNotLogged$default(CodiumStatusBarWidgetFactory.kt:47)
	at ai.codium.ui.CodiumStatusBarWidget.<init>(CodiumStatusBarWidgetFactory.kt:61)
	at ai.codium.ui.CodiumStatusBarWidgetFactory.createWidget(CodiumStatusBarWidgetFactory.kt:32)
	at com.intellij.openapi.wm.StatusBarWidgetFactory.createWidget(StatusBarWidgetFactory.java:71)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetsManagerKt.createWidget(StatusBarWidgetsManager.kt:248)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetsManagerKt.access$createWidget(StatusBarWidgetsManager.kt:1)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetsManager.init$intellij_platform_ide_impl(StatusBarWidgetsManager.kt:202)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.init$intellij_platform_ide_impl(IdeStatusBarImpl.kt:273)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.init$intellij_platform_ide_impl$default(IdeStatusBarImpl.kt:270)
	at com.intellij.openapi.wm.impl.ProjectFrameHelper.installDefaultProjectStatusBarWidgets$suspendImpl(ProjectFrameHelper.kt:362)
	at com.intellij.openapi.wm.impl.ProjectFrameHelper.installDefaultProjectStatusBarWidgets(ProjectFrameHelper.kt)
	at com.intellij.openapi.project.impl.ProjectFrameAllocatorKt$initFrame$3.invokeSuspend(ProjectFrameAllocator.kt:387)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

# Other Information
```
=== About ===
Build version: PyCharm 2023.1 Build: #PC-231.8109.197 March 29, 2023
Theme: vuesion-theme
JRE: 17.0.6+10-b829.5, JetBrains s.r.o.
JVM: 17.0.6+10-b829.5, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 10.0 (amd64)

=== Plugins ===
Custom plugins: [Vuesion Theme (1.9.2), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.4.12), VSCode Theme (1.8.0), Bito – GPT-4 & ChatGPT to write code, explain code, create tests (1.0.134), ChatGPT (2.1.17-222.231), Tokyo Night Theme (0.1.6), CSV Editor (3.2.0-231), One Dark theme (5.7.4), Material Design Dark-Theme (1.7.12), IdeaVim (2.2.0), Lotus Theme (1.10), Monokai Pro Theme (1.10), ChatGPT Copilot (0.6.1), Machinet AI GPT4 (2022.1.35)]
Disabled plugins:[]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/AWTQsl8Z) by [Unito](https://www.unito.io)

**Comment by twofivecrypto** [comment]
just crashed upon loading, maybe was running python code from too many IDEs, ie VSCode and Geany earlier today.

**Comment by twofivecrypto** [comment]
Thank you.
