### ISSUE TITLE
[0.10.1][PYCHARM PC 2024.2.0.1] com.intellij.openapi.vfs.InvalidVirtualFileAccessException: Accessing invalid virtual...

### ISSUE THREAD

**Issue by shyamsubrahmanyan-Intelo** [Codium-ai/codiumai-jetbrains-release#344]
```
com.intellij.openapi.vfs.InvalidVirtualFileAccessException: Accessing invalid virtual file: file:///Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/python-skeletons; original:43; found:-; File.exists()=false
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectory(FileManagerImpl.java:411)
	at com.intellij.psi.impl.PsiManagerImpl.findDirectory(PsiManagerImpl.java:175)
	at com.jetbrains.python.codeInsight.userSkeletons.PyUserSkeletonsUtil.getUserSkeletonForModuleQName(PyUserSkeletonsUtil.java:179)
	at com.jetbrains.python.codeInsight.userSkeletons.PyUserSkeletonsUtil.getUserSkeletonForFile(PyUserSkeletonsUtil.java:241)
	at com.jetbrains.python.codeInsight.userSkeletons.PyUserSkeletonsUtil.getUserSkeletonWithContext(PyUserSkeletonsUtil.java:151)
	at com.jetbrains.python.codeInsight.userSkeletons.PyUserSkeletonsUtil.getUserSkeleton(PyUserSkeletonsUtil.java:145)
	at com.jetbrains.python.codeInsight.userSkeletons.PyUserSkeletonsModuleMembersProvider.resolveMember(PyUserSkeletonsModuleMembersProvider.java:24)
	at com.jetbrains.python.psi.types.PyModuleType.resolveByMembersProviders(PyModuleType.java:265)
	at com.jetbrains.python.psi.types.PyModuleType.resolveMemberInPackageOrModule(PyModuleType.java:110)
	at com.jetbrains.python.psi.types.PyModuleType.resolveMember(PyModuleType.java:73)
	at com.jetbrains.python.psi.resolve.ResolveImportUtil.resolveModuleMember(ResolveImportUtil.java:315)
	at com.jetbrains.python.psi.resolve.ResolveImportUtil.resolveInPackageModule(ResolveImportUtil.java:280)
	at com.jetbrains.python.psi.resolve.ResolveImportUtil.resolveChildren(ResolveImportUtil.java:265)
	at com.jetbrains.python.psi.resolve.ResolveImportUtil.resolveNameInFromImport(ResolveImportUtil.java:137)
	at com.jetbrains.python.psi.resolve.ResolveImportUtil.multiResolveImportElement(ResolveImportUtil.java:104)
	at com.jetbrains.python.psi.impl.PyImportElementImpl.multiResolve(PyImportElementImpl.java:215)
	at com.jetbrains.python.psi.impl.PyImportElementImpl.getElementsNamed(PyImportElementImpl.java:196)
	at com.jetbrains.python.psi.impl.PyImportElementImpl.multiResolveName(PyImportElementImpl.java:167)
	at com.jetbrains.python.psi.resolve.PyResolveProcessor.resolveInImportedNameDefiner(PyResolveProcessor.java:96)
	at com.jetbrains.python.psi.resolve.PyResolveProcessor.execute(PyResolveProcessor.java:48)
	at com.jetbrains.python.psi.impl.PyFileImpl$ExportedNameCache.multiResolve(PyFileImpl.java:145)
	at com.jetbrains.python.psi.impl.PyFileImpl.lambda$multiResolveName$1(PyFileImpl.java:417)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at co

<TRIMMED STACKTRACE>

t com.intellij.codeInsight.hints.InlayHintsUtilsKt.getCollectorWrapperFor(InlayHintsUtils.kt:56)
	at com.intellij.codeInsight.daemon.impl.InlayHintsPassFactoryInternal.createHighlightingPass(InlayHintsPassFactoryInternal.kt:46)
	at com.intellij.codeInsight.daemon.impl.TextEditorHighlightingPassRegistrarImpl.instantiatePasses(TextEditorHighlightingPassRegistrarImpl.java:185)
	at com.intellij.codeInsight.daemon.impl.TextEditorBackgroundHighlighter.getPasses(TextEditorBackgroundHighlighter.kt:65)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$submitInBackground$28(DaemonCodeAnalyzerImpl.java:1271)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:264)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:221)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:857)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:66)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$submitInBackground$29(DaemonCodeAnalyzerImpl.java:1258)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.submitInBackground(DaemonCodeAnalyzerImpl.java:1255)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$queuePassesCreation$23(DaemonCodeAnalyzerImpl.java:1220)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:190)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)

```

# Other Information
```
=== About ===
Build version: PyCharm 2024.2.0.1 Build: #PC-242.20224.428 August 21, 2024
Theme: Dark
JRE: 21.0.3+13-b509.4, JetBrains s.r.o.
JVM: 21.0.3+13-b509.4, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 15.0.1 (aarch64)

=== Plugins ===
Custom plugins: [YouTrack Integration (2024.2.123), One Dark Theme (5.12.0), Codeium: AI Autocomplete and Chat for Python, JS, Java, Go... (1.20.9), Extra ToolWindow Colorful Icons (2024.5.2), Key Promoter X (2024.2.0), Tabnine: AI Chat & Autocomplete for JavaScript, Python & more (1.147.0), Please (v2.1.4), Ruff (0.0.39), AI Commits (2.6.0), Qodo Gen (Formerly Codiumate) (0.10.1)]
Disabled plugins:[Ideolog (242.22855.126), JetBrains AI Assistant (242.22855.75), Docker (242.22855.113), GitToolBox (600.0.2+242), Pydantic (0.4.14), Space (242.22855.32), Chinese (Simplified) Language Pack / 中文语言包 (242.20224.428), Terraform and HCL (242.22855.32), AICommit (3.1.0)]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Seems to be IDE internal (python subsystem) issue
