### ISSUE TITLE
[0.10.1][RUBYMINE 2024.2.3] java.lang.NoClassDefFoundError: okhttp3/internal/Util

### ISSUE THREAD

**Issue by hms** [Codium-ai/codiumai-jetbrains-release#347]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.NoClassDefFoundError: okhttp3/internal/Util
	at ai.codium.UtilsKt.calculateSpacesAndTabsCountForOffset(Utils.kt:291)
	at ai.codium.CodiumInlayProvider.buildOptionsPresentation(CodiumInlayProvider.kt:251)
	at ai.codium.CodiumInlayProvider.addCodiumOptionsInlay(CodiumInlayProvider.kt:226)
	at ai.codium.CodiumInlayProvider.access$addCodiumOptionsInlay(CodiumInlayProvider.kt:38)
	at ai.codium.CodiumInlayProvider$createAddTestsFactoryInlayHintsCollector$1.collect(CodiumInlayProvider.kt:146)
	at com.intellij.codeInsight.hints.CollectorWithSettings.collectHints(InlayHintsUtils.kt:97)
	at com.intellij.codeInsight.hints.InlayHintsPass.doCollectInformation$lambda$1(InlayHintsPass.kt:60)
	at com.intellij.concurrency.ApplierCompleter.processArrayItem(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.processArray(ApplierCompleter.java:196)
	at com.intellij.concurrency.ApplierCompleter.execAll(ApplierCompleter.java:166)
	at com.intellij.concurrency.JobLauncherImpl.lambda$invokeConcurrentlyUnderProgressAsync$3(JobLauncherImpl.java:103)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:279)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$2(ApplierCompleter.java:148)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:159)
	at com.intellij.concurrency.ApplierCompleter.wrapAndRun(ApplierCompleter.java:143)
	at com.intellij.concurrency.JobLauncherImpl.lambda$invokeConcurrentlyUnderProgressAsync$4(JobLauncherImpl.java:103)
	at com.intellij.concurrency.JobLauncherImpl.safeIterate(JobLauncherImpl.java:168)
	at com.intellij.concurrency.JobLauncherImpl.invokeConc

<TRIMMED STACKTRACE>

ntents/plugins/javascript-plugin, version=242.23339.18, package=com.intellij.javascript.java, isBundled=true), PluginDescriptor(name=JavaScript and TypeScript, id=JavaScript, moduleName=intellij.aqua.runners.playwright.js, descriptorPath=intellij.aqua.runners.playwright.js.xml, path=/Applications/RubyMine.app/Contents/plugins/javascript-plugin, version=242.23339.18, package=com.intellij.aqua.runners.playwright.js, isBundled=true), PluginDescriptor(name=JavaScript and TypeScript, id=JavaScript, moduleName=intellij.aqua.runners.js.core, descriptorPath=intellij.aqua.runners.js.core.xml, path=/Applications/RubyMine.app/Contents/plugins/javascript-plugin, version=242.23339.18, package=com.intellij.aqua.runners.js.core, isBundled=true), PluginDescriptor(name=JavaScript and TypeScript, id=JavaScript, moduleName=intellij.aqua.runners.cypress, descriptorPath=intellij.aqua.runners.cypress.xml, path=/Applications/RubyMine.app/Contents/plugins/javascript-plugin, version=242.23339.18, package=com.intellij.aqua.runners.cypress, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=/Applications/RubyMine.app/Contents/lib, version=242.23339.18, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.log.impl, descriptorPath=intellij.platform.vcs.log.impl.xml, path=/Applications/RubyMine.app/Contents/lib, version=242.23339.18, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.dvcs.impl, descriptorPath=intellij.platform.vcs.dvcs.impl.xml, path=/Applications/RubyMine.app/Contents/lib, version=242.23339.18, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.collaborationTools, descriptorPath=intellij.platform.collaborationTools.xml, path=/Applications/RubyMine.app/Contents/lib, version=242.23339.18, package=null, isBundled=true), PluginDescriptor(name=Git, id=Git4Idea, descriptorPath=plugin.xml, path=/Applications/RubyMine.app/Contents/plugins/vcs-git, version=242.23339.18, package=git4idea, isBundled=true), PluginDescriptor(name=JavaScript and TypeScript, id=JavaScript, descriptorPath=plugin.xml, path=/Applications/RubyMine.app/Contents/plugins/javascript-plugin, version=242.23339.18, package=null, isBundled=true), )
	... 52 more

```

# Other Information
```
=== About ===
Build version: RubyMine 2024.2.3 Build: #RM-242.23339.18 September 25, 2024
Theme: GitHub Light
JRE: 21.0.4+13-b509.17, JetBrains s.r.o.
JVM: 21.0.4+13-b509.17, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 15.0.1 (aarch64)

=== Plugins ===
Custom plugins: [Ideolog (242.23339.18), Properties (242.20224.155), IntelliJ New UI (0.4), Dash (3.3), GitHub Theme (1.2.2), Xcode Theme (1.7.0), Xcode-Dark Theme (1.2.4), Check for Dependency Updates (1.1), Toml (242.20224.155), RubyMine Help (242.23339.18), AWS Core (3.32-242), Space (242.23339.11), JetBrains AI Assistant (242.23339.40), IdeaVim (2.17.0-eap.1), Qodo Gen (Formerly Codiumate) (0.10.1), Github Themes (0.0.23), AWS Toolkit (3.32-242), Postgres Explain Visualizer (1.10)]
Disabled plugins:[Angular (242.23339.18), React (242.23339.18), Polymer & Web Components (242.23339.18), Subversion (242.23339.18), Vue.js (242.23339.18), Stimulus (0.5.241), Perforce Helix Core (242.23339.18), Styled Components & Styled JSX (242.23339.18), Eclipse Keymap (242.23339.18), CoffeeScript (242.23339.18), NetBeans Keymap (242.23339.18), Textmate Keymap (242.23339.18), Vagrant (242.23339.18), Mercurial (242.23339.18), Slim (242.23339.18), GitLab (242.23339.18), Gherkin (242.23339.18), Liquid (242.23339.18), Sass (242.23339.18), Webpack (242.23339.18), Less (242.23339.18), Next.js (242.23339.18), Visual Studio Keymap (242.23339.18), TextMate Bundles (242.23339.18), Vite (242.23339.18), Tailwind Formatter (2.0.10), Time Tracking (242.23339.18), Haml (242.23339.18)]
```

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
1. Was that one time glitch or you see it often/always?
2. Did you install plugin from marketplace or manually from downloaded .zip file?
