### ISSUE TITLE
[Exception][PyCharm 2023.1.2] java.lang.ClassCastException: class ai.codium.analytic.CodiumAnalyticService cannot be ...

### ISSUE THREAD

**Issue by alex25132** [Codium-ai/codiumai-jetbrains-release#36]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.ClassCastException: class ai.codium.analytic.CodiumAnalyticService cannot be cast to class ai.codium.analytic.CodiumAnalyticService (ai.codium.analytic.CodiumAnalyticService is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @535d10fb; ai.codium.analytic.CodiumAnalyticService is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @4fb5c2cd)
	at ai.codium.UtilsKt.getCodiumAnalyticService(Utils.kt:224)
	at ai.codium.net.CodiumLoginManager$Companion.sendLoginFinishedEvent(CodiumLoginManager.kt:61)
	at ai.codium.net.CodiumHttpRequestHandler.process$processError(CodiumHttpRequestHandler.kt:37)
	at ai.codium.net.CodiumHttpRequestHandler.access$process$processError(CodiumHttpRequestHandler.kt:19)
	at ai.codium.net.CodiumHttpRequestHandler$process$signInResponse$1.invoke(CodiumHttpRequestHandler.kt:63)
	at ai.codium.net.CodiumHttpRequestHandler$process$signInResponse$1.invoke(CodiumHttpRequestHandler.kt:60)
	at ai.codium.net.CodiumNetworkClient.executeRequest(CodiumNetworkClient.kt:33)
	at ai.codium.net.CodiumNetworkClient.executeRequest(CodiumNetworkClient.kt:50)
	at ai.codium.net.CodiumNetworkClient.executeRequest(CodiumNetworkClient.kt:50)
	at ai.codium.net.CodiumNetworkClient.executeRequest(CodiumNetworkClient.kt:50)
	at ai.codium.net.CodiumNetworkClient.executeRequest$default(CodiumNetworkClient.kt:24)
	at ai.codium.net.CodiumFirebaseApiClient.signInWithProvider$codium_ai_plugin(CodiumFirebaseApiClient.kt:19)
	at ai.codium.net.CodiumNetworkService.loginToFirebase(CodiumNetworkService.kt:101)
	at ai.codium.net.CodiumHttpRequestHandler.process(CodiumHttpRequestHandler.kt:60)
	at org.jetbrains.io.DelegatingHttpRequestHandler.process$checkAndProcess(DelegatingHttpRequestHandler.kt:21)
	at org.jetbrains.io.DelegatingHttpRequestHandler.access$process$checkAndProcess(DelegatingHttpRequestHandler.kt:15)
	at org.jetbrains.io.DelegatingHttpRequestHandler$process$1.invoke(DelegatingHttpRequestHandler.kt:35)
	at org.jetbrains.io.DelegatingHttpRequestHandler$process$1.invoke(DelegatingHttpRequestHandler.kt:34)
	at org.jetbrains.io.DelegatingHttpRequestHandler.process$lambda$0(DelegatingHttpRequestHandler.kt:34)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.findFirstSafe$lambda$0(ExtensionProcessingHelper.kt:47)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.kt:57)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.findFirstSafe(ExtensionProcessingHelper.kt:47)
	at com.intellij.openapi.extensions.ExtensionPointName.findFirstSafe(ExtensionPointName.kt:53)
	at org.jetbrains.io.DelegatingHttpRequestHandler.process(DelegatingHttpRequestHandler.kt:34)
	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.kt:15)
	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase

<TRIMMED STACKTRACE>

text.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at org.jetbrains.io.PortUnificationServerHandler.decode(PortUnificationServerHandler.java:128)
	at org.jetbrains.io.PortUnificationServerHandler.messageReceived(PortUnificationServerHandler.java:76)
	at org.jetbrains.io.Decoder.channelRead(Decoder.java:23)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

# Other Information
```
=== About ===
Build version: PyCharm 2023.1.2 Build: #PY-231.9011.38 May 17, 2023
Theme: Dark
JRE: 17.0.6+10-b829.9, JetBrains s.r.o.
JVM: 17.0.6+10-b829.9, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [ChatGPT GPT-4 – Free AI Assistant for Developers (1.0.137), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.5.7), Chinese (Simplified) Language Pack / 中文语言包 (231.283)]
Disabled plugins:[]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/P7wOxzAB) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Should be fixed in upcoming 0.5.15
Please feel free to reopen/report if experience it again.
