### ISSUE TITLE
[Exception][IDEA 2023.1.2] java.lang.Throwable: find: An invalid record was encountered. (-67701)

### ISSUE THREAD

**Issue by kobikisos1** [Codium-ai/codiumai-jetbrains-release#37]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable: find: An invalid record was encountered. (-67701)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.credentialStore.KeyChainCredentialStore$Companion.checkForError(macOsKeychainLibrary.kt:88)
	at com.intellij.credentialStore.KeyChainCredentialStore$Companion.findGenericPassword(macOsKeychainLibrary.kt:37)
	at com.intellij.credentialStore.KeyChainCredentialStore$Companion.access$findGenericPassword(macOsKeychainLibrary.kt:29)
	at com.intellij.credentialStore.KeyChainCredentialStore.get(macOsKeychainLibrary.kt:96)
	at com.intellij.credentialStore.NativeCredentialStoreWrapper.get(NativeCredentialStoreWrapper.kt:46)
	at com.intellij.ide.passwordSafe.impl.BasePasswordSafe.get(PasswordSafeImpl.kt:91)
	at com.intellij.credentialStore.CredentialStore.getPassword(CredentialStore.java:30)
	at ai.codium.CodiumCredentialStorageKt.getCodiumRefreshToken(CodiumCredentialStorage.kt:16)
	at ai.codium.net.CodiumLoginManager.getRefreshToken(CodiumLoginManager.kt:20)
	at ai.codium.ui.CodiumStatusBarWidget.showToolWindowIfNotLogged(CodiumStatusBarWidgetFactory.kt:49)
	at ai.codium.ui.CodiumStatusBarWidget.showToolWindowIfNotLogged$default(CodiumStatusBarWidgetFactory.kt:48)
	at ai.codium.ui.CodiumStatusBarWidget._init_$lambda$2(CodiumStatusBarWidgetFactory.kt:64)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:249)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:365)
	at com.intellij.util.Alarm$Request.run(Alarm.java:354)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:571)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:571)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2023.1.2 Build: #IU-231.9011.34 May 16, 2023
Theme: Darcula
JRE: 17.0.6+10-b829.9, JetBrains s.r.o.
JVM: 17.0.6+10-b829.9, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.3.1 (aarch64)

=== Plugins ===
Custom plugins: [Go (231.9011.4), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.5.7)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Hi @kobikisos1, Thanks for reporting!
Was it one time exception or you experiencing it many times?
Did you get alongside with that exception any OS message about any issue with OS Credential Store?

**Comment by ArtsiomCh** [comment]
Will close for now. Seems to be one time glitch. Please reopen if happened again.
