### ISSUE TITLE
[Exception][PyCharm 2023.1.2] java.lang.Throwable: Write-unsafe context! Model changes are allowed from write-safe co...

### ISSUE THREAD

**Issue by krillavilla** [Codium-ai/codiumai-jetbrains-release#38]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable: Write-unsafe context! Model changes are allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
  current modality=ModalityState.NON_MODAL
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.application.TransactionGuardImpl.assertWriteActionAllowed(TransactionGuardImpl.java:135)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$openFileImpl4$open$1.invoke(FileEditorManagerImpl.kt:998)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$openFileImpl4$open$1.invoke(FileEditorManagerImpl.kt:996)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$Companion.runBulkTabChange$intellij_platform_ide_impl(FileEditorManagerImpl.kt:390)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4$open(FileEditorManagerImpl.kt:996)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4$intellij_platform_ide_impl(FileEditorManagerImpl.kt:1024)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2$lambda$22(FileEditorManagerImpl.kt:900)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:210)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:150)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.kt:899)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFile(FileEditorManagerImpl.kt:798)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openEditorImpl$lambda$31(FileEditorManagerImpl.kt:1275)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:150)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openEditorImpl(FileEditorM

<TRIMMED STACKTRACE>

EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:571)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:571)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

# Other Information
```
=== About ===
Build version: PyCharm 2023.1.2 Build: #PY-231.9011.38 May 16, 2023
Theme: [NEWUI] Gradianto Nature Green
JRE: 17.0.6+10-b829.9, JetBrains s.r.o.
JVM: 17.0.6+10-b829.9, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Linux 6.2.0-20-generic (amd64)

=== Plugins ===
Custom plugins: [Rainbow Brackets (2023.2.8), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.5.8), Gradianto (5.1), Gerry Themes Pro (2023.1.50), Power Mode II (102.201), String Manipulation (9.7.1), HighlightBracketPair (1.4.0), Azure DevOps (1.162.2), Github farshid Light v2 (rainglow) Color Scheme (2.6), Indent Rainbow (2.1.0), aiXcoder Code Completer (4.1.27-2020), Rainbow Dash Progress Bar (1.5), Kubernetes (231.9011.4), JetBrains Academy (2023.5-2023.1-646), Legacy Icon Pack for 2018.2+ (1.14), Extra Icons (2023.2.5-231), PowerShell (2.0.10), Terraform and HCL (231.8109.91), Randomness (2.7.6), Nyan Progress Bar (1.14), .env files support (2023.1), Atom Material Icons (90.0.0), SonarLint (8.3.0.71062), .ignore (4.5.0), AWS Toolkit (1.68-231), AceJump (3.8.13), Noctumsempra's Color MEGAPACK (1.0.3.3)]
Disabled plugins:[Tabnine AI Code Completion- JS Java Python TS Rust Go PHP & More (1.0.14), Key Promoter X (2023.1.0), Rainbow (1.8.8), Foldable ProjectView (1.1.4), Code With Me (231.9011.38), IdeaVim (2.2.0), Save Actions (2.3.0), Rainbow CSV (2.0.2), Monokai Pro Theme (1.10), Grep Console (12.18.211.6693.0), GitToolBox (500.0.9+213)]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/BcOzVOg8) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Thanks for reporting! Will be fixed in 0.5.11
