### ISSUE TITLE
[Exception][IDEA 2023.1.2] java.lang.RuntimeException: Cannot invoke (class=, method=selectionChanged, topic=FileEdit...

### ISSUE THREAD

**Issue by Goldziher** [Codium-ai/codiumai-jetbrains-release#39]
# User Description
The plugin stopped working completely. I opened an issue on discord: https://discord.com/channels/1057273017547378788/1115630087451185192

# Stack Trace
```
java.lang.RuntimeException: Cannot invoke (class=, method=selectionChanged, topic=FileEditorManagerListener)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:657)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:415)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:394)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:454)
	at jdk.proxy1/jdk.proxy1.$Proxy97.selectionChanged(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.fireSelectionChanged(FileEditorManagerImpl.kt:1637)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.access$fireSelectionChanged(FileEditorManagerImpl.kt:119)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$1$1.invokeSuspend(FileEditorManagerImpl.kt:223)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.application.impl.DispatchedRunnable.run(DispatchedRunnable.kt:35)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.applica

<TRIMMED STACKTRACE>

onOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.NullPointerException: Cannot read field "parent" because "comp" is null
	at java.desktop/java.awt.Container.remove(Container.java:1290)
	at com.intellij.openapi.ui.SimpleToolWindowPanel.setToolbar(SimpleToolWindowPanel.java:99)
	at ai.codium.ui.structureview.CodiumStructureViewPanel.<init>(CodiumStructureViewPanel.kt:34)
	at ai.codium.ui.structureview.CodiumStructureViewToolWindowFactory.createToolWindowContent$setToolwindowContent(CodiumStructureViewToolWindowFactory.kt:16)
	at ai.codium.ui.structureview.CodiumStructureViewToolWindowFactory.access$createToolWindowContent$setToolwindowContent(CodiumStructureViewToolWindowFactory.kt:10)
	at ai.codium.ui.structureview.CodiumStructureViewToolWindowFactory$createToolWindowContent$1.selectionChanged(CodiumStructureViewToolWindowFactory.kt:28)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:680)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:640)
	... 48 more

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2023.1.2 Build: #IU-231.9011.34 May 16, 2023
Theme: Dark
JRE: 17.0.6+10-b829.9, JetBrains s.r.o.
JVM: 17.0.6+10-b829.9, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.4 (aarch64)

=== Plugins ===
Custom plugins: [Makefile Language (231.8109.91), File Watchers (231.8109.91), Native Debugging Support (231.8770.15), Ini (231.9011.41), Dart (231.9065), Python (231.9011.34), Nest (1.2.13), Flutter (74.0.4), Go Linter (1.6.5), Go (231.9011.4), Handlebars/Mustache (231.8770.3), String Manipulation (9.7.1), .env files support (2023.1), .ignore (4.5.0), GitHub Copilot (1.2.8.2635-nightly), Nx Console Idea (0.58.0), Terraform and HCL (231.8109.91), ReStructuredText (231.8770.3), Go Template (231.8109.91), Rust (0.4.195.5408-231), Prisma ORM (231.9011.4), Kubernetes (231.9011.4), Nginx Configuration (2022.1.1), BlackConnect (0.6.0), SonarLint (8.3.0.71062), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.5.9)]
Disabled plugins:[Hibernate (231.9011.34), Gradle-Maven (231.9011.34), GlassFish (231.9011.34), Maven (231.9011.34), Spring Data (231.9011.34), Jakarta EE: Server Pages (JSP) (231.9011.34), Jakarta EE: RESTful Web Services (JAX-RS) (231.9011.34), Jakarta EE: Bean Validation (231.9011.34), Mercurial (231.9011.34), Persistence Frameworks (231.9011.34), Space (231.9011.34), Reactive Streams (231.9011.34), TestNG (231.9011.34), JavaFX (231.9011.34), Jakarta EE: Web/Servlets (231.9011.34), AOP Pointcut Language (231.9011.34), Grazie Lite (231.9011.34), Spring Cloud (231.9011.34), Spring Integration Patterns (231.9011.34), Ant (231.9011.34), Eclipse Interoperability (231.9011.34), Spring Messaging (231.9011.34), Maven Extension (231.9011.34), IDE Features Trainer (231.9011.34), Cucumber for Java (231.9011.34), Tomcat and TomEE (231.9011.34), Eclipse Keymap (231.9011.34), Polymer & Web Components (231.9011.34), Spring Web (231.9011.34), Gherkin (231.9011.34), Spring Security (231.9011.34), Gradle Extension (231.9011.34), Subversion (231.9011.34), Jakarta EE: Persistence (JPA) (231.9011.34), Perforce Helix Core (231.9011.34), Jakarta EE: Gradle Integration (231.9011.34), JVM Microservices Frameworks (231.9011.34), NetBeans Keymap (231.9011.34), Karma (231.9011.34), Spring Initializr (231.9011.34), Velocity (231.9011.34), Quarkus (231.9011.34), FreeMarker (231.9011.34), WildFly (231.9011.34), Visual Studio Keymap (231.9011.34), Code Coverage for Java (231.9011.34), Spring (231.9011.34), Jakarta EE: Messaging (JMS) (231.9011.34), Thymeleaf (231.9011.34), Spring Boot (231.9011.34), Jakarta EE: Contexts and Dependency Injection (CDI) (231.9011.34), Package Checker (231.9011.34), UI Designer (231.9011.34), Ktor (231.9011.34), Jakarta EE: Application Servers (231.9011.34), Micronaut (231.9011.34), Angular and AngularJS (231.9011.34), TSLint (231.9011.34), Integration Testing of Workspace Model (231.9011.34), Jakarta EE Platform (231.9011.34), Jakarta EE: Expression Language (EL) (231.9011.34), Cucumber for Groovy (231.9011.34), Lombok (231.9011.34)]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/hctkrJ3f) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Thanks for reporting! Fixed in upcoming 0.5.10. In meantime please rollback to 0.5.8
