### ISSUE TITLE
[Exception][PyCharm 2022.2.5] java.lang.ClassCastException: class ai.codium.analytic.CodiumAnalyticService cannot be ...

### ISSUE THREAD

**Issue by beta101-2022** [Codium-ai/codiumai-jetbrains-release#48]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.ClassCastException: class ai.codium.analytic.CodiumAnalyticService cannot be cast to class ai.codium.analytic.CodiumAnalyticService (ai.codium.analytic.CodiumAnalyticService is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @44a18a4; ai.codium.analytic.CodiumAnalyticService is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @2237087d)
	at ai.codium.UtilsKt.getCodiumAnalyticService(Utils.kt:240)
	at ai.codium.net.CodiumLoginManager$Companion.sendLoginFinishedEvent(CodiumLoginManager.kt:61)
	at ai.codium.net.CodiumHttpRequestHandler.process$processError(CodiumHttpRequestHandler.kt:37)
	at ai.codium.net.CodiumHttpRequestHandler.access$process$processError(CodiumHttpRequestHandler.kt:19)
	at ai.codium.net.CodiumHttpRequestHandler$process$signInResponse$1.invoke(CodiumHttpRequestHandler.kt:63)
	at ai.codium.net.CodiumHttpRequestHandler$process$signInResponse$1.invoke(CodiumHttpRequestHandler.kt:60)
	at ai.codium.net.CodiumNetworkClient.executeRequest(CodiumNetworkClient.kt:33)
	at ai.codium.net.CodiumNetworkClient.executeRequest(CodiumNetworkClient.kt:50)
	at ai.codium.net.CodiumNetworkClient.executeRequest(CodiumNetworkClient.kt:50)
	at ai.codium.net.CodiumNetworkClient.executeRequest(CodiumNetworkClient.kt:50)
	at ai.codium.net.CodiumNetworkClient.executeRequest$default(CodiumNetworkClient.kt:24)
	at ai.codium.net.CodiumFirebaseApiClient.signInWithProvider$codium_ai_plugin(CodiumFirebaseApiClient.kt:19)
	at ai.codium.net.CodiumNetworkService.loginToFirebase(CodiumNetworkService.kt:118)
	at ai.codium.net.CodiumHttpRequestHandler.process(CodiumHttpRequestHandler.kt:60)
	at org.jetbrains.io.DelegatingHttpRequestHandler$process$1.invoke(DelegatingHttpRequestHandler.kt:21)
	at org.jetbrains.io.DelegatingHttpRequestHandler$process$2.test(DelegatingHttpRequestHandler.kt:35)
	at org.jetbrains.io.DelegatingHttpRequestHandler$process$2.test(DelegatingHttpRequestHandler.kt:16)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.lambda$findFirstSafe$0(ExtensionProcessingHelper.java:46)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.java:56)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.findFirstSafe(ExtensionProcessingHelper.java:46)
	at com.intellij.openapi.extensions.ExtensionPointName.findFirstSafe(ExtensionPointName.java:50)
	at org.jetbrains.io.DelegatingHttpRequestHandler.process(DelegatingHttpRequestHandler.kt:34)
	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.kt:15)
	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequ

<TRIMMED STACKTRACE>

Read(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.jetbrains.io.PortUnificationServerHandler.decode(PortUnificationServerHandler.java:129)
	at org.jetbrains.io.PortUnificationServerHandler.messageReceived(PortUnificationServerHandler.java:76)
	at org.jetbrains.io.Decoder.channelRead(Decoder.java:24)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

# Other Information
```
=== About ===
Build version: PyCharm 2022.2.5 Build: #PY-222.4554.11 March 15, 2023
Theme: IntelliJ Light
JRE: 17.0.6+7-b469.82, JetBrains s.r.o.
JVM: 17.0.6+7-b469.82, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.2.1 (aarch64)

=== Plugins ===
Custom plugins: [Json Parser (1.4.1), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.5.12), Casbin (0.1.14), String Manipulation (9.7.1), Reloadium - Hot Reloading & Profiling for Python (0.9.5), Translation (3.5.0), GitToolBox (500.0.10+213), ChatGPT - ChatMoss (1.0.7), JetBrains Academy (2023.4-2022.2-2216), Rainbow Brackets (2023.2.11-ij), Codeium: AI Autocomplete for Python, JS, TS, Java, Go, and more (1.2.19), Machinet AI GPT4 & ChatGPT (2022.1.41), ChatGPT GPT-4 (1.0.138), OnlineSearch (2.0.1), LeetCode with labuladong (1.7.1), CSV Editor (3.2.0-222)]
Disabled plugins:[Markdown Navigator Enhanced (3.0.213.150), Chinese (Simplified) Language Pack / 中文语言包 (222.426), Paste Images into Markdown (1.2.11)]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/gZYNU54W) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Will close as duplicated for #36
