### ISSUE TITLE
[Exception][PyCharm 2023.1] com.intellij.diagnostic.PluginException: Cannot create class ai.codium.analytic.CodiumAna...

### ISSUE THREAD

**Issue by EmperiuM666** [Codium-ai/codiumai-jetbrains-release#51]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
com.intellij.diagnostic.PluginException: Cannot create class ai.codium.analytic.CodiumAnalyticService (classloader=PluginClassLoader(plugin=PluginDescriptor(name=CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4, id=codiumai.codiumai, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/PyCharm2023.1/plugins/codium-ai-plugin-0.5.14.jar, version=0.5.14, package=null, isBundled=false), packagePrefix=null, instanceId=129, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1034)
	at com.intellij.serviceContainer.ComponentManagerImpl.createLightService(ComponentManagerImpl.kt:970)
	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:774)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:726)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:670)
	at ai.codium.UtilsKt.getCodiumAnalyticService(Utils.kt:228)
	at ai.codium.CodiumErrorReportAutoSubmitterKt.addAutoSubmitter$lambda$3(CodiumErrorReportAutoSubmitter.kt:19)
	at com.intellij.util.containers.LockFreeCopyOnWriteArrayList.forEach(LockFreeCopyOnWriteArrayList.java:804)
	at com.intellij.diagnostic.MessagePool.notifyEntryAdded(MessagePool.java:92)
	at com.intellij.diagnostic.MessagePool$MessageGrouper.post(MessagePool.java:126)
	at com.intellij.diagnostic.MessagePool$MessageGrouper.run(MessagePool.java:111)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoClassDefFoundError: com/mixpanel/mixpanelapi/MixpanelAPI
	at ai.codium.analytic.CodiumAnalyticService.<init>(CodiumAnalyticService.kt:26)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:993)
	... 20 more
Caused by: java.lang.ClassNotFoundException: com.mixpanel.mixpanelapi.MixpanelAPI PluginClassLoader(plugin=PluginDescriptor(name=CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4, id=codiumai.codiumai, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/PyCharm2023.1/plugins/codium-ai-plugin-0.5.14.jar, version=0.5.14, package=null, isBundled=false), packagePrefix=null, instanceId=129, state=active)
	... 22 more

```

# Other Information
```
=== About ===
Build version: PyCharm 2023.1 Build: #PY-231.8109.197 March 29, 2023
Theme: Darcula
JRE: 17.0.6+10-b829.5, JetBrains s.r.o.
JVM: 17.0.6+10-b829.5, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 12.6.6 (x86_64)

=== Plugins ===
Custom plugins: [Tabnine AI Code Completion- JS Java Python TS Rust Go PHP & More (1.0.16), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.5.14)]
Disabled plugins:[]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/5tqXDzN7) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Should be fixed in upcoming 0.5.15
Please feel free to reopen/report if experience it again.
