### ISSUE TITLE
[Exception][PyCharm 2023.1.3] java.lang.NoClassDefFoundError: okhttp3/internal/Util

### ISSUE THREAD

**Issue by Blake-Bishop** [Codium-ai/codiumai-jetbrains-release#53]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.NoClassDefFoundError: okhttp3/internal/Util
	at ai.codium.CodiumInlayProviderBase.addCodiumTestsGenerationInlay(CodiumInlayProviderBase.kt:99)
	at ai.codium.python.CodiumPythonInlayProvider.access$addCodiumTestsGenerationInlay(CodiumPythonInlayProvider.kt:18)
	at ai.codium.python.CodiumPythonInlayProvider$getCollectorFor$1.collect(CodiumPythonInlayProvider.kt:47)
	at com.intellij.codeInsight.hints.CollectorWithSettings.collectHints(InlayHintsUtils.kt:90)
	at com.intellij.codeInsight.hints.InlayHintsPass.doCollectInformation$lambda$0(InlayHintsPass.kt:46)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$2(JobLauncherImpl.java:137)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$3(JobLauncherImpl.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at com.intellij.concurrency.JobLauncherImpl.processImmediatelyIfTooFew(JobLauncherImpl.java:144)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:44)
	at com.intellij.codeInsight.hints.InlayHintsPass.doCollectInformation(InlayHintsPass.kt:37)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:374)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:373)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:349)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:187)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:347)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ClassNotFoundException: okhttp3.internal.Util PluginClassLoader(plugin=PluginDescriptor(name=CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4, id=codiumai.codiumai, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\PyCharm2023.1\plugins\codium-ai-plugin-0.5.16.jar, version=0.5.16, package=null, isBundled=false), packagePrefix=null, instanceId=139, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 36 more

```

# Other Information
```
=== About ===
Build version: PyCharm 2023.1.3 Build: #PY-231.9161.41 June 20, 2023
Theme: Xcode-Dark
JRE: 17.0.7+10-b829.16, JetBrains s.r.o.
JVM: 17.0.7+10-b829.16, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [Requirements (2022.4.1), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.5.16), Nginx Configuration (2022.1.1), Xcode-Dark Theme (1.2.4), Ideolog (203.0.30.0), .env files support (2023.1), EnvFile (3.4.1), Casbin (0.1.14), HOCON (2023.1.0), Logstash Config Files Support (0.8.2)]
Disabled plugins:[Nginx Configuration Pro (2022.1.1)]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/q0AhMPq8) by [Unito](https://www.unito.io)

**Comment by ilia-krivonosov** [comment]
I have similar problem with CodiumAI plugin in Aqua 2023.1 EAP
## Stack trace ##
```
Failed to execute 'tests/generate' network request: stream was reset: INTERNAL_ERROR
okhttp3.internal.http2.StreamResetException: stream was reset: INTERNAL_ERROR
```
## IDE info ##
```
=== About ===
Build #QA-231.9206, built on June 21, 2023
Runtime version: 17.0.7+10-b829.14 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 5120M
Cores: 10
Metal Rendering is ON
Registry:
    ide.experimental.ui=true

=== Plugins ===
Non-Bundled Plugins:
    com.github.copilot (1.2.9.2684)
    codiumai.codiumai (0.5.16)
    allure-ee-idea (3.19.1)
    ru.adelf.idea.dotenv (2023.1)
```

**Comment by ArtsiomCh** [comment]
@ilia-krivonosov INTERNAL_ERROR is different issue. It mean something goes wrong on our backend. Usually trying again helps.

**Comment by ArtsiomCh** [comment]
@Blake-Bishop java.lang.NoClassDefFoundError: okhttp3/internal/Util is very strange exception... Did you saw it once or it happening regularly?
Did you install plugin from marketplace or manually?

**Comment by Blake-Bishop** [comment]
It has happened multiple times. I installed Codium via download from Chrome then following the instructions to manually add plugin from disk.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ArtsiomCh** [comment]
@Blake-Bishop Aha, then did you install it as **zip** file or unzip first and install as **jar**?
If latter then you left behind retrofit(okhttp) dependency we use for network communications. Please, uninstall plugin and install it again from **zip** or better just install from marketplace.
