### ISSUE TITLE
[Exception][PyCharm 2023.1.3] java.lang.Throwable: Project is already disposed: Project(name=IliDilinator, containerS...

### ISSUE THREAD

**Issue by thiagojramos** [Codium-ai/codiumai-jetbrains-release#54]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable: Project is already disposed: Project(name=IliDilinator, containerState=DISPOSE_IN_PROGRESS, componentStore=C:\Users\thiag\IliDilinator) (disposed)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.getCachedPsiFile(FileManagerImpl.java:376)
	at com.intellij.psi.impl.PsiDocumentManagerBase.getCachedPsiFile(PsiDocumentManagerBase.java:144)
	at com.intellij.psi.impl.PsiDocumentManagerBase.getCachedPsiFile(PsiDocumentManagerBase.java:126)
	at com.intellij.codeInsight.daemon.impl.PsiChangeHandler$1.beforeDocumentChange(PsiChangeHandler.java:59)
	at jdk.internal.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:120)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:85)
	at jdk.proxy2/jdk.proxy2.$Proxy87.beforeDocumentChange(Unknown Source)
	at com.intellij.openapi.editor.impl.DocumentImpl.lambda$beforeChangedUpdate$1(DocumentImpl.java:881)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgr

<TRIMMED STACKTRACE>

$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

# Other Information
```
=== About ===
Build version: PyCharm 2023.1.3 Build: #PY-231.9161.41 June 20, 2023
Theme: Light
JRE: 17.0.7+10-b829.16, JetBrains s.r.o.
JVM: 17.0.7+10-b829.16, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [Prisma ORM (231.9011.4), Case conversion (0.7.1), JetBrains Academy (2023.6-2023.1-974), Live Coding in Python (4.10.2), Evaluate Async Code (1.23), StarCoder (0.230627), UI Automation Support (231.8109.91), YouTrack Integration (2023.1.40), Grazie Professional (0.3.230), Rust (0.4.197.5401-231), ESLint Restart Service Action (0.0.1), Refactor-X (231.8109.91), Quick File Preview (1.6.4), GitHub Copilot (1.2.9.2684), Python Smart Execute (0.3.1), Quokka (1.0.389), Preview.js (1.23.6), Json Helper (1.2.0), Test Management (231.9161.14), Odoo Autocompletion Support (0.6.11), You.com Python Edit and Continue (0.9.6), Apache config (.htaccess) (231.9161.47), String Manipulation (9.9.0), MicroPython (1.4.1-2023.1), IRen (0.2.1), PowerShell (2.0.10), Makefile Language (231.8109.91), LivePlugin (0.8.6 beta), .env files support (2023.1), GitHub Theme (1.2.0), Python Security (1.28.0), CSV Editor (3.2.0-231), SonarLint (8.4.0.73538), BinEd - Binary/Hexadecimal Editor (0.2.8.1), Gist Snippet (1.1.0), WebP Support (231.8109.91), Lines Sorter (1.0.1), Run Configuration for TypeScript (2022.11.14-1), CMD Support (1.0.5), Statistic (4.2.7), MDX (231.8109.91), TinyPNG Image Optimizer (1.0.8), Fast Mouse Scrolling (1.6.1), Big Data Tools (231.9011.34), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.5.17), Mario Progress Bar (1.8), PyCharm Help (231.9161.41), Live Edit (231.8770.15), Batch Scripts Support (1.0.13), Inspection Lens (1.3.0), AliasImports (3.1), Rainbow CSV (2.0.2), Json Parser (1.4.1), Requirements (2022.4.1), ExcelReader (2023.6.1-222.232), R Language for IntelliJ (231.8770.15), Selenium UI Testing (231.8109.91), Database Navigator (3.3.9310.0), XPathView + XSLT (231.8770.15), Atom Material Icons (90.0.0), Tabnine AI Code Completion- JS Java Python TS Rust Go PHP & More (1.0.20), YAML/Ansible support (0.11.2), Writerside (2023.06.3718), Perl (2023.1.2), TeXiFy IDEA (0.7.30), Resource Bundle Editor (231.8109.91), React Buddy (2023.2.4-231), Power Mode II (102.201), Command Line Tool (231.9161.47), File Expander (2.1), Scratch (1.10), CamelCase (3.0.12), Hunspell (231.8109.91), Aqua (231.9161.14), Full Line Code Completion (232.5561), WebAssembly (1.4.231), Regex Rename Files (1.2.4), .ignore (4.5.1)]
Disabled plugins:[Docker (231.9161.41), Vite (231.9161.41), Shared Project Indexes (231.9161.41), WarmNeon Color Scheme (231.9161.41), Go Template (231.8109.91), Terraform and HCL (231.8109.91), Space (231.9161.41), Next.js Support (231.9161.41), Vue.js (231.9161.41), Node.js (231.9161.41), Rider UI Theme Pack (0.14.0), Dart (231.9161.14), Handlebars/Mustache (231.8770.3), GitLab Projects (2.1.1), IntelliVue (1.1.32), Karma (231.9161.41), Puppet (231.9161.41), Shared Indexes for Python (231.9161.41), Twilight Color Scheme (231.9161.41), Qodana (231.9161.41), Vagrant (231.9161.41), Japanese Language Pack / 日本語言語パック (231.283), Angular and AngularJS (231.9161.41), Node.js Remote Interpreter (231.9161.41), Subversion (231.9161.41), Monokai Color Scheme (231.9161.41)]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/YKFg4Djq) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Thanks for reporting! Will be fixed in next version.
