### ISSUE TITLE
[Exception][PyCharm 2023.1] A suspiciously high nesting of suppressPrioritizing, forgot to call restorePrioritizing?

### ISSUE THREAD

**Issue by m-root** [Codium-ai/codiumai-jetbrains-release#55]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:127)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:216)
	at com.intellij.openapi.progress.impl.CoreProgressManager.suppressPrioritizing(CoreProgressManager.java:824)
	at com.intellij.openapi.progress.impl.CoreProgressManager.avoidBlockingPrioritizingThread(CoreProgressManager.java:879)
	at com.intellij.openapi.progress.impl.CoreProgressManager.sleepIfNeededToGivePriorityToAnotherThread(CoreProgressManager.java:840)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runCheckCanceledHooks(ProgressManagerImpl.java:191)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:145)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:227)
	at com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled(ProgressIndicatorProvider.java:23)
	at com.intellij.psi.impl.source.tree.CompositeElement.getPsi(CompositeElement.java:687)
	at com.intellij.psi.impl.source.SourceTreeToPsiMap.treeElementToPsi(SourceTreeToPsiMap.java:16)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getNextSibling(SharedImplUtil.java:46)
	at com.intellij.psi.impl.source.tree.LeafPsiElement.getNextSibling(LeafPsiElement.java:75)
	at com.intellij.psi.util.PsiTreeUtil.getChildrenOfAnyType(PsiTreeUtil.java:396)
	at ai.codium.language.PyLanguageService.doGetSupportedElements$codium_ai_plugin(PyLanguageService.kt:26)
	at ai.codium.language.LanguageService.getSupportedElements(LanguageService.kt:17)
	at ai.codium.ui.structureview.CodiumStructureViewElement.getChildren(CodiumStructureViewElement.kt:43)
	at ai.codium.ui.structureview.CodiumStructureViewElement.getChildren(CodiumStructureViewElement.kt:19)
	at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.initChildren(TreeElementWrapper.java:35)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.rebuildSubtree(CachingChildrenTreeNode.java:207)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.ensureChildrenAreInitialized(CachingChildrenTreeNode.java:41)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.getChildren(CachingChildrenTreeNode.java:33)
	at com.intellij.ide.structureView.newStructureView.StructureViewComponent$MyNodeWrapper.getChildren(StructureViewComponent.java:834)
	at com.intellij.ide.util.treeView.smartTree.SmartTreeStructure.getChildElements(SmartTreeStructure.java:62)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:410)
	at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:328)
	at com.intellij.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:322)
	at com.intellij.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:342)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.ge

<TRIMMED STACKTRACE>

Service.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$1(ProgressManager.java:70)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:70)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:107)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:72)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:187)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:165)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:431)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:248)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:28)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:221)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

# Other Information
```
=== About ===
Build version: PyCharm 2023.1 Build: #PY-231.8109.197 March 29, 2023
Theme: Dark
JRE: 17.0.6+10-b829.5, JetBrains s.r.o.
JVM: 17.0.6+10-b829.5, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.4 (aarch64)

=== Plugins ===
Custom plugins: [GitHub Copilot (1.2.9.2684), Machinet AI GPT4 & ChatGPT (2022.1.43), EnvFile (3.4.1), Ideolog (203.0.30.0), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.5.16), Cody AI by Sourcegraph (3.0.2), One Dark theme (5.8.0), WakaTime (14.1.5), Requirements (2022.4.1), Solidity (2.4.2)]
Disabled plugins:[Requirements Pro (2022.4.1), Copilot Dark Theme (1.0.2)]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/88ECXqwf) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Hi @m-root !
Thanks for reporting. It looks like it's some bug in IDE internals. We've seen such issues time to time on user's side but not able to reproduce. :(  Probably somehow related to the project size, but can't verity...
We created [the issue in JetBrains issues tracker](https://youtrack.jetbrains.com/issue/IDEA-323502/Error-A-suspiciously-high-nesting-of-suppressPrioritizing-logged-inside-PsiTreeUtil.findChildOfType) and JetBrains team need to see "threadDump.txt" to explore.
Please try to find it (or ask JB team in the issue where it's located) and provide it to JB team for analyzing.

**Comment by ljchen1** [comment]
Hi, I am from the JetBrains team. If you see this error in the IDEA's IDE fatal error dialog, there should be a `threadDump.txt` attachment in the left list. If you don't have it, you could also use the IDE main menu `Help | Collect Logs and Diagnostic Data` to get the full log, upload it here https://uploads.jetbrains.com/, and share the upload id so we could check any clues there.

**Comment by ArtsiomCh** [comment]
Seems like we fixed it in latest versions, please feel free to report if experience it again!
