### ISSUE TITLE
[Exception][PyCharm 2022.2.4] A suspiciously high nesting of suppressPrioritizing, forgot to call restorePrioritizing?

### ISSUE THREAD

**Issue by shaharler1991** [Codium-ai/codiumai-jetbrains-release#64]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:127)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:194)
	at com.intellij.openapi.progress.impl.CoreProgressManager.suppressPrioritizing(CoreProgressManager.java:828)
	at com.intellij.openapi.progress.impl.CoreProgressManager.avoidBlockingPrioritizingThread(CoreProgressManager.java:883)
	at com.intellij.openapi.progress.impl.CoreProgressManager.sleepIfNeededToGivePriorityToAnotherThread(CoreProgressManager.java:844)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runCheckCanceledHooks(ProgressManagerImpl.java:191)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:147)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:219)
	at com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled(ProgressIndicatorProvider.java:23)
	at com.intellij.psi.impl.source.tree.CompositeElement.getPsi(CompositeElement.java:687)
	at com.intellij.psi.impl.source.SourceTreeToPsiMap.treeElementToPsi(SourceTreeToPsiMap.java:16)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getNextSibling(SharedImplUtil.java:46)
	at com.intellij.psi.impl.source.tree.LeafPsiElement.getNextSibling(LeafPsiElement.java:75)
	at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getNextSibling(PsiWalkingState.java:31)
	at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getNextSibling(PsiWalkingState.java:28)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:61)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:49)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:76)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
	at com.intellij.psi.util.PsiTreeUtil$4.visitElement(PsiTreeUtil.java:924)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at com.jetbrains.python.psi.impl.PyBaseElementImpl.accept(PyBaseElementImpl.java:64)
	at com.intellij.psi.util.PsiTreeUtil.processElements(PsiTreeUtil.java:920)
	at com.intellij.psi.util.PsiTreeUtil.findChildOfType(PsiTreeUtil.java:235)
	at com.intellij.psi.util.PsiTreeUtil.findChildOfType(PsiTreeUtil.java:201)
	at ai.codium.language.LanguageService.hasErrorElements(LanguageService.kt:30)
	at ai.codium.ui.structureview.CodiumStructureViewRootElement.getChildren(CodiumStructureViewElement.kt:82)
	at ai.codium.ui.structureview.CodiumStructureViewRootElement.getChildren(CodiumStructureViewElement.kt:62)
	at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.initChildren(TreeElementWrapper.java:50)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.rebuildSubtree(CachingChildrenTreeNode.java:207)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.ensureChildrenAreInit

<TRIMMED STACKTRACE>

tils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:205)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:183)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:487)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

# Other Information
```
=== About ===
Build version: PyCharm 2022.2.4 Build: #PY-222.4459.20 November 17, 2022
Theme: Dracula
JRE: 17.0.5+7-b469.71, JetBrains s.r.o.
JVM: 17.0.5+7-b469.71, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.4.1 (x86_64)

=== Plugins ===
Custom plugins: [CSV Editor (3.0.3-222), OpenAPI Specifications (222.4459.16), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.5.19), GitHub Copilot (1.2.9.2684), Dracula Theme (1.14.3), Vue.js (222.4459.28), New Relic CodeStream: GitHub, GitLab, PRs and Code Review (14.23.0+503), Makefile Language (222.4459.16)]
Disabled plugins:[Gitlab CI Dashboard (2023.3.2), AWS Toolkit (1.67-222)]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/KI6cqZSE) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Thanks for reporting! 
Duplicate of #55
