### ISSUE TITLE
[Exception][PyCharm 2022.3.3] A suspiciously high nesting of suppressPrioritizing, forgot to call restorePrioritizing?

### ISSUE THREAD

**Issue by marjeta007** [Codium-ai/codiumai-jetbrains-release#70]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:127)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:212)
	at com.intellij.openapi.progress.impl.CoreProgressManager.suppressPrioritizing(CoreProgressManager.java:824)
	at com.intellij.openapi.progress.impl.CoreProgressManager.avoidBlockingPrioritizingThread(CoreProgressManager.java:879)
	at com.intellij.openapi.progress.impl.CoreProgressManager.sleepIfNeededToGivePriorityToAnotherThread(CoreProgressManager.java:840)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runCheckCanceledHooks(ProgressManagerImpl.java:191)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.checkCanceled(AbstractProgressIndicatorBase.java:150)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.checkCanceled(AbstractProgressIndicatorExBase.java:103)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:141)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:221)
	at com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled(ProgressIndicatorProvider.java:23)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getGreenStub(StubBasedPsiElementBase.java:350)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getParent(StubBasedPsiElementBase.java:314)
	at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getParent(PsiWalkingState.java:37)
	at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getParent(PsiWalkingState.java:14)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:64)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:49)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:62)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
	at com.intellij.psi.util.PsiTreeUtil$4.visitElement(PsiTreeUtil.java:924)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at com.jetbrains.python.psi.impl.PyBaseElementImpl.accept(PyBaseElementImpl.java:64)
	at com.intellij.psi.util.PsiTreeUtil.processElements(PsiTreeUtil.java:920)
	at com.intellij.psi.util.PsiTreeUtil.findChildOfType(PsiTreeUtil.java:235)
	at com.intellij.psi.util.PsiTreeUtil.findChildOfType(PsiTreeUtil.java:201)
	at ai.codium.la

<TRIMMED STACKTRACE>

t com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:68)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:106)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:71)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:187)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:165)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:475)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:243)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:216)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:205)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

# Other Information
```
=== About ===
Build version: PyCharm 2022.3.3 Build: #PY-223.8836.43 March 10, 2023
Theme: Darcula
JRE: 17.0.6+1-b653.34, JetBrains s.r.o.
JVM: 17.0.6+1-b653.34, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11 10.0 (amd64)

=== Plugins ===
Custom plugins: [Test Data (223.8214.6), JetBrains Academy (2023.6-2022.3-1320), GitHub Copilot (1.2.13.2776), CodeGPT (2.0.5), BlackConnect (0.6.1), Ideolog (222.1.0.0), Pylint (0.15.0), Test Management (223.8214.6), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.5.20), PyCharm Help (222.4554.11), .ignore (4.4.4)]
Disabled plugins:[WSL Support Framework (223.8836.43), WebP Support (223.8836.15), Tailwind CSS (223.8836.43), Karma (223.8836.43), Endpoints (223.8836.43), Vite (223.8836.43), W3C Validators (223.7571.203), SSH Remote Run (223.8836.43), AWS CloudFormation (223.8617.8), Next.js Support (223.8836.43), AWS Toolkit (1.72-223), Sass (223.8836.43), JavaScript and TypeScript (223.8836.43), Vue.js (223.8836.43), FTP/SFTP/WebDAV Connectivity (223.8836.43), Perforce Helix Core (223.8836.43), Qodana (223.8836.43), Apache config (.htaccess) (223.8836.46), Subversion (223.8836.43), Prettier (223.8836.43), Node.js Remote Interpreter (223.8836.43), Angular and AngularJS (223.8836.43), JavaScript Debugger (223.8836.43), Docker (223.8836.43), Vagrant (223.8836.43), TSLint (223.8836.43), Big Data Tools (223.8836.7), Space (223.8836.43), Styled Components & Styled JSX (223.8836.43), Polymer & Web Components (223.8836.43), Webpack (223.8836.43), Node.js (223.8836.43), JavaScript Intention Power Pack (223.8836.43), Puppet (223.8836.43), Mercurial (223.8836.43), Less (223.8836.43)]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/euvGLjLE) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Duplicate of https://github.com/Codium-ai/codiumai-jetbrains-release/issues/55
