### ISSUE TITLE
[Exception][IDEA 2023.2] *** exception class was changed or removed

### ISSUE THREAD

**Issue by JesusTheHun** [Codium-ai/codiumai-jetbrains-release#73]
# User Description
I just pasted some content

# Stack Trace
```
  A suspiciously high nesting of suppressPrioritizing, forgot to call restorePrioritizing?
  
  java.lang.Throwable
at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:131)
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:384)
at com.intellij.openapi.progress.impl.CoreProgressManager.suppressPrioritizing(CoreProgressManager.java:824)
at com.intellij.openapi.progress.impl.CoreProgressManager.avoidBlockingPrioritizingThread(CoreProgressManager.java:879)
at com.intellij.openapi.progress.impl.CoreProgressManager.sleepIfNeededToGivePriorityToAnotherThread(CoreProgressManager.java:840)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.runCheckCanceledHooks(ProgressManagerImpl.java:192)
at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:145)
at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:231)
at com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled(ProgressIndicatorProvider.java:23)
at com.intellij.psi.impl.source.tree.CompositeElement.getPsi(CompositeElement.java:676)
at com.intellij.psi.impl.source.SourceTreeToPsiMap.treeElementToPsi(SourceTreeToPsiMap.java:15)
at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:37)
at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:737)
at com.intellij.psi.util.PsiTreeUtil.getChildrenOfAnyType(PsiTreeUtil.java:399)
at ai.codium.language.JsTsLanguageService.getClassOnlyChildren(JsTsLanguageService.kt:92)
at ai.codium.language.JsTsLanguageService.getElementsForClass(JsTsLanguageService.kt:49)
at ai.c

<TRIMMED STACKTRACE>

enapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:111)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:76)
at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:188)
at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:165)
at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:433)
at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
at java.base/java.lang.Thread.run(Thread.java:833)

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2023.2 Build: #IU-232.8660.185 July 26, 2023
Theme: Darcula
JRE: 17.0.7+7-b1000.6, JetBrains s.r.o.
JVM: 17.0.7+7-b1000.6, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.4.1 (aarch64)

=== Plugins ===
Custom plugins: [PHP Docker (232.8660.142), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.5.22), PHP Remote Interpreter (232.8660.142), Conventional Commit (0.22.0), CodeGlance Pro (1.6.7), PHP Command Line Tool (232.8660.158), PHP Annotations (9.4.0), PHP (232.8660.185), AI Assistant (232.9191), Extra Icons (2023.2.8-231), AsciiDoc (0.38.20)]
Disabled plugins:[Jakarta EE: Server Pages (JSP) (232.8660.185), Grazie Lite (232.8660.185), TestNG (232.8660.185), Maestro (1.3.1-2023.1), Quarkus (232.8660.185), AOP Pointcut Language (232.8660.185), Refactor-X (232.8660.185), Visual Studio Keymap (232.8660.185), Ant (232.8660.185), AWS Toolkit (1.74-232), TSLint (232.8660.185), WildFly (232.8660.185), Thymeleaf (232.8660.185), PHP Toolbox (6.2.0), Copyright (232.8660.185), Cucumber for Java (232.8660.185), Groovy (232.8660.185), Jakarta EE: Persistence (JPA) (232.8660.185), Jakarta EE: Application Servers (232.8660.185), UI Designer (232.8660.185), Qodana (232.8660.185), Android (2022.3.1 Beta 2.232.8660.185), Tomcat and TomEE (232.8660.185), GlassFish (232.8660.185), Behat Support (232.8660.142), Android Design Tools (232.8660.185), Prisma ORM (232.8660.129), Kotlin (232-1.9.0-IJ8660.185), Polymer & Web Components (232.8660.185), Protocol Buffers (232.8660.185), Subversion (232.8660.185), Less (232.8660.185), Gradle (232.8660.185), Dev Containers (232.8660.202), FreeMarker (232.8660.185), gRPC (232.8660.185), Eclipse Keymap (232.8660.185), WebP Support (232.8660.185), Reactive Streams (232.8660.185), Twig (232.8660.158), Hibernate (232.8660.185), Run Configuration for TypeScript (2022.11.14-1), NetBeans Keymap (232.8660.185), Ktor (232.8660.185), Mercurial (232.8660.185), Gherkin (232.8660.185), Next.js Support (232.8660.185), Angular and AngularJS (232.8660.185), Dependency Structure Matrix (232.8660.185), Plugin DevKit (232.8660.185), Gradle-Java (232.8660.185), Styled Components & Styled JSX (232.8660.185), Vue.js (232.8660.185), Gradle-Java-Analysis (232.8660.185), IDE Features Trainer (232.8660.185), Eclipse Interoperability (232.8660.185), Micronaut (232.8660.185), JavaFX (232.8660.185), Jakarta EE: Gradle Integration (232.8660.185), Webpack (232.8660.185), Terminal for Gateway (232.8660.185), Karma (232.8660.185), Nx Console Idea (0.58.0), Tailwind Formatter (2.0.7), Gradle Extension (232.8660.185), Diagrams (232.8660.185), API Recommenders (232.8660.185), Persistence Frameworks (232.8660.185), Codeception Framework (232.8660.185), Nx Console (1.10.0), OpenAPI Specifications (232.8660.185), EditorConfig (232.8660.185), Time Tracking (232.8660.185), Space (232.8660.185), Remote Development Gateway (232.8660.185), Perforce Helix Core (232.8660.185), Sass (232.8660.185), Gradle-Maven (232.8660.185), Gradle Dependency Updater Implementation (232.8660.185), Cucumber for Groovy (232.8660.185), Apache Velocity (232.8660.185)]
```

**Comment by JesusTheHun** [comment]
@ArtsiomCh Hi ! It happened again. I believe it has something to do with symbol deletion : 
I just remove a symbol (a constant in this case) and I saved. Prettier triggered and the error happened.

**Comment by ArtsiomCh** [comment]
Tried different ways to delete and save and still no luck with triggering that error :( 
@JesusTheHun next time you'll get it, please try to find that `threadDump.txt` mentioned above and provide it to JetBrains/me to explore.
