### ISSUE TITLE
[Exception][PyCharm 2023.2] *** exception class was changed or removed

### ISSUE THREAD

**Issue by gaillota** [Codium-ai/codiumai-jetbrains-release#80]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
  A suspiciously high nesting of suppressPrioritizing, forgot to call restorePrioritizing?
  
  java.lang.Throwable
at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:131)
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:384)
at com.intellij.openapi.progress.impl.CoreProgressManager.suppressPrioritizing(CoreProgressManager.java:824)
at com.intellij.openapi.progress.impl.CoreProgressManager.avoidBlockingPrioritizingThread(CoreProgressManager.java:879)
at com.intellij.openapi.progress.impl.CoreProgressManager.sleepIfNeededToGivePriorityToAnotherThread(CoreProgressManager.java:840)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.runCheckCanceledHooks(ProgressManagerImpl.java:192)
at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:145)
at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:231)
at com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled(ProgressIndicatorProvider.java:23)
at com.intellij.psi.impl.source.tree.CompositeElement.getPsi(CompositeElement.java:676)
at com.intellij.psi.impl.source.SourceTreeToPsiMap.treeElementToPsi(SourceTreeToPsiMap.java:15)
at com.intellij.psi.impl.source.tree.SharedImplUtil.getNextSibling(SharedImplUtil.java:45)
at com.intellij.psi.impl.source.tree.LeafPsiElement.getNextSibling(LeafPsiElement.java:61)
at com.intellij.psi.util.PsiTreeUtil.getChildrenOfAnyType(PsiTreeUtil.java:399)
at ai.codium.language.PyLanguageService.doGetSupportedElementsForFileLevel$codium_ai_plugin(PyLanguageService.kt:28)
at ai.codium.language.LanguageService.hasErrorElements(LanguageService.kt:52)
at ai.codium.ui.structureview.CodiumStructureViewRootElement.getChildren(CodiumStructureViewChildElement.kt:93)
at ai.codium.ui.structureview.CodiumStructureViewRootElement.getChildren(CodiumStructureViewChildElement.kt:77)
at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.initChildren(TreeElementWrapper.java:35)
at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.rebuildSubtree(CachingChildrenTreeNode.java:207)
at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.ensureChildrenAreInitialized(CachingChildrenTreeNode.java:41)
at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.getChildren(CachingChildrenTreeNode.java:33)
at com.intellij.ide.structureView.newStructureView.StructureViewComponent$MyNodeWrapper.getChildren(StructureViewComponent.java:841)
at com.intellij.ide.util.treeView.smartTree.SmartTreeStructure.getChildElements(SmartTreeStructure.java:62)
at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:411)
at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:329)
at com.intellij.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:323)
at com.intellij.ui.tree.StructureTreeModel.getChildren(StructureTreeM

<TRIMMED STACKTRACE>

ellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:133)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:114)
at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:111)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:76)
at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:188)
at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:165)
at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:433)
at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
at java.base/java.lang.Thread.run(Thread.java:833)

```

# Other Information
```
=== About ===
Build version: PyCharm 2023.2 Build: #PC-232.8660.197 July 26, 2023
Theme: Light
JRE: 17.0.7+7-b1000.6, JetBrains s.r.o.
JVM: 17.0.7+7-b1000.6, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.1 (aarch64)

=== Plugins ===
Custom plugins: [Terraform and HCL (232.8660.88), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.5.25), Makefile Language (232.8660.88), Ini (232.8660.205), BlackConnect (0.6.1), Gherkin (232.8660.88), Docker (232.8660.205), JetClient - The Ultimate REST Client (2023.1.14-232), GitHub Copilot (1.2.18.2908)]
Disabled plugins:[]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/LcRzDLjD) by [Unito](https://www.unito.io)

**Comment by aldanchenko** [comment]
Hi @gaillota 

Thanks for reporting! We work on fixing this issue. Other users also reported this issue. Please check [here](https://github.com/Codium-ai/codiumai-jetbrains-release/issues/73) for example.

Also we opened issue in JetBrains YouTrack - [please check here](https://youtrack.jetbrains.com/issue/IDEA-323502/Error-A-suspiciously-high-nesting-of-suppressPrioritizing-logged-inside-PsiTreeUtil.findChildOfType). Also you could share your stack trace or other information here too. 

We will let you know when we fix the problem or if more information is needed. 

Best regards,
Alex

**Comment by ArtsiomCh** [comment]
Thanks for reporting, we have that hard to catch issue for a long time. Would you mind please follow the https://github.com/Codium-ai/codiumai-jetbrains-release/issues/55#issuecomment-1622995021 to find threadDump.txt and provide it to them for analyzing:

>Hi, I am from the JetBrains team. If you see this error in the IDEA's IDE fatal error dialog, there should be a threadDump.txt attachment in the left list. If you don't have it, you could also use the IDE main menu Help | Collect Logs and Diagnostic Data to get the full log, upload it here https://uploads.jetbrains.com/, and share the upload id so we could check any clues there.

PS Also would be nice if you can share some more details when it happened, cause we can't reproduce it :(
Can you reproduce that issue? What kind/size of the project you have? Any specific action you did just before it happened?

**Comment by ArtsiomCh** [comment]
Seems like we fixed it in latest versions, please feel free to report if experience it again!
