### ISSUE TITLE
[Exception][PyCharm 2023.1] java.lang.Throwable: File is not valid:file:///private/var/folders/52/3wqrwbx920d9zz019bc...

### ISSUE THREAD

**Issue by yossideepkeep** [Codium-ai/codiumai-jetbrains-release#84]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable: File is not valid:file:///private/var/folders/52/3wqrwbx920d9zz019bckc01m0000gn/T/AppTranslocation/016A3E50-5F5C-4812-96F0-8D91ABDC8A46/d/PyCharm CE.app/Contents/plugins/python-ce/helpers/python-skeletons (invalid)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectory(FileManagerImpl.java:394)
	at com.intellij.psi.impl.PsiManagerImpl.findDirectory(PsiManagerImpl.java:169)
	at com.jetbrains.python.codeInsight.userSkeletons.PyUserSkeletonsUtil.getUserSkeletonForModuleQName(PyUserSkeletonsUtil.java:181)
	at com.jetbrains.python.codeInsight.userSkeletons.PyUserSkeletonsUtil.getUserSkeletonForFile(PyUserSkeletonsUtil.java:243)
	at com.jetbrains.python.codeInsight.userSkeletons.PyUserSkeletonsUtil.getUserSkeletonWithContext(PyUserSkeletonsUtil.java:153)
	at com.jetbrains.python.codeInsight.userSkeletons.PyUserSkeletonsUtil.getUserSkeleton(PyUserSkeletonsUtil.java:147)
	at com.jetbrains.python.codeInsight.userSkeletons.PyUserSkeletonsModuleMembersProvider.resolveMember(PyUserSkeletonsModuleMembersProvider.java:24)
	at com.jetbrains.python.psi.types.PyModuleType.resolveByMembersProviders(PyModuleType.java:265)
	at com.jetbrains.python.psi.types.PyModuleType.resolveMemberInPackageOrModule(PyModuleType.java:110)
	at com.jetbrains.python.psi.types.PyModuleType.resolveMember(PyModuleType.java:73)
	at com.jetbrains.python.psi.resolve.PyResolveUtil.doResolveQualifiedNameInScope(PyResolveUtil.java:272)
	at com.jetbrains.python.psi.resolve.PyResolveUtil.lambda$resolveQualifiedNameInScope$4(PyResolveUtil.java:231)
	at com.jetbrains.python.psi.PyUtil.getNullableParameterizedCachedValue(PyUtil.java:670)
	at com.jetbrains.python.psi.PyUtil.getParameterizedCachedValue(PyUtil.java:648)
	at com.jetbrains.python.psi.resolve.PyResolveUtil.resolveQualifiedNameInScope(PyResolveUtil.java:230)
	at com.jetbrains.python.psi.impl.PyClassImpl.classTypeFromQName(PyClassImpl.java:1716)
	at com.jetbrains.python.psi.impl.PyClassImpl.fillSuperClassesNoSwitchToAst(PyClassImpl.java:1411)
	at com.jetbrains.python.psi.impl.PyClassImpl.doGetSuperClassTypes(PyClassImpl.java:1356)
	at com.jetbrains.python.psi.PyUtil.getNullableParameterizedCachedValue(PyUtil.java:670)
	at com.jetbrains.python.psi.PyUtil.getParameterizedCachedValue(PyUtil.java:648)
	at com.jetbrains.python.psi.impl.PyClassImpl.getSuperClassTypes(PyClassImpl.java:1347)
	at com.jetbrains.python.psi.types.PyClassTypeImpl.getSuperClassTypes(PyClassTypeImpl.java:119)
	at com.jetbrains.python.psi.impl.PyClassImpl.mroLinearize(PyClassImpl.java:417)
	at com.jetbrains.python.psi.impl.PyClassImpl.getMROAncestorTypes(PyClassImpl.java:1641)
	at com.jetbrains.python.psi.impl.PyClassImpl.lambda$getAncestorTypesWithMetaClassInstances$10(PyClassImpl.java:1444)
	at com.jetbrains.python.psi.PyUtil.getNullableParameterizedCachedValue(PyUtil.java:670)
	at com.jetbrains.python.psi.PyUtil.getParameterizedCachedValue(PyUtil.java:648)
	at com.jetb

<TRIMMED STACKTRACE>

er.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2804)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:790)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:763)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:761)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:614)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:569)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

# Other Information
```
=== About ===
Build version: PyCharm 2023.1 Build: #PC-231.8109.197 March 29, 2023
Theme: Darcula
JRE: 17.0.6+10-b829.5, JetBrains s.r.o.
JVM: 17.0.6+10-b829.5, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 12.6.3 (aarch64)

=== Plugins ===
Custom plugins: [CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.5.22), GitHub Copilot (1.2.16.2847), Nyan Progress Bar (1.14)]
Disabled plugins:[]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/mVnfhaby) by [Unito](https://www.unito.io)

**Comment by aldanchenko** [comment]
Hi @yossideepkeep 

Thank you for reporting!

Please try the newest version - 0.5.29. Could you share some steps to reproduce this issue?

Best regards,
Alex

**Comment by yossideepkeep** [comment]
This is the first time it happened to me with Codium, I assume it was
related to the old version of PyCharm in combination with poetry packages.

Unfortunately I can't give you more information than that.

**Comment by ArtsiomCh** [comment]
Sorry for late response 😔
Do you still experience such issues? 
Seems like we fixed it in latest versions, please feel free to report if experience it again!
