### ISSUE TITLE
[Exception][IDEA 2023.2] *** exception class was changed or removed

### ISSUE THREAD

**Issue by sid-gupta-ak** [Codium-ai/codiumai-jetbrains-release#86]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
  A suspiciously high nesting of suppressPrioritizing, forgot to call restorePrioritizing?
  
  java.lang.Throwable
at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:131)
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:384)
at com.intellij.openapi.progress.impl.CoreProgressManager.suppressPrioritizing(CoreProgressManager.java:824)
at com.intellij.openapi.progress.impl.CoreProgressManager.avoidBlockingPrioritizingThread(CoreProgressManager.java:879)
at com.intellij.openapi.progress.impl.CoreProgressManager.sleepIfNeededToGivePriorityToAnotherThread(CoreProgressManager.java:840)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.runCheckCanceledHooks(ProgressManagerImpl.java:192)
at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:145)
at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:231)
at com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled(ProgressIndicatorProvider.java:23)
at com.intellij.psi.impl.source.tree.CompositeElement.getPsi(CompositeElement.java:676)
at com.intellij.psi.impl.source.SourceTreeToPsiMap.treeElementToPsi(SourceTreeToPsiMap.java:15)
at com.intellij.psi.impl.source.tree.SharedImplUtil.getNextSibling(SharedImplUtil.java:45)
at com.intellij.psi.impl.source.tree.LeafPsiElement.getNextSibling(LeafPsiElement.java:61)
at com.intellij.psi.util.PsiTreeUtil.getChildrenOfAnyType(PsiTreeUtil.java:399)
at ai.codium.language.JsTsLanguageService.getAllNamedClasses(JsTsLanguageService.kt:81)
at ai.codium.language.JsTsLanguageService.getSupportedClasses(JsTsLangua

<TRIMMED STACKTRACE>

.ProgressManager.runProcess(ProgressManager.java:71)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:111)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:76)
at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:188)
at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:165)
at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:433)
at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
at java.base/java.lang.Thread.run(Thread.java:833)

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2023.2 Build: #IU-232.8660.185 July 26, 2023
Theme: Light
JRE: 17.0.7+7-b1000.6, JetBrains s.r.o.
JVM: 17.0.7+7-b1000.6, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.5 (aarch64)

=== Plugins ===
Custom plugins: [AceJump (3.8.14), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.5.27), Nginx Configuration (2022.1.1), IdeaVim (2.4.1), JetClient - The Ultimate REST Client (2023.1.14-232), GraphQL (4.0.2), Run Configuration for TypeScript (2022.11.14-1), IdeaVim-EasyMotion (1.10)]
Disabled plugins:[Jakarta EE Platform (232.8660.185), Jakarta EE: Web/Servlets (232.8660.185), JUnit (232.8660.185), Gradle Extension (232.8660.185), Subversion (232.8660.185), Code With Me (232.8660.185), Maven (232.8660.185), Hibernate (232.8660.185), Spring Web (232.8660.185), FreeMarker (232.8660.185), JVM Microservices Frameworks (232.8660.185), Plugin DevKit (232.8660.185), Vue.js (232.8660.185), Visual Studio Keymap (232.8660.185), Quarkus (232.8660.185), Jakarta EE: Server Pages (JSP) (232.8660.185), Spring Boot (232.8660.185), Angular and AngularJS (232.8660.185), Persistence Frameworks (232.8660.185), Maven Extension (232.8660.185), Thymeleaf (232.8660.185), Spring (232.8660.185), Time Tracking (232.8660.185), Jakarta EE: Messaging (JMS) (232.8660.185), Ant (232.8660.185), Apache Velocity (232.8660.185), Mercurial (232.8660.185), Protocol Buffers (232.8660.185), Tomcat and TomEE (232.8660.185), Toml (232.8660.185), TestNG (232.8660.185), Task Management (232.8660.185), Reactive Streams (232.8660.185), Spring Data (232.8660.185), Eclipse Keymap (232.8660.185), Webpack (232.8660.185), Jakarta EE: Persistence (JPA) (232.8660.185), gRPC (232.8660.185), Spring Initializr (232.8660.185), Jakarta EE: Application Servers (232.8660.185), Java Stream Debugger (232.8660.185), Cucumber for Java (232.8660.185), Gherkin (232.8660.185), UI Designer (232.8660.185), Java Internationalization (232.8660.185), Jakarta EE: Bean Validation (232.8660.185), Karma (232.8660.185), Jakarta EE: Gradle Integration (232.8660.185), JavaFX (232.8660.185), Ktor (232.8660.185), Eclipse Interoperability (232.8660.185), WildFly (232.8660.185), AOP Pointcut Language (232.8660.185), Code Coverage for Java (232.8660.185), Spring Integration Patterns (232.8660.185), Spring Messaging (232.8660.185), Java Bytecode Decompiler (232.8660.185), Android Design Tools (232.8660.185), Perforce Helix Core (232.8660.185), Gradle-Maven (232.8660.185), Kotlin (232-1.9.0-IJ8660.185), Qodana (232.8660.185), Spring Cloud (232.8660.185), Gradle-Java (232.8660.185), Next.js Support (232.8660.185), Gradle-Java-Analysis (232.8660.185), Spring Security (232.8660.185), Jakarta EE: RESTful Web Services (JAX-RS) (232.8660.185), NetBeans Keymap (232.8660.185), Cucumber for Groovy (232.8660.185), Jakarta EE: Expression Language (EL) (232.8660.185), Lombok (232.8660.185), Gradle Dependency Updater Implementation (232.8660.185), Gradle (232.8660.185), GlassFish (232.8660.185), Micronaut (232.8660.185), Space (232.8660.185), Jakarta EE: Contexts and Dependency Injection (CDI) (232.8660.185), Android (2022.3.1 Beta 2.232.8660.185)]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/uC4umQrP) by [Unito](https://www.unito.io)

**Comment by aldanchenko** [comment]
Hi @sid-gupta-ak 

Thanks for reporting! We are working on fixing this issue. Other users also reported this issue. Please check https://github.com/Codium-ai/codiumai-jetbrains-release/issues/73 for example.

Also we opened issue in JetBrains YouTrack - [please check here](https://youtrack.jetbrains.com/issue/IDEA-323502/Error-A-suspiciously-high-nesting-of-suppressPrioritizing-logged-inside-PsiTreeUtil.findChildOfType). Also you could share your stack trace or other information here too.

We will let you know when we fix the problem or if more information is needed.

Best regards,
Alex
