### ISSUE TITLE
[IDEA 2023.2.1] Every 5 seconds whole IDE stucks for 5 seconds

### ISSUE THREAD

**Issue by Villar74** [Codium-ai/codiumai-jetbrains-release#87]
After installing and starting use Codium AI i got trouble with my IDE. It stucks for 5 seconds every 5 seconds making this plugin  hard to use. It starts in 2023.1 IDEA and yesterday after update plugin it was fixed, but today i update to new webstorm version and this problem returns. 

I tried uninstall and install plugin again but lags still happens with same period.

Here are my IDE version
```
IntelliJ IDEA 2023.2.1 (Ultimate Edition)
Build #IU-232.9559.62, built on August 23, 2023
Licensed 
Runtime version: 17.0.8+7-b1000.8 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    org.jetbrains.completion.full.line (233.2912)
    com.rmondjone.jsontotypescript (2023.1.2)
    co.bito.bito-intellij (1.1.5)
    com.github.anuragkanwar.modernreactsnippetsplugin (1.0.1)
    com.nd.sdp.indexed.bundle.handler (1.1)
    com.intellij.ml.llm (232.9613)
    com.suming.react.PropTypes (1.1.5)
    izhangzhihao.rainbow.brackets (2023.3.3)
    com.dmarcotte.handlebars (232.8660.88)
    com.clutcher.comments_highlighter (2023.7.10)
    com.haulmont.rcb (2023.3-232)
    org.vepanimas.uml.javascript (0.2.0)
    com.github.blarc.gitlab-template-lint-plugin (1.13.2)
    com.github.nhat-phan.codecleaner (2019.2.1)
    com.previewjs.intellij.plugin (1.24.1)
    call-graph (0.1.17)

Kotlin: 232-1.9.0-IJ9559.62
```

I'm using Macbook Pro M2 16'

this is my cpu usage profiling for that event
[IU-232.9559.62_mdzhafarov_25.08.2023_14.46.26.zip](https://github.com/Codium-ai/codiumai-jetbrains-release/files/12438895/IU-232.9559.62_mdzhafarov_25.08.2023_14.46.26.zip)

**Comment by aldanchenko** [comment]
Hi @Villar74 

Thank you for reporting this information.

**Comment by ArtsiomCh** [comment]
@Vilar74 does that freeze happened on any project/file on your side or only with some particular project/file ? If latter, can we have that project ( or may be some synthetic one) to reproduce the issue?

**Comment by Villar74** [comment]
@ArtsiomCh that happens on every project i have. (Clean typescript project and react native typescript project). If i turn off all other extensions the problem still appears

**Comment by ArtsiomCh** [comment]
Ok, and when CodiumAI extension is uninstalled that freeze is not observed, correct?

**Comment by AndPim4912** [comment]
As an experiment deleted analytic/CodiumAnalyticService.class from codium-ai-plugin-0.6.02.jar
No more freezes) 
But analysis, sure, don't work in this case.

**Comment by ArtsiomCh** [comment]
Thanks for investigation! 
Will take a look on that place. Afaik it should not perform any lengthy action in EDT, but...

**Comment by AndPim4912** [comment]
Pycharm CodiumAI 0.6.03
Still get freezes:
`2023-09-08 19:10:36,687 [ 113047]   WARN - #ai.codium.analytic.CodiumAnalyticService - Fail to create Mixpanel user: Read timed out
2023-09-08 19:10:44,625 [ 120985]   WARN - #ai.codium.analytic.CodiumAnalyticService - Fail to send Mixpanel events: Read timed out
java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:288)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:484)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:589)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1430)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1401)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:220)
	at com.mixpanel.mixpanelapi.MixpanelAPI.sendData(MixpanelAPI.java:165)
	at com.mixpanel.mixpanelapi.MixpanelAPI.sendMessages(MixpanelAPI.java:203)
	at com.mixpanel.mixpanelapi.MixpanelAPI.deliver(MixpanelAPI.java:121)
	at com.mixpanel.mixpanelapi.MixpanelAPI.deliver(MixpanelAPI.java:101)
	at ai.codium.analytic.CodiumAnalyticService.sendMessages(CodiumAnalyticService.kt:72)
	at ai.codium.analytic.CodiumAnalyticService.addAlarmRequest$lambda$0(CodiumAnalyticService.kt:57)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:254)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:373)
	at com.intellij.util.Alarm$Request.run(Alarm.java:360)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2023-09-08 19:10:44,630 [ 120990]   WARN - #c.i.d.PerformanceWatcherImpl - UI was frozen for 10042ms, details saved to /home/razrab/.cache/JetBrains/PyCharm2023.2/log/threadDumps-freeze-20230908-191039-PY-232.8660.197-Net.poll-10sec
2023-09-08 19:11:04,676 [ 141036]   WARN - #c.i.d.PerformanceWatcherImpl - UI was frozen for 10045ms, details saved to /home/razrab/.cache/JetBrains/PyCharm2023.2/log/threadDumps-freeze-20230908-191059-PY-232.8660.197-Net.poll-10sec
2023-09-08 19:11:24,714 [ 161074]   WARN - #c.i.d.PerformanceWatcherImpl - UI was frozen for 10038ms, details saved to /home/razrab/.cache/JetBrains/PyCharm2023.2/log/threadDumps-freeze-20230908-191119-PY-232.8660.197-Net.poll-10sec
`
[
[1.txt](https://github.com/Codium-ai/codiumai-jetbrains-release/files/12561894/1.txt)
[2.txt](https://github.com/Codium-ai/codiumai-jetbrains-release/files/12561896/2.txt)
](url)

**Comment by ArtsiomCh** [comment]
Yep, fix is not released yet. 
Wait for 0.6.04 (shell be released beginning of next week)
