### ISSUE TITLE
[Exception][IDEA 2023.2.1] java.lang.IndexOutOfBoundsException: Wrong offset: -1. Should be in range: [0, 11586]

### ISSUE THREAD

**Issue by andersonblopes** [Codium-ai/codiumai-jetbrains-release#89]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.IndexOutOfBoundsException: Wrong offset: -1. Should be in range: [0, 11586]
	at com.intellij.openapi.editor.impl.LineSet.findLineIndex(LineSet.java:164)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineNumber(DocumentImpl.java:1001)
	at ai.codium.CodiumInlayProviderBase.addCodiumTestsGenerationInlay(CodiumInlayProviderBase.kt:85)
	at ai.codium.language.CodiumJavaInlayProvider.access$addCodiumTestsGenerationInlay(CodiumJavaInlayProvider.kt:16)
	at ai.codium.language.CodiumJavaInlayProvider$getCollectorFor$1.collect(CodiumJavaInlayProvider.kt:44)
	at com.intellij.codeInsight.hints.CollectorWithSettings.collectHints(InlayHintsUtils.kt:91)
	at com.intellij.codeInsight.hints.InlayHintsPass.doCollectInformation$lambda$0(InlayHintsPass.kt:46)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:110)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:91)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2023.2.1 Build: #IU-232.9559.62 August 23, 2023
Theme: Dark
JRE: 17.0.8+7-b1000.8, JetBrains s.r.o.
JVM: 17.0.8+7-b1000.8, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 14.0 (aarch64)

=== Plugins ===
Custom plugins: [GitToolBox (500.0.14+222), GenerateAllSetter (2.8.3), Terraform and HCL (232.8660.88), Database Navigator (3.3.9995.0), Package Search (232.9559.10), Jakarta EE: Batch Applications (232.8660.142), MapStruct Support (1.6.1), Solarized Themes (2.4.0), Jakarta EE: Server Faces (JSF) (232.8660.142), Spring Batch (232.8660.142), Diagrams.net Integration (0.2.4), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.6.00), SwaggerHub API Design by SmartBear (1.0.11), SonarLint (8.5.1.75093), Java Visualizer (2.2.1), Guice (232.8660.142), Properties to YAML Converter (1.0.2), .ignore (4.5.1), JPA Buddy (2023.3.3-232), Convert YAML and Properties File (1.0.5), Rainbow Brackets (2023.3.3), Maven Helper (4.23.222.2964.0), CMD Support (1.0.5), CodeGlance Pro (1.7.4), JavaDoc (4.0.2), PMD (1.8.27), Resource Bundle Editor (232.8660.88), EnvFile (3.4.1), Jakarta EE: Web Services (JAX-WS) (232.8660.142), AsciiDoc (0.38.20), Nx Console Idea (0.58.0), .env files support (2023.2), Tabnine: AI Code Completion & Chat in Java JS/TS Python & More (1.0.48), Add to gitignore (0.3)]
Disabled plugins:[FTP/SFTP/WebDAV Connectivity (232.9559.62), Save Actions (2.3.0), FreeMarker (232.9559.62), Micronaut (232.9559.62), Android (2022.3.1 Final.232.9559.62), Batch Scripts Support (1.0.13), Space (232.9559.62), Eclipse Interoperability (232.9559.62), gRPC (232.9559.62), Less (232.9559.62), IDE Features Trainer (232.9559.62), Apache Velocity (232.9559.62), Node.js (232.9559.62), Ktor (232.9559.62), Refactor-X (232.9559.62), UI Designer (232.9559.62), XPathView + XSLT (232.9559.62), Bolt Toolkit (1.18.0), Plugin DevKit (232.9559.62), Mercurial (232.9559.62), GlassFish (232.9559.62), Jakarta EE: Enterprise Java Beans (EJB) (232.8660.142), Cucumber for Java (232.9559.62), Jakarta EE: Gradle Integration (232.9559.62), Subversion (232.9559.62), Styled Components & Styled JSX (232.9559.62), Cucumber for Groovy (232.9559.62), Code With Me (232.9559.62), SSH Remote Run (232.9559.62), RestfulToolkitX (2.1.5), Node.js Remote Interpreter (232.9559.62), ANSI Highlighter Premium (23.2.0), Android Design Tools (232.9559.62), JavaScript Intention Power Pack (232.9559.62), Ant (232.9559.62), Perforce Helix Core (232.9559.62), WildFly (232.9559.62), Gherkin (232.9559.62)]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/6y2Nvnhv) by [Unito](https://www.unito.io)

**Comment by aldanchenko** [comment]
Hi @andersonblopes

Thanks for reporting! Right now we are working on a fix.

Could you share steps to reproduce? Or any additional information? For example, maybe some additional configuration? Or maybe code style (formatting)?

Thank you!

Best regards,
Alex

**Comment by aldanchenko** [comment]
Hi @andersonblopes  

Please try to update to the new version.

Best regards,
Alex
