### ISSUE TITLE
[Exception][IDEA 2022.3.3] java.lang.IndexOutOfBoundsException: Wrong offset: -1. Should be in range: [0, 76635]

### ISSUE THREAD

**Issue by gepapageorgiou22** [Codium-ai/codiumai-jetbrains-release#91]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.IndexOutOfBoundsException: Wrong offset: -1. Should be in range: [0, 76635]
	at com.intellij.openapi.editor.impl.LineSet.findLineIndex(LineSet.java:166)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineNumber(DocumentImpl.java:1015)
	at com.intellij.codeInsight.hints.InlayHintsSinkImpl.addBlockElement(InlayHintsSinkImpl.kt:31)
	at ai.codium.CodiumInlayProviderBase.addCodiumTestsGenerationInlay(CodiumInlayProviderBase.kt:97)
	at ai.codium.language.CodiumJavaInlayProvider.access$addCodiumTestsGenerationInlay(CodiumJavaInlayProvider.kt:16)
	at ai.codium.language.CodiumJavaInlayProvider$getCollectorFor$1.collect(CodiumJavaInlayProvider.kt:44)
	at com.intellij.codeInsight.hints.CollectorWithSettings.collectHints(InlayHintsUtils.kt:92)
	at com.intellij.codeInsight.hints.InlayHintsPass.doCollectInformation$lambda$0(InlayHintsPass.kt:47)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1111)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:86)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2022.3.3 Build: #IU-223.8836.41 March 10, 2023
Theme: Darcula
JRE: 17.0.6+1-b653.34, JetBrains s.r.o.
JVM: 17.0.6+1-b653.34, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.5.1 (aarch64)

=== Plugins ===
Custom plugins: [Jakarta EE: Web Services (JAX-WS) (223.8214.16), Ideolog (222.1.0.0), Angular Component Folding (1.5.0), JPA Buddy (2023.3.3-223), AWS Toolkit (1.76-223), Big Data Tools (223.8836.7), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.6.01), Drools (223.8617.20)]
Disabled plugins:[Jakarta EE: Enterprise Java Beans (EJB) (223.7571.182)]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/d7iEAK78) by [Unito](https://www.unito.io)

**Comment by aldanchenko** [comment]
Hi @gepapageorgiou22 

Please try to update to the new version.

Best regards,
Alex
