### ISSUE TITLE
[Exception][IDEA 2023.2.1] com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.so...

### ISSUE THREAD

**Issue by absantanna2412** [Codium-ai/codiumai-jetbrains-release#95]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl #JAVA  because: different providers: com.intellij.psi.DummyHolderViewProvider{vFile=LightVirtualFile: \DummyHolder, content=VirtualFileContent{size=0}, eventSystemEnabled=false}(40506144); com.intellij.psi.SingleRootFileViewProvider{vFile=LightVirtualFile: \DummyHolder, content=VirtualFileContent{size=0}, eventSystemEnabled=true}(287a8672)
invalidated at: see attachment; Type element reference of class com.intellij.psi.impl.source.PsiFieldImpl #PsiFieldImpl, index=0 #Language: JAVA; augmenters=[com.intellij.psi.impl.source.JShellPsiAugmentProvider@50131cc1, com.intellij.psi.impl.RecordAugmentProvider@e4f8bf9, de.plushnikov.intellij.plugin.provider.LombokAugmentProvider@47cd00e3]
	at com.intellij.psi.impl.source.PsiClassReferenceType.resolveGenerics(PsiClassReferenceType.java:181)
	at com.intellij.psi.PsiClassType.equals(PsiClassType.java:97)
	at de.plushnikov.intellij.plugin.psi.LombokLightParameter.equals(LombokLightParameter.java:81)
	at java.base/java.util.Objects.equals(Objects.java:64)
	at java.base/java.util.Arrays.equals(Arrays.java:2979)
	at de.plushnikov.intellij.plugin.psi.LombokLightParameterListBuilder.equals(LombokLightParameterListBuilder.java:37)
	at de.plushnikov.intellij.plugin.psi.LombokLightMethodBuilder.equals(LombokLightMethodBuilder.java:326)
	at kotlin.jvm.internal.Intrinsics.areEqual(Intrinsics.java:167)
	at ai.codium.elements.CutElement.equals(CutElement.kt:126)
	at com.intellij.openapi.util.Comparing.equal(Comparing.java:32)
	at com.intellij.ide.structureView.newStructureView.StructureViewComponent$MyNodeWrapper.equals(StructureViewComponent.java:886)
	at java.base/java.util.HashMap$TreeNode.find(HashMap.java:2018)
	at java.base/java.util.HashMap$TreeNode.find(HashMap.java:2028)
	at java.base/java.util.HashMap$TreeNode.find(HashMap.java:2028)
	at java.base/java.util.HashMap$TreeNode.getTreeNode(HashMap.java:2040)
	at java.base/java.util.HashMap.getNode(HashMap.java:574)
	at java.base/java.util.HashMap.get(HashMap.java:556)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:442)

<TRIMMED STACKTRACE>

9)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:111)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:76)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:188)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:165)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:433)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:24)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2023.2.1 Build: #IU-232.9559.62 August 23, 2023
Theme: Dark
JRE: 17.0.8+7-b1000.8, JetBrains s.r.o.
JVM: 17.0.8+7-b1000.8, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [IntelliVue (1.1.41), Resource Bundle Editor (232.8660.88), .ignore (4.5.1), Package Search (232.9559.10), Tabnine: AI Code Completion & Chat in Java JS/TS Python & More (1.0.51), JPA Buddy (2023.3.3-232), Jakarta EE: Batch Applications (232.8660.142), Spring Batch (232.8660.142), OpenAPI (Swagger) Editor (1.66), Ideolog (222.1.0.0), JPA Support (2.1.0-RC3), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.6.02), Jakarta EE: Server Faces (JSF) (232.8660.142), Translation (3.5.2), Atom Material Icons (93.0.1), Nginx Configuration (2022.1.1), Rainbow Brackets (2023.3.4), Spring WebSocket (232.8660.142), Visual Studio Code Dark Plus Theme (2.8), String Manipulation (9.11.3)]
Disabled plugins:[Cucumber for Groovy (232.9559.62), Qodana (232.9559.62), GlassFish (232.9559.62), Gradle-Java-Analysis (232.9559.62), Android (2022.3.1 Final.232.9559.62), Gradle-Maven (232.9559.62), Kotlin (232-1.9.0-IJ9559.62), Refactor-X (232.9559.62), Apache Velocity (232.9559.62), Gradle-Java (232.9559.62), Jakarta EE: Gradle Integration (232.9559.62), Groovy (232.9559.62), Thymeleaf (232.9559.62), JavaFX (232.9559.62), Gradle Extension (232.9559.62), Quarkus (232.9559.62), Space (232.9559.62), Gradle Dependency Updater Implementation (232.9559.62), Mercurial (232.9559.62), Toml (232.9559.62), Ant (232.9559.62), Micronaut (232.9559.62), TestNG (232.9559.62), FreeMarker (232.9559.62), Plugin DevKit (232.9559.62), Android Design Tools (232.9559.62), Ktor (232.9559.62), WildFly (232.9559.62), Cucumber for Java (232.9559.62), UI Designer (232.9559.62), WSL Support Framework (232.9559.62), Perforce Helix Core (232.9559.62), Subversion (232.9559.62), Gherkin (232.9559.62), Gradle (232.9559.62)]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/V0p1czgD) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Hi, Thanks for reporting!
Very strange exception, seems to come from third party plugin: `de.plushnikov.intellij.plugin`
Was it one time exception or you see it often and can reproduce?

**Comment by absantanna2412** [comment]
Hi,

It was one time only, have no idea how to reproduce.

I think you can close this.

Best.

Alexandre

**Comment by ArtsiomCh** [comment]
Seems Lombok plugin related.
And it most likely will happen again.
So will wrap relevant code into try-catch to prevent it.
Thanks for reporting again!
