### ISSUE TITLE
[Exception][RubyMine 2023.2] *** exception class was changed or removed

### ISSUE THREAD

**Issue by OrenMag** [Codium-ai/codiumai-jetbrains-release#98]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
  A suspiciously high nesting of suppressPrioritizing, forgot to call restorePrioritizing?
  
  java.lang.Throwable
at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:131)
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:384)
at com.intellij.openapi.progress.impl.CoreProgressManager.suppressPrioritizing(CoreProgressManager.java:824)
at com.intellij.openapi.progress.impl.CoreProgressManager.avoidBlockingPrioritizingThread(CoreProgressManager.java:879)
at com.intellij.openapi.progress.impl.CoreProgressManager.sleepIfNeededToGivePriorityToAnotherThread(CoreProgressManager.java:840)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.runCheckCanceledHooks(ProgressManagerImpl.java:192)
at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:145)
at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:231)
at com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled(ProgressIndicatorProvider.java:23)
at com.intellij.psi.impl.source.tree.CompositeElement.getPsi(CompositeElement.java:676)
at com.intellij.psi.impl.source.SourceTreeToPsiMap.treeElementToPsi(SourceTreeToPsiMap.java:15)
at com.intellij.psi.impl.source.tree.SharedImplUtil.getParent(SharedImplUtil.java:33)
at com.intellij.psi.impl.source.tree.LeafPsiElement.getParent(LeafPsiElement.java:56)
at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getParent(PsiWalkingState.java:37)
at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getParent(PsiWalkingState.java:14)
at com.intellij.util.WalkingState.next(WalkingState.java:93)
at com.intellij.util.WalkingState.walkChildren(WalkingState.java:51)
at com.intellij.util.WalkingState.elementStarted(WalkingState.java:42)
at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:62)
at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
at com.intellij.psi.util.PsiTreeUtil$4.visitElement(PsiTreeUtil.java:929)
at com.intellij.lang.javascript.psi.ecma6.impl.TypeScriptEnumImpl.accept(TypeScriptEnumImpl.java:64)
at com.intellij.psi.util.PsiTreeUtil.processElements(PsiTreeUtil.java:925)
at com.intellij.psi.util.PsiTreeUtil.findChildOfType(PsiTreeUtil.java:232)
at com.intellij.psi.util.PsiTreeUtil.findChildOfType(PsiTreeUtil.java:198)
at ai.codium.elements.CutElement.findErrorChild(CutElement.kt:52)
at ai.codium.language.LanguageService.hasErrorElements(LanguageService.kt:49)
at ai.codium.ui.structureview.CodiumStructureViewRootElement.getChildren(CodiumStructureViewChildElement.kt:85)
at ai.codium.ui.structureview.CodiumStructureViewRootElement.getChildren(CodiumStructureViewChildElement.kt:69)
at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.initChildren(TreeElementWrapper.java:35)
at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.rebuildSubtree(CachingChildrenTreeNode.java:207)
at com.intellij.ide.uti

<TRIMMED STACKTRACE>

orUtils.java:76)
at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:133)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:114)
at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:111)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:76)
at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:188)
at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:165)
at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:433)
at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
at java.base/java.lang.Thread.run(Thread.java:833)

```

# Other Information
```
=== About ===
Build version: RubyMine 2023.2 Build: #RM-232.8660.186 July 26, 2023
Theme: Darcula
JRE: 17.0.7+7-b1000.6, JetBrains s.r.o.
JVM: 17.0.7+7-b1000.6, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 13.5.1 (aarch64)

=== Plugins ===
Custom plugins: [String Manipulation (9.7.1), GitHub Copilot (1.2.21.2995), RubyMine Help (222.4554.10), EnvFile (3.4.1), CommitPrefix (1.4.1), .env files support (2023.2), React snippets (1.1.1), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.5.29)]
Disabled plugins:[]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/L7t7GjkY) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Thanks for reporting, we have that hard to catch issue for a long time. Would you mind please follow the https://github.com/Codium-ai/codiumai-jetbrains-release/issues/55#issuecomment-1622995021 to find threadDump.txt and provide it to them for analyzing:


> Hi, I am from the JetBrains team. If you see this error in the IDEA's IDE fatal error dialog, there should be a threadDump.txt attachment in the left list. If you don't have it, you could also use the IDE main menu Help | Collect Logs and Diagnostic Data to get the full log, upload it here https://uploads.jetbrains.com/, and share the upload id so we could check any clues there.



PS Also would be nice if you can share some more details when it happened, cause we can't reproduce it :(
Can you reproduce that issue? What kind/size of the project you have? Any specific action you did just before it happened?

**Comment by ArtsiomCh** [comment]
Seems like we fixed it in latest versions, please feel free to report if experience it again!
