### ISSUE TITLE
[Exception][PyCharm 2022.3.1] A suspiciously high nesting of suppressPrioritizing, forgot to call restorePrioritizing?

### ISSUE THREAD

**Issue by mukhammad-irmatov** [Codium-ai/codiumai-jetbrains-release#99]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:127)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:212)
	at com.intellij.openapi.progress.impl.CoreProgressManager.suppressPrioritizing(CoreProgressManager.java:809)
	at com.intellij.openapi.progress.impl.CoreProgressManager.avoidBlockingPrioritizingThread(CoreProgressManager.java:864)
	at com.intellij.openapi.progress.impl.CoreProgressManager.isLowPriorityReallyApplicable(CoreProgressManager.java:844)
	at com.intellij.openapi.progress.impl.CoreProgressManager.sleepIfNeededToGivePriorityToAnotherThread(CoreProgressManager.java:823)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runCheckCanceledHooks(ProgressManagerImpl.java:191)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:147)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:221)
	at com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled(ProgressIndicatorProvider.java:23)
	at com.intellij.psi.impl.source.tree.CompositeElement.getPsi(CompositeElement.java:687)
	at com.intellij.psi.impl.source.SourceTreeToPsiMap.treeElementToPsi(SourceTreeToPsiMap.java:16)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:37)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:744)
	at com.intellij.psi.util.PsiTreeUtil.getChildrenOfAnyType(PsiTreeUtil.java:398)
	at ai.codium.language.PyLanguageService.doGetFileSupportedElements$codium_ai_plugin(PyLanguageService.kt:23)
	at ai.codium.language.LanguageService.hasErrorElements(LanguageService.kt:48)
	at ai.codium.ui.structureview.CodiumStructureViewRootElement.getChildren(CodiumStructureViewChildElement.kt:92)
	at ai.codium.ui.structureview.CodiumStructureViewRootElement.getChildren(CodiumStructureViewChildElement.kt:76)
	at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.initChildren(TreeElementWrapper.java:35)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.rebuildSubtree(CachingChildrenTreeNode.java:207)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.ensureChildrenAreInitialized(CachingChildrenTreeNode.java:41)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.getChildren(CachingChildrenTreeNode.java:33)
	at com.intellij.ide.structureView.newStructureView.StructureViewComponent$MyNodeWrapper.getChildren(StructureViewComponent.java:831)
	at com.intellij.ide.util.treeView.smartTree.SmartTreeStructure.getChildElements(SmartTreeStructure.java:62)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:412)
	at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:330)
	at com.intellij.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:324)
	at com.intellij.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:344)
	at com

<TRIMMED STACKTRACE>

Utils.java:71)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:109)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:68)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:68)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:106)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:71)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:187)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:165)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:475)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:243)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:216)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:205)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

# Other Information
```
=== About ===
Build version: PyCharm 2022.3.1 Build: #PY-223.8214.51 December 20, 2022
Theme: Darcula
JRE: 17.0.5+1-b653.23, JetBrains s.r.o.
JVM: 17.0.5+1-b653.23, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 12.6.3 (aarch64)

=== Plugins ===
Custom plugins: [Requirements (2022.4.1), .env files support (2022.3), CodiumAI - Meaningful tests powered by TestGPT-1 and GPT-3.5&4 (0.5.22), Bito – ChatGPT to write code, explain code, create tests (1.0.133)]
Disabled plugins:[]
```

┆Issue is synchronized with this [Trello card](https://trello.com/c/nCQ2VXCY) by [Unito](https://www.unito.io)

**Comment by aldanchenko** [comment]
Hi @mukhammad-irmatov 👋

Thanks for reporting! Could you please share some steps to reproduce this issue or any additional details?

Best regards,
Alex

**Comment by ArtsiomCh** [comment]
Would you mind please follow the https://github.com/Codium-ai/codiumai-jetbrains-release/issues/55#issuecomment-1622995021 to find threadDump.txt and provide it to them for analyzing:

> Hi, I am from the JetBrains team. If you see this error in the IDEA's IDE fatal error dialog, there should be a threadDump.txt attachment in the left list. If you don't have it, you could also use the IDE main menu Help | Collect Logs and Diagnostic Data to get the full log, upload it here https://uploads.jetbrains.com/, and share the upload id so we could check any clues there.


PS Also would be nice if you can share some more details when it happened, cause we can't reproduce it :(
Can you reproduce that issue? What kind/size of the project you have? Any specific action you did just before it happened?
